const expertiseAndResourceSuggestions = [
  '2D cultures',
  '3D cultures',
  '3D human PD chip',
  'A53T',
  'Adapter ligation',
  'Adaptive and innate immunity',
  'Adaptive immune cells',
  'Adaptive immunity',
  'Adenosine receptors',
  'Aggregation',
  'Aging',
  'Algorithms',
  'Alpha-synuclein',
  'Animal models',
  'Antibodies',
  'Antigen-specific response',
  'Antimicrobial peptide',
  'Antioxidants',
  'Antiviral therapy',
  'Artificial intelligence',
  'Assay development',
  'Astrocytes',
  'ATP13A2',
  'Atypical Parkinson’s',
  'Autoimmunity',
  'Autonomic dysfunction',
  'Autophagy',
  'Autosomal recessive juvenile parkinsonism (ARJP)',
  'Autosomal recessive PD',
  'Bacteria',
  'Basal Ganglia',
  'Behavioral pharmacology',
  'Biochemistry',
  'Bioinformatics',
  'Biomarker assay',
  'Biomarker discovery',
  'Biomarker validation',
  'Bitopertin',
  'Blood',
  'Blood-Brain barrier',
  'BRAF',
  'Brain',
  'Brain-on-a-chip',
  'C. elegans',
  'Caffeine',
  'Cancer',
  'Cas9',
  'Catecholamines',
  'Cell biology',
  'Cell replacement',
  'Cellular assays',
  'Cellular toxicity mechanisms',
  'Chaperones',
  'Chemical-genetic interaction',
  'Cholesterol',
  'Choroid plexus',
  'Ciliogenesis',
  'Circadian rhythm',
  'Clinical feature',
  'Clinical measures',
  'Clinical trials',
  'Cluster analysis',
  'Cognitive decline',
  'Cognitive dysfunction/dementia',
  'Collaboration',
  'Computer modeling',
  'Conformational strains',
  'Cortex',
  'Corticospinal',
  'CRISPR/Cas9',
  'Cross-species',
  'Cryo-EM',
  'Cryo-ET',
  'DAMPs (Damage-associated molecular patterns)',
  'Data science',
  'Data sharing',
  'Deep learning',
  'Dendritic cells',
  'Depression',
  'Deubiquitinases',
  'Development',
  'Developmental biology',
  'Diabetes',
  'Digital measures',
  'Digital pathology',
  'Disease heterogeneity',
  'Disease mechanisms',
  'Disease models',
  'Disease modification',
  'Disease penetrance',
  'Disease risks',
  'DJ-1',
  'DMT1 - divalent metal (ion) transporter 1',
  'DNA damage',
  'DNA damage response',
  'DNA repair',
  'Dopamine neuron subtypes',
  'Dopamine release',
  'Drosophila',
  'Drug repurposing',
  'Drug targets',
  'Dyskinesia',
  'Early onset PD',
  'Ecogenomics',
  'Electron microscopy',
  'Electrophysiology',
  'Endolysosomal dysfunction',
  'Endosomes',
  'Energy failure',
  'Enteric nervous system',
  'Enteroendocrine cells',
  'Environment',
  'Environmental chemicals',
  'Environmental toxins',
  'Epidemiology',
  'Epigenomics',
  'ER tubular network',
  'Ethnic diversity',
  'Excitability',
  'Excitotoxicity',
  'Exercise',
  'Exosomes',
  'Extracellular Space',
  'Eyes',
  'FIB-SEM',
  'Fibril',
  'Fluid-based biomarkers',
  'Functional biotype',
  'Functional genomics',
  'Functional impairment',
  'Functional phenotype',
  'GABA',
  'GBA (Glucocerebrosidase)',
  'Gender',
  'Gene therapy',
  'Gene-environment interactions',
  'Genetic interactions',
  'Genetic risk',
  'Genetic screen',
  'Genetic susceptibility',
  'Genetic targets',
  'Genetic variants',
  'Genetics',
  'Genomics',
  'GI/gut motility',
  'Glia',
  'Glutamate receptors',
  'Glutamate signaling',
  'Glycosphingolipids',
  'GPNNB',
  'Grants administration',
  'Grants management',
  'Gut',
  'Gut-brain',
  'GWAS',
  'Herpes simplex virus (HSV)',
  'hiPSCs (Human induced pluripotent stem cells)',
  'hPSCs (Human pluripotent stem cells)',
  'Human brains',
  'Human-mouse xenograft model',
  'Idiopathic',
  'iGlia (induced glia)',
  'Imaging',
  'Immune activation',
  'Immune response',
  'Immune tolerance',
  'Immunity',
  'Immunotherapy',
  'in situ',
  'in situ RNA analytics',
  'in vivo',
  'Induced pluripotent stem cells (iPS/iPSCs)',
  'iNeurons (induced neurons)',
  'Infection',
  'Infection models',
  'Inflammasomes',
  'Inflammation',
  'Innate immunity',
  'Interorganellar contact sites',
  'Intracellular',
  'intracellular transport',
  'Ion channels and receptors',
  'iPSC neurons',
  'iPSCs (Induced pluripotent stem cells)',
  'Iron',
  'Iron and copper',
  'Isogenic',
  'Kinase',
  'Kinase dynamics',
  'Leukocyte trafficking',
  'Lewy bodies',
  'Lifespan',
  'Lipidomics',
  'Lipids',
  'Liquid-liquid phase separation',
  'Live-imaging',
  'Locus coeruleus',
  'Long-read sequencing',
  'LRRK2',
  'LRRK2 pathway',
  'Lymphocytes',
  'Lysosomal -omics',
  'Lysosomal dysfunction',
  'Lysosomal homeostasis',
  'Lysosomes',
  'Machine learning',
  'Manganese',
  'Mass',
  'Melanoma',
  'Membrane traffic',
  'Membrane trafficking',
  'Membrane-protein interaction',
  'Metabolism',
  'Metabolomics',
  'Microbial amyloid proteins',
  'Microbial exposure',
  'Microbiome',
  'Microbiome',
  'Microfluidic devices',
  'Microglia',
  'Microtubule',
  'miRNA',
  'Miro1',
  'Mitochondria',
  'Mitochondria-nucleus communication',
  'Mitochondria/lysosome axis',
  'Mitochondrial',
  'Mitochondrial dysfunction',
  'Mitochondrial morphology',
  'mitoPARK',
  'Mitophagy',
  'Modifiers',
  'Molecular chaperone',
  'Molecular mechanism',
  'Monocyte',
  'Mortality',
  'Motor symptoms',
  'Mouse',
  'MPTP',
  'MSA (Multiple system atrophy)',
  'mTOR',
  'Multi-electrode array',
  'Multi-omics',
  'Mutational signature',
  'Mutations',
  'Nanobodies',
  'Network analysis',
  'Networking',
  'Neural circuitry',
  'Neuro-immune',
  'Neuro-immune interactions',
  'Neuro-immune sensitization',
  'Neurobehavioral',
  'Neurobiology',
  'Neurodegeneration',
  'Neuroimaging',
  'Neuroinflammation',
  'Neuroinflammation',
  'Neuromelanin',
  'Neuromodulation',
  'Neurons',
  'Neuropharmacology',
  'Neuroprotective/regenerative',
  'Neuroregenerative',
  'Neurotransmitters',
  'Neutrophils',
  'Next generation neuropathology',
  'Next generation sequencing',
  'NF-kappaB',
  'Non-coding RNA',
  'Non-Human Primate',
  'Non-motor symptoms',
  'Non-profit health sector',
  'Noradrenaline',
  'Nurr1',
  'Olfactory dysfunc+A14:A96tion',
  'Olfactory dysfunction',
  'Olfactory mucosa',
  'Oligomeric assays',
  'Optogenetics',
  'Organelle contact sites',
  'Organoid',
  'Oxidative stress',
  'PAK6',
  'Parkin (PARK2)',
  "Parkinson's disease",
  'Parkinsonism',
  'Parkinsonism',
  'Pathogens',
  'Pathology',
  'Pathomechanism',
  'Pathophysiology',
  'Pathophysiology',
  'Patient registry',
  'PD progression',
  'PD subtypes',
  'Peripheral immune system',
  'Perturb-seq',
  'Pesticides',
  'PET (Positron emission tomography)',
  'PGRN (Progranulin)',
  'Phagocytosis',
  'Pharmacokinetics',
  'Phenomics',
  'Phenotypic variability',
  'Phosphatase',
  'Phospho-code',
  'Phosphorylation',
  'PINK1',
  'Placebo response',
  'Plasma',
  'Plasmids',
  'Plasticity',
  'Polyamine',
  'Postural instability',
  'Primate',
  'Prion',
  'Prodromal PD',
  'Prodrome',
  'Program operations',
  'Project management',
  'Propagation',
  'PROTAC (Proteolysis targeting chimera)',
  'Protein aggregates',
  'Protein degradation',
  'Protein handling',
  'Protein-interaction/signaling',
  'Protein-protein interaction',
  'Protein-protein interaction tags',
  'Proteins',
  'Proteomics',
  'Proteostasis',
  'Proteotoxicity',
  'Proximity proteomics',
  'PRS (Polygenic risk score)',
  'PTEN',
  'Rab',
  'Rab GTPases',
  'Rab29',
  'Rapid autopsy',
  'Reactive astrocytes',
  'Regulatory gene networks',
  'Regulome glia ATAC-seq',
  'Retromer',
  'Risk genes',
  'Risk loci',
  'RNA binding proteins',
  'RNAi',
  'scRNAseq (Single-cell RNA-seq)',
  'Seeding assays',
  'Senescence',
  'Senolytic',
  'Single cell analysis',
  'Single cell genomics',
  'Single cell multi-omics',
  'Single cell transcriptomics',
  'Single-cell analysis',
  'Single-cell eQTL',
  'Single-cell eqtl',
  'Single-cell multi-omics',
  'Single-cell transcriptomics',
  'snRNA-seq (Single-nuclear RNA-seq)',
  'Sleep disorders',
  'SNpc (Substantia nigra pars compacta)',
  'snRNA-seq (Single-nuclear RNA-seq)',
  'Somatic gene recombination',
  'Somatic genetic mutation',
  'Spatial transcriptomics',
  'Spectrometry',
  'Sphingolipids',
  'Spine density',
  'Stem cells',
  'Stem cells - embryonic',
  'Stem cells – adult',
  'Stem cells – animal',
  'Stem cells – embryonic',
  'Stem cells – fetal',
  'Strain',
  'Stratification',
  'Structural biology',
  'Structure',
  'Structure & Function',
  'Structure guided drug design',
  'Substantia nigra pars compacta (SNpc)',
  'Substantia nigra pars compacta (SNpc)]',
  'Super-resolution microscopy',
  'Surgical',
  'Synapse',
  'Synaptic dysfunction',
  'Synaptic trafficking',
  'Synaptic transmission',
  'Synaptic vesicle exocytosis',
  'Systems biology',
  'Systems genetics',
  'Systems immunology',
  'T cell receptors (TCR)',
  'T cells',
  'T lymphocytes',
  'Target validation',
  'TCR repertoire',
  'TCRs (T cell Receptors)',
  'Temperature',
  'TGN (Trans-Golgi network)',
  'Therapeutic development',
  'Trans-Golgi network (TGN)',
  'Transcranial Focused Ultrasound (tFUS)',
  'Transcriptional regulation',
  'Transcriptomics',
  'Transdifferentiation',
  'Transport',
  'Transposable elements',
  'Tropic factors/GDNF',
  'Tunneling Nanotubes',
  'Ubiquitin',
  'UCH-L1',
  'Ultrastructure microscopy',
  'vATPase a1',
  'Ventral Tegmental Area',
  'Vesicle trafficking',
  'Viral vectors',
  'VPS35',
  'Xenobiotics',
];

export default expertiseAndResourceSuggestions;
