name: 'ECR Repository Name'
description: 'Outputs the name of the image'
inputs:
  repository-name:
    description: 'Name of the repository'
    required: true
  aws-account-id:
    description: 'AWS Access Account ID'
    required: false
    default: '249832953260'
  aws-region:
    description: 'AWS Region for ECR'
    required: false
    default: ap-southeast-2
  image-tag:
    description: 'Image Tag'
    required: false
    default: 8bf2c61ef5a3d31df5b6d670085335fe4de93734
outputs:
  image-name:
    description: 'Name of image'
    value: ${{ steps.get-image-name.outputs.image-name }}
runs:
  using: 'composite'
  steps:
    - name: Output Image Name
      id: get-image-name
      shell: bash
      env:
        ACCOUNT_ID: ${{ inputs.aws-account-id }}
        REPOSITORY: ${{ inputs.aws-repository }}
        REPOSITORY_NAME: ${{ inputs.repository-name }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        REGION: ${{ inputs.aws-region }}
      run: |
        IMAGE_NAME="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG"
        echo "::set-output name=image-name::$IMAGE_NAME"
