name: 'Setup'
description: 'Generates the environment variables for the workflow'
inputs:
  environment-name:
    description: 'Current environment'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup
      shell: bash
      run: |
        if [ "$ENVIRONMENT_NAME" = "Branch" ]; then
          echo "Setting up branch environment"
          PR_NUMBER=${{ github.event.number || github.event.inputs.prNumber }}
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "SQUIDEX_APP_NAME=$PR_NUMBER" >> $GITHUB_ENV

          echo "ALGOLIA_INDEX=asap-hub_CI-$PR_NUMBER" >> $GITHUB_ENV
          ASAP_HOSTNAME="hub.asap.science"

          echo "ASAP_HOSTNAME=$ASAP_HOSTNAME" >> $GITHUB_ENV
          echo "ASAP_API_URL=https://api-$PR_NUMBER.$ASAP_HOSTNAME" >> $GITHUB_ENV
          echo "ASAP_APP_URL=https://$PR_NUMBER.$ASAP_HOSTNAME" >> $GITHUB_ENV
          echo "SLS_STAGE=$PR_NUMBER" >> $GITHUB_ENV

          APP_RELEASE='${{ github.run_id }}-dev'
          echo "APP_RELEASE=$APP_RELEASE" >> $GITHUB_ENV
        elif [ "$ENVIRONMENT_NAME" = 'Development' ]; then
          echo "Setting up development environment"
        elif [ "$ENVIRONMENT_NAME" = 'Production' ]; then
          echo "Setting up production environment"
        else
          echo "Unknown environment: $ENVIRONMENT_NAME"
          exit 1
        fi

        cat ".github/environment/All.env" >> $GITHUB_ENV
        cat ".github/environment/$ENVIRONMENT_NAME.env" >> $GITHUB_ENV
      env:
        ENVIRONMENT_NAME: ${{ inputs.environment-name }}
