name: 'Setup'
description: 'Generates the environment variables for the workflow'
inputs:
  environment-name:
    description: 'Current environment'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup
      shell: bash
      run: |
        if [ "$ENVIRONMENT_NAME" = "Branch" ]; then
          echo "Setting up branch environment"
        elif [ "$ENVIRONMENT_NAME" == 'Development' ]; then
          echo "Setting up development environment"
        elif [ "$ENVIRONMENT_NAME" == 'Production' ]; then
          echo "Setting up production environment"
        else
          echo "Unknown environment: $ENVIRONMENT_NAME"
          exit 1
        fi

        cat ".github/environment/All.env" >> $GITHUB_ENV
        cat ".github/environment/$ENVIRONMENT_NAME.env" >> $GITHUB_ENV
      env:
        ENVIRONMENT_NAME: ${{ inputs.environment-name }}
