name: 'Setup'
description: 'Generates the environment variables for the workflow'
inputs:
  environment-name:
    description: 'Current environment'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup
      shell: bash
      run: |
        if [ "$ENVIRONMENT_NAME" = "Branch" ]; then
          echo "Setting up branch environment"
          PR_NUMBER=${{ github.event.number || github.event.inputs.prNumber }}
          echo "SQUIDEX_APP_NAME=$PR_NUMBER" >> $GITHUB_ENV

          echo "ALGOLIA_INDEX=asap-hub_CI-$PR_NUMBER" >> $GITHUB_ENV
        elif [ "$ENVIRONMENT_NAME" == 'Development' ]; then
          echo "Setting up development environment"
        elif [ "$ENVIRONMENT_NAME" == 'Production' ]; then
          echo "Setting up production environment"
        else
          echo "Unknown environment: $ENVIRONMENT_NAME"
          exit 1
        fi

        cat ".github/environment/All.env" >> $GITHUB_ENV
        cat ".github/environment/$ENVIRONMENT_NAME.env" >> $GITHUB_ENV

        echo cat $GITHUB_ENV
      env:
        ENVIRONMENT_NAME: ${{ inputs.environment-name }}
