initScope: asap-hub

packageExtensions:
  '@serverless/components@2.34.9':
    dependencies:
      inquirer: ^7.0.0
  '@storybook/core@6.1.11':
    dependencies:
      typescript: ~3.9.7
  '@storybook/react@6.1.11':
    dependencies:
      typescript: ~3.9.7
  node-fetch@3.0.0-beta.8:
    dependencies:
      domexception: ^2.0.1
  'react-dev-utils@>=10 <=11':
    dependencies:
      typescript: ~3.9.7
      webpack: ^4.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-dotenv.cjs
    spec: 'https://unpkg.com/yarn-plugin-dotenv@0.1.1/bundles/@yarnpkg/plugin-dotenv.js'

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.4.0.cjs
