initScope: asap-hub

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.js
    spec: '@yarnpkg/plugin-constraints'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: '@yarnpkg/plugin-typescript'

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.0.0-rc.33.js

packageExtensions:
  '@storybook/react@6.0.0-beta.12':
    dependencies:
      'typescript': '~3.8.3'
  'react-color@2.18.1':
    dependencies:
      'react': '^16.13.1'
  'react-docgen-typescript-loader@3.7.2':
    dependencies:
      'webpack': '*'
  'serverless-webpack@5.3.2':
    dependencies:
      'typescript': '~3.8.3'
