initScope: asap-hub

nodeLinker: pnp

packageExtensions:
  "@serverless/components@2.34.9":
    dependencies:
      inquirer: ^7.0.0
  "@storybook/core@6.2.9":
    dependencies:
      webpack: ^5.0.0
  debug@*:
    dependencies:
      supports-color: "*"
  jest-cli@*:
    dependencies:
      "@jest/console": "*"
      "@jest/reporters": "*"
  jest-config@*:
    dependencies:
      jest-runtime: "*"
  node-fetch@3.0.0-beta.8:
    dependencies:
      domexception: ^2.0.1
  react-dev-utils@>=10 <=11:
    dependencies:
      typescript: ~4.1.0
      webpack: ^4.0.0
  serverless-webpack@5.5.0:
    dependencies:
      typescript: ~4.1.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-dotenv.cjs
    spec: "https://unpkg.com/yarn-plugin-dotenv@0.1.1/bundles/@yarnpkg/plugin-dotenv.js"

pnpEnableEsmLoader: true

pnpMode: loose

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-3.7.0.cjs
