initScope: asap-hub

packageExtensions:
  '@storybook/react@6.0.4':
    dependencies:
      typescript: ~3.9.7
  react-color@2.18.1:
    dependencies:
      react: ^16.13.1
  react-docgen-typescript-loader@3.7.2:
    dependencies:
      webpack: '*'
  serverless-webpack@5.3.2:
    dependencies:
      typescript: ~3.9.7

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.0.0-rc.36.cjs
