initScope: asap-hub

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.js
    spec: '@yarnpkg/plugin-constraints'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: '@yarnpkg/plugin-workspace-tools'

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.0.0-rc.33.js
