initScope: asap-hub

packageExtensions:
  '@serverless/components@2.34.9':
    dependencies:
      inquirer: ^7.0.0
  '@storybook/react@6.0.4':
    dependencies:
      typescript: ~3.9.7
  '@vercel/nft@0.9.3':
    dependencies:
      acorn: ^6.0.1
  node-fetch@3.0.0-beta.8:
    dependencies:
      domexception: ^2.0.1
  react-color@2.18.1:
    dependencies:
      react: ^16.13.1
  react-docgen-typescript-loader@3.7.2:
    dependencies:
      webpack: ^4.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-dotenv.cjs
    spec: 'https://unpkg.com/yarn-plugin-dotenv@0.1.1/bundles/@yarnpkg/plugin-dotenv.js'

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.2.2.cjs
