name: 'Import entity'
description: 'Export entity data from Contentful and into Algolia index'
inputs:
  algolia-api-key:
    description: 'Algolia api key name'
    required: true
  algolia-app-id:
    description: 'Algolia app id name'
    required: true
  algolia-index:
    description: 'Algolia index name'
    required: true
  app:
    description: 'crn or gp2'
    required: true
  entity-type:
    description: 'Entity type (ie. "user")'
    required: true
  contentful-space-id:
    description: 'Contentful Space ID'
    required: true
  contentful-env:
    description: 'Contentful environment'
    required: true
  contentful-access-token:
    description: 'Contentful access token'
    required: true
  contentful-management-token:
    description: 'Contentful management token'
    required: true
outputs:
  algolia-app-id:
    description: 'Algolia App ID'
    value: '${{ steps.keys.outputs.algolia-app-id }}'
  algolia-api-key:
    description: 'Algolia API Key'
    value: '${{ steps.keys.outputs.algolia-api-key }}'
runs:
  using: 'composite'
  steps:
    - name: Import Entity
      shell: bash
      run: |
        crn_entities=(events external-authors interest-groups news research-outputs teams tutorials users working-groups)
        gp2_entities=(events external-users news outputs projects users working-groups)

        ["${{ inputs.app }}" == "crn"] && entities=("${crn_entities[@]}") || entities=("${gp2_entities[@]}")

        if [[ "$ENTITY" == "all" ]]; then
          for entity in "${entities[@]}"; do yarn export:entity:${{ inputs.app }} $entity -f $entity.json
          jq -c '.[]' $entity.json | algolia objects import $ALGOLIA_INDEX -F -; done
        else
          yarn export:entity:${{ inputs.app }} $ENTITY -f $ENTITY.json
          jq -c '.[]' $ENTITY.json | algolia objects import $ALGOLIA_INDEX -F -
        fi
      env:
        ALGOLIA_APPLICATION_ID: ${{ inputs.algolia-app-id }}
        ALGOLIA_ADMIN_API_KEY: ${{ inputs.algolia-api-key }}
        ALGOLIA_INDEX: ${{ inputs.algolia-index }}
        ENTITY: ${{ inputs.entity-type }}
        CONTENTFUL_ACCESS_TOKEN: ${{ inputs.contentful-access-token }}
        CONTENTFUL_ENV_ID: ${{  inputs.contentful-env }}
        CONTENTFUL_MANAGEMENT_ACCESS_TOKEN: ${{  inputs.contentful-management-token }}
        CONTENTFUL_SPACE_ID: ${{ inputs.contentful-space-id }}
