name: Teardown environment
description: Teardown a PR environment
inputs:
  prNumber:
    required: true
    description: Choose which PR number to destroy
runs:
  using: composite
  steps:
    - name: Remove CF Stack
      if: ${{ inputs.prNumber != 'production' && env.prNumber != 'dev' }}
      run: yarn sls remove --verbose
      shell: bash
      env:
        SLS_STAGE: ${{ inputs.prNumber }}
        NODE_ENV: 'production'
        ASAP_HOSTNAME: 'hub.asap.science'
        ASAP_API_URL: 'https://api-${{ inputs.prNumber }}.hub.asap.science'
        ASAP_APP_URL: 'https://${{ inputs.prNumber }}.hub.asap.science'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACM_CERTIFICATE_ARN: ${{ secrets.AWS_ACM_CERTIFICATE_ARN }}
        AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: Remove GitLab CF Stack
      env:
        SLS_STAGE: ${{ inputs.prNumber }}-gitlab
      if: ${{ env.SLS_STAGE != 'production' && env.SLS_STAGE != 'dev' }}
      shell: bash
      run: yarn sls remove --verbose
    - name: Delete PR Squidex App
      run: python ci/integration/scripts/delete-app.py
      shell: bash
      env:
        SQUIDEX_APP_NAME: ${{ inputs.prNumber }}
        SQUIDEX_CLIENT_ID: ${{ secrets.SQUIDEX_CLIENT_ID_TEST }}
        SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET_TEST }}
    - name: Delete PR Squidex App created by gitlab
      env:
        SQUIDEX_APP_NAME: ${{ inputs.prNumber }}-gitlab
      shell: bash
      run: python ci/integration/scripts/delete-app.py
