name: Auth0 Checks
description: Defines outputs to set up a dedicated Auth0 environment

inputs:
  app:
    description: 'crn or gp2'
    required: true
    type: string
  create-dedicated-auth0-env:
    description: 'if a dedicated env should be created'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Determine Environment
      id: determine-environment
      shell: bash
      run: |
        echo "determine env for auth0"
