/* eslint-disable */
import * as graphql from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

const documents = {
  '\n  fragment CalendarsContentData on Calendars {\n    sys {\n      id\n      firstPublishedAt\n      publishedAt\n      publishedVersion\n    }\n    googleCalendarId\n    name\n    color\n    syncToken\n    resourceId\n    expirationDate\n  }\n':
    graphql.CalendarsContentDataFragmentDoc,
  '\n  query FetchCalendarById($id: String!) {\n    calendars(id: $id) {\n      ...CalendarsContentData\n    }\n  }\n  \n':
    graphql.FetchCalendarByIdDocument,
  '\n  query FetchCalendars(\n    $limit: Int\n    $skip: Int\n    $order: [CalendarsOrder]\n    $where: CalendarsFilter\n  ) {\n    calendarsCollection(\n      limit: $limit\n      skip: $skip\n      order: $order\n      where: $where\n    ) {\n      total\n      items {\n        ...CalendarsContentData\n      }\n    }\n  }\n  \n':
    graphql.FetchCalendarsDocument,
  '\n  fragment ContributingCohortsContentData on ContributingCohorts {\n    sys {\n      id\n    }\n    name\n  }\n':
    graphql.ContributingCohortsContentDataFragmentDoc,
  '\n  query FetchContributingCohorts(\n    $limit: Int\n    $skip: Int\n    $order: [ContributingCohortsOrder]\n  ) {\n    contributingCohortsCollection(limit: $limit, skip: $skip, order: $order) {\n      total\n      items {\n        ...ContributingCohortsContentData\n      }\n    }\n  }\n  \n':
    graphql.FetchContributingCohortsDocument,
  '\n  fragment EventsContent on Events {\n    sys {\n      id\n      publishedAt\n      publishedVersion\n    }\n    description\n    endDate\n    endDateTimeZone\n    startDate\n    startDateTimeZone\n    meetingLink\n    hideMeetingLink\n    eventLink\n    status\n    hidden\n    tags\n    title\n    notesPermanentlyUnavailable\n    notes {\n      json\n      links {\n        entries {\n          inline {\n            sys {\n              id\n            }\n            __typename\n            ... on Media {\n              url\n            }\n          }\n        }\n        assets {\n          block {\n            sys {\n              id\n            }\n            url\n            description\n            contentType\n            width\n            height\n          }\n        }\n      }\n    }\n    notesUpdatedAt\n    videoRecordingPermanentlyUnavailable\n    videoRecording {\n      json\n      links {\n        entries {\n          inline {\n            sys {\n              id\n            }\n            __typename\n            ... on Media {\n              url\n            }\n          }\n        }\n        assets {\n          block {\n            sys {\n              id\n            }\n            url\n            description\n            contentType\n            width\n            height\n          }\n        }\n      }\n    }\n    videoRecordingUpdatedAt\n    presentationPermanentlyUnavailable\n    presentation {\n      json\n      links {\n        entries {\n          inline {\n            sys {\n              id\n            }\n            __typename\n            ... on Media {\n              url\n            }\n          }\n        }\n        assets {\n          block {\n            sys {\n              id\n            }\n            url\n            description\n            contentType\n            width\n            height\n          }\n        }\n      }\n    }\n    presentationUpdatedAt\n    meetingMaterialsPermanentlyUnavailable\n    meetingMaterials\n    calendar {\n      googleCalendarId\n      color\n      name\n    }\n    thumbnail {\n      url\n    }\n    speakersCollection(limit: 10) {\n      items {\n        title\n        user {\n          __typename\n          ... on ExternalUsers {\n            sys {\n              id\n            }\n            name\n            orcid\n          }\n          ... on Users {\n            sys {\n              id\n            }\n            firstName\n            lastName\n            onboarded\n            avatar {\n              url\n            }\n          }\n        }\n      }\n    }\n  }\n':
    graphql.EventsContentFragmentDoc,
  '\n  query FetchEventById($id: String!) {\n    events(id: $id) {\n      ...EventsContent\n    }\n  }\n  \n':
    graphql.FetchEventByIdDocument,
  '\n  query FetchEvents(\n    $limit: Int\n    $skip: Int\n    $order: [EventsOrder]\n    $where: EventsFilter\n  ) {\n    eventsCollection(limit: $limit, skip: $skip, order: $order, where: $where) {\n      total\n      items {\n        ...EventsContent\n      }\n    }\n  }\n  \n':
    graphql.FetchEventsDocument,
  '\n  query FetchEventsByUserId($id: String!, $limit: Int, $skip: Int) {\n    users(id: $id) {\n      linkedFrom {\n        eventSpeakersCollection(limit: 1) {\n          items {\n            linkedFrom {\n              eventsCollection(limit: $limit, skip: $skip) {\n                total\n                items {\n                  ...EventsContent\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n  \n':
    graphql.FetchEventsByUserIdDocument,
  '\n  query FetchEventsByExternalUserId($id: String!, $limit: Int, $skip: Int) {\n    externalUsers(id: $id) {\n      linkedFrom {\n        eventSpeakersCollection(limit: 1) {\n          items {\n            linkedFrom {\n              eventsCollection(limit: $limit, skip: $skip) {\n                total\n                items {\n                  ...EventsContent\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n  \n':
    graphql.FetchEventsByExternalUserIdDocument,
  '\n  fragment ExternalUsersContentData on ExternalUsers {\n    sys {\n      id\n      firstPublishedAt\n      publishedAt\n      publishedVersion\n    }\n    name\n    orcid\n  }\n':
    graphql.ExternalUsersContentDataFragmentDoc,
  '\n  query FetchExternalUsers(\n    $limit: Int\n    $skip: Int\n    $order: [ExternalUsersOrder]\n    $where: ExternalUsersFilter\n  ) {\n    externalUsersCollection(\n      limit: $limit\n      skip: $skip\n      order: $order\n      where: $where\n    ) {\n      total\n      items {\n        ...ExternalUsersContentData\n      }\n    }\n  }\n  \n':
    graphql.FetchExternalUsersDocument,
  '\n  fragment NewsContentData on News {\n    sys {\n      id\n      firstPublishedAt\n    }\n    title\n    shortText\n    sampleCount\n    articleCount\n    cohortCount\n    link\n    linkText\n    publishDate\n  }\n':
    graphql.NewsContentDataFragmentDoc,
  '\n  query FetchNewsById($id: String!) {\n    news(id: $id) {\n      ...NewsContentData\n    }\n  }\n  \n':
    graphql.FetchNewsByIdDocument,
  '\n  query FetchNews(\n    $limit: Int\n    $skip: Int\n    $order: [NewsOrder]\n    $where: NewsFilter\n  ) {\n    newsCollection(limit: $limit, skip: $skip, order: $order, where: $where) {\n      total\n      items {\n        ...NewsContentData\n      }\n    }\n  }\n  \n':
    graphql.FetchNewsDocument,
  '\n  fragment PageContentData on Pages {\n    sys {\n      id\n    }\n    title\n    path\n    shortText\n    text {\n      json\n      links {\n        entries {\n          inline {\n            sys {\n              id\n            }\n            __typename\n            ... on Media {\n              url\n            }\n          }\n        }\n        assets {\n          block {\n            sys {\n              id\n            }\n            url\n            description\n            contentType\n            width\n            height\n          }\n        }\n      }\n    }\n    link\n    linkText\n  }\n':
    graphql.PageContentDataFragmentDoc,
  '\n  query FetchPages($where: PagesFilter) {\n    pagesCollection(limit: 100, where: $where) {\n      total\n      items {\n        ...PageContentData\n      }\n    }\n  }\n  \n':
    graphql.FetchPagesDocument,
  '\n  fragment UsersContentData on Users {\n    sys {\n      id\n      firstPublishedAt\n      publishedAt\n      publishedVersion\n    }\n    activatedDate\n    firstName\n    lastName\n    avatar {\n      url\n    }\n    degrees\n    country\n    city\n    region\n    email\n    alternativeEmail\n    telephoneCountryCode\n    telephoneNumber\n    keywords\n    biography\n    questions\n    fundingStreams\n    blog\n    linkedIn\n    twitter\n    github\n    googleScholar\n    orcid\n    researchGate\n    researcherId\n    connections\n    role\n    onboarded\n    positions\n    activatedDate\n    contributingCohortsCollection(limit: 100) {\n      items {\n        contributingCohort {\n          sys {\n            id\n          }\n          name\n        }\n        role\n        studyLink\n      }\n    }\n    linkedFrom {\n      projectMembershipCollection(limit: 10) {\n        items {\n          user {\n            sys {\n              id\n            }\n          }\n          role\n          linkedFrom {\n            projectsCollection(limit: 1) {\n              items {\n                sys {\n                  id\n                }\n                title\n                status\n                membersCollection(limit: 25) {\n                  items {\n                    role\n                    user {\n                      sys {\n                        id\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      workingGroupMembershipCollection(limit: 10) {\n        items {\n          user {\n            sys {\n              id\n            }\n          }\n          role\n          linkedFrom {\n            workingGroupsCollection(limit: 1) {\n              items {\n                sys {\n                  id\n                }\n                title\n                membersCollection(limit: 25) {\n                  items {\n                    role\n                    user {\n                      sys {\n                        id\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n':
    graphql.UsersContentDataFragmentDoc,
  '\n  query FetchUserById($id: String!) {\n    users(id: $id) {\n      ...UsersContentData\n    }\n  }\n  \n':
    graphql.FetchUserByIdDocument,
  '\n  query FetchUsers(\n    $limit: Int\n    $skip: Int\n    $order: [UsersOrder]\n    $where: UsersFilter\n  ) {\n    usersCollection(limit: $limit, skip: $skip, order: $order, where: $where) {\n      total\n      items {\n        ...UsersContentData\n      }\n    }\n  }\n  \n':
    graphql.FetchUsersDocument,
  '\n  query FetchUsersByProjectId($id: [String]!, $limit: Int, $skip: Int) {\n    projectsCollection(\n      limit: $limit\n      skip: $skip\n      where: { sys: { id_in: $id } }\n    ) {\n      total\n      items {\n        sys {\n          id\n        }\n        membersCollection {\n          total\n          items {\n            user {\n              sys {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n':
    graphql.FetchUsersByProjectIdDocument,
  '\n  query FetchUsersByWorkingGroupId($id: [String]!, $limit: Int, $skip: Int) {\n    workingGroupsCollection(\n      limit: $limit\n      skip: $skip\n      where: { sys: { id_in: $id } }\n    ) {\n      total\n      items {\n        sys {\n          id\n        }\n        membersCollection {\n          total\n          items {\n            user {\n              sys {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n':
    graphql.FetchUsersByWorkingGroupIdDocument,
  '\n  fragment WorkingGroupNetworkContentData on WorkingGroupNetwork {\n    supportCollection(limit: 10) {\n      total\n      items {\n        ...WorkingGroupsContentData\n      }\n    }\n    monogenicCollection(limit: 10) {\n      total\n      items {\n        ...WorkingGroupsContentData\n      }\n    }\n    operationalCollection(limit: 10) {\n      total\n      items {\n        ...WorkingGroupsContentData\n      }\n    }\n    complexDiseaseCollection(limit: 10) {\n      total\n      items {\n        ...WorkingGroupsContentData\n      }\n    }\n  }\n  \n':
    graphql.WorkingGroupNetworkContentDataFragmentDoc,
  '\n  query FetchWorkingGroupNetwork {\n    workingGroupNetworkCollection(limit: 1) {\n      total\n      items {\n        ...WorkingGroupNetworkContentData\n      }\n    }\n  }\n  \n':
    graphql.FetchWorkingGroupNetworkDocument,
  '\n  fragment WorkingGroupsContentData on WorkingGroups {\n    sys {\n      id\n    }\n    title\n    shortDescription\n    description\n    primaryEmail\n    secondaryEmail\n    leadingMembers\n    membersCollection(limit: 50) {\n      total\n      items {\n        sys {\n          id\n        }\n        role\n        user {\n          sys {\n            id\n          }\n          firstName\n          lastName\n          onboarded\n          avatar {\n            url\n          }\n        }\n      }\n    }\n    milestonesCollection(limit: 10) {\n      total\n      items {\n        sys {\n          id\n        }\n        description\n        externalLink\n        status\n        title\n      }\n    }\n    resourcesCollection(limit: 10) {\n      total\n      items {\n        sys {\n          id\n        }\n        type\n        title\n        description\n        externalLink\n      }\n    }\n    calendar {\n      sys {\n        id\n      }\n      name\n    }\n  }\n':
    graphql.WorkingGroupsContentDataFragmentDoc,
  '\n  query FetchWorkingGroupById($id: String!) {\n    workingGroups(id: $id) {\n      ...WorkingGroupsContentData\n    }\n  }\n  \n':
    graphql.FetchWorkingGroupByIdDocument,
};

export function gql(
  source: '\n  fragment CalendarsContentData on Calendars {\n    sys {\n      id\n      firstPublishedAt\n      publishedAt\n      publishedVersion\n    }\n    googleCalendarId\n    name\n    color\n    syncToken\n    resourceId\n    expirationDate\n  }\n',
): (typeof documents)['\n  fragment CalendarsContentData on Calendars {\n    sys {\n      id\n      firstPublishedAt\n      publishedAt\n      publishedVersion\n    }\n    googleCalendarId\n    name\n    color\n    syncToken\n    resourceId\n    expirationDate\n  }\n'];
export function gql(
  source: '\n  query FetchCalendarById($id: String!) {\n    calendars(id: $id) {\n      ...CalendarsContentData\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchCalendarById($id: String!) {\n    calendars(id: $id) {\n      ...CalendarsContentData\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchCalendars(\n    $limit: Int\n    $skip: Int\n    $order: [CalendarsOrder]\n    $where: CalendarsFilter\n  ) {\n    calendarsCollection(\n      limit: $limit\n      skip: $skip\n      order: $order\n      where: $where\n    ) {\n      total\n      items {\n        ...CalendarsContentData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchCalendars(\n    $limit: Int\n    $skip: Int\n    $order: [CalendarsOrder]\n    $where: CalendarsFilter\n  ) {\n    calendarsCollection(\n      limit: $limit\n      skip: $skip\n      order: $order\n      where: $where\n    ) {\n      total\n      items {\n        ...CalendarsContentData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment ContributingCohortsContentData on ContributingCohorts {\n    sys {\n      id\n    }\n    name\n  }\n',
): (typeof documents)['\n  fragment ContributingCohortsContentData on ContributingCohorts {\n    sys {\n      id\n    }\n    name\n  }\n'];
export function gql(
  source: '\n  query FetchContributingCohorts(\n    $limit: Int\n    $skip: Int\n    $order: [ContributingCohortsOrder]\n  ) {\n    contributingCohortsCollection(limit: $limit, skip: $skip, order: $order) {\n      total\n      items {\n        ...ContributingCohortsContentData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchContributingCohorts(\n    $limit: Int\n    $skip: Int\n    $order: [ContributingCohortsOrder]\n  ) {\n    contributingCohortsCollection(limit: $limit, skip: $skip, order: $order) {\n      total\n      items {\n        ...ContributingCohortsContentData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment EventsContent on Events {\n    sys {\n      id\n      publishedAt\n      publishedVersion\n    }\n    description\n    endDate\n    endDateTimeZone\n    startDate\n    startDateTimeZone\n    meetingLink\n    hideMeetingLink\n    eventLink\n    status\n    hidden\n    tags\n    title\n    notesPermanentlyUnavailable\n    notes {\n      json\n      links {\n        entries {\n          inline {\n            sys {\n              id\n            }\n            __typename\n            ... on Media {\n              url\n            }\n          }\n        }\n        assets {\n          block {\n            sys {\n              id\n            }\n            url\n            description\n            contentType\n            width\n            height\n          }\n        }\n      }\n    }\n    notesUpdatedAt\n    videoRecordingPermanentlyUnavailable\n    videoRecording {\n      json\n      links {\n        entries {\n          inline {\n            sys {\n              id\n            }\n            __typename\n            ... on Media {\n              url\n            }\n          }\n        }\n        assets {\n          block {\n            sys {\n              id\n            }\n            url\n            description\n            contentType\n            width\n            height\n          }\n        }\n      }\n    }\n    videoRecordingUpdatedAt\n    presentationPermanentlyUnavailable\n    presentation {\n      json\n      links {\n        entries {\n          inline {\n            sys {\n              id\n            }\n            __typename\n            ... on Media {\n              url\n            }\n          }\n        }\n        assets {\n          block {\n            sys {\n              id\n            }\n            url\n            description\n            contentType\n            width\n            height\n          }\n        }\n      }\n    }\n    presentationUpdatedAt\n    meetingMaterialsPermanentlyUnavailable\n    meetingMaterials\n    calendar {\n      googleCalendarId\n      color\n      name\n    }\n    thumbnail {\n      url\n    }\n    speakersCollection(limit: 10) {\n      items {\n        title\n        user {\n          __typename\n          ... on ExternalUsers {\n            sys {\n              id\n            }\n            name\n            orcid\n          }\n          ... on Users {\n            sys {\n              id\n            }\n            firstName\n            lastName\n            onboarded\n            avatar {\n              url\n            }\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  fragment EventsContent on Events {\n    sys {\n      id\n      publishedAt\n      publishedVersion\n    }\n    description\n    endDate\n    endDateTimeZone\n    startDate\n    startDateTimeZone\n    meetingLink\n    hideMeetingLink\n    eventLink\n    status\n    hidden\n    tags\n    title\n    notesPermanentlyUnavailable\n    notes {\n      json\n      links {\n        entries {\n          inline {\n            sys {\n              id\n            }\n            __typename\n            ... on Media {\n              url\n            }\n          }\n        }\n        assets {\n          block {\n            sys {\n              id\n            }\n            url\n            description\n            contentType\n            width\n            height\n          }\n        }\n      }\n    }\n    notesUpdatedAt\n    videoRecordingPermanentlyUnavailable\n    videoRecording {\n      json\n      links {\n        entries {\n          inline {\n            sys {\n              id\n            }\n            __typename\n            ... on Media {\n              url\n            }\n          }\n        }\n        assets {\n          block {\n            sys {\n              id\n            }\n            url\n            description\n            contentType\n            width\n            height\n          }\n        }\n      }\n    }\n    videoRecordingUpdatedAt\n    presentationPermanentlyUnavailable\n    presentation {\n      json\n      links {\n        entries {\n          inline {\n            sys {\n              id\n            }\n            __typename\n            ... on Media {\n              url\n            }\n          }\n        }\n        assets {\n          block {\n            sys {\n              id\n            }\n            url\n            description\n            contentType\n            width\n            height\n          }\n        }\n      }\n    }\n    presentationUpdatedAt\n    meetingMaterialsPermanentlyUnavailable\n    meetingMaterials\n    calendar {\n      googleCalendarId\n      color\n      name\n    }\n    thumbnail {\n      url\n    }\n    speakersCollection(limit: 10) {\n      items {\n        title\n        user {\n          __typename\n          ... on ExternalUsers {\n            sys {\n              id\n            }\n            name\n            orcid\n          }\n          ... on Users {\n            sys {\n              id\n            }\n            firstName\n            lastName\n            onboarded\n            avatar {\n              url\n            }\n          }\n        }\n      }\n    }\n  }\n'];
export function gql(
  source: '\n  query FetchEventById($id: String!) {\n    events(id: $id) {\n      ...EventsContent\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchEventById($id: String!) {\n    events(id: $id) {\n      ...EventsContent\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchEvents(\n    $limit: Int\n    $skip: Int\n    $order: [EventsOrder]\n    $where: EventsFilter\n  ) {\n    eventsCollection(limit: $limit, skip: $skip, order: $order, where: $where) {\n      total\n      items {\n        ...EventsContent\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchEvents(\n    $limit: Int\n    $skip: Int\n    $order: [EventsOrder]\n    $where: EventsFilter\n  ) {\n    eventsCollection(limit: $limit, skip: $skip, order: $order, where: $where) {\n      total\n      items {\n        ...EventsContent\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchEventsByUserId($id: String!, $limit: Int, $skip: Int) {\n    users(id: $id) {\n      linkedFrom {\n        eventSpeakersCollection(limit: 1) {\n          items {\n            linkedFrom {\n              eventsCollection(limit: $limit, skip: $skip) {\n                total\n                items {\n                  ...EventsContent\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchEventsByUserId($id: String!, $limit: Int, $skip: Int) {\n    users(id: $id) {\n      linkedFrom {\n        eventSpeakersCollection(limit: 1) {\n          items {\n            linkedFrom {\n              eventsCollection(limit: $limit, skip: $skip) {\n                total\n                items {\n                  ...EventsContent\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchEventsByExternalUserId($id: String!, $limit: Int, $skip: Int) {\n    externalUsers(id: $id) {\n      linkedFrom {\n        eventSpeakersCollection(limit: 1) {\n          items {\n            linkedFrom {\n              eventsCollection(limit: $limit, skip: $skip) {\n                total\n                items {\n                  ...EventsContent\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchEventsByExternalUserId($id: String!, $limit: Int, $skip: Int) {\n    externalUsers(id: $id) {\n      linkedFrom {\n        eventSpeakersCollection(limit: 1) {\n          items {\n            linkedFrom {\n              eventsCollection(limit: $limit, skip: $skip) {\n                total\n                items {\n                  ...EventsContent\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment ExternalUsersContentData on ExternalUsers {\n    sys {\n      id\n      firstPublishedAt\n      publishedAt\n      publishedVersion\n    }\n    name\n    orcid\n  }\n',
): (typeof documents)['\n  fragment ExternalUsersContentData on ExternalUsers {\n    sys {\n      id\n      firstPublishedAt\n      publishedAt\n      publishedVersion\n    }\n    name\n    orcid\n  }\n'];
export function gql(
  source: '\n  query FetchExternalUsers(\n    $limit: Int\n    $skip: Int\n    $order: [ExternalUsersOrder]\n    $where: ExternalUsersFilter\n  ) {\n    externalUsersCollection(\n      limit: $limit\n      skip: $skip\n      order: $order\n      where: $where\n    ) {\n      total\n      items {\n        ...ExternalUsersContentData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchExternalUsers(\n    $limit: Int\n    $skip: Int\n    $order: [ExternalUsersOrder]\n    $where: ExternalUsersFilter\n  ) {\n    externalUsersCollection(\n      limit: $limit\n      skip: $skip\n      order: $order\n      where: $where\n    ) {\n      total\n      items {\n        ...ExternalUsersContentData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment NewsContentData on News {\n    sys {\n      id\n      firstPublishedAt\n    }\n    title\n    shortText\n    sampleCount\n    articleCount\n    cohortCount\n    link\n    linkText\n    publishDate\n  }\n',
): (typeof documents)['\n  fragment NewsContentData on News {\n    sys {\n      id\n      firstPublishedAt\n    }\n    title\n    shortText\n    sampleCount\n    articleCount\n    cohortCount\n    link\n    linkText\n    publishDate\n  }\n'];
export function gql(
  source: '\n  query FetchNewsById($id: String!) {\n    news(id: $id) {\n      ...NewsContentData\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchNewsById($id: String!) {\n    news(id: $id) {\n      ...NewsContentData\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchNews(\n    $limit: Int\n    $skip: Int\n    $order: [NewsOrder]\n    $where: NewsFilter\n  ) {\n    newsCollection(limit: $limit, skip: $skip, order: $order, where: $where) {\n      total\n      items {\n        ...NewsContentData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchNews(\n    $limit: Int\n    $skip: Int\n    $order: [NewsOrder]\n    $where: NewsFilter\n  ) {\n    newsCollection(limit: $limit, skip: $skip, order: $order, where: $where) {\n      total\n      items {\n        ...NewsContentData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment PageContentData on Pages {\n    sys {\n      id\n    }\n    title\n    path\n    shortText\n    text {\n      json\n      links {\n        entries {\n          inline {\n            sys {\n              id\n            }\n            __typename\n            ... on Media {\n              url\n            }\n          }\n        }\n        assets {\n          block {\n            sys {\n              id\n            }\n            url\n            description\n            contentType\n            width\n            height\n          }\n        }\n      }\n    }\n    link\n    linkText\n  }\n',
): (typeof documents)['\n  fragment PageContentData on Pages {\n    sys {\n      id\n    }\n    title\n    path\n    shortText\n    text {\n      json\n      links {\n        entries {\n          inline {\n            sys {\n              id\n            }\n            __typename\n            ... on Media {\n              url\n            }\n          }\n        }\n        assets {\n          block {\n            sys {\n              id\n            }\n            url\n            description\n            contentType\n            width\n            height\n          }\n        }\n      }\n    }\n    link\n    linkText\n  }\n'];
export function gql(
  source: '\n  query FetchPages($where: PagesFilter) {\n    pagesCollection(limit: 100, where: $where) {\n      total\n      items {\n        ...PageContentData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchPages($where: PagesFilter) {\n    pagesCollection(limit: 100, where: $where) {\n      total\n      items {\n        ...PageContentData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment UsersContentData on Users {\n    sys {\n      id\n      firstPublishedAt\n      publishedAt\n      publishedVersion\n    }\n    activatedDate\n    firstName\n    lastName\n    avatar {\n      url\n    }\n    degrees\n    country\n    city\n    region\n    email\n    alternativeEmail\n    telephoneCountryCode\n    telephoneNumber\n    keywords\n    biography\n    questions\n    fundingStreams\n    blog\n    linkedIn\n    twitter\n    github\n    googleScholar\n    orcid\n    researchGate\n    researcherId\n    connections\n    role\n    onboarded\n    positions\n    activatedDate\n    contributingCohortsCollection(limit: 100) {\n      items {\n        contributingCohort {\n          sys {\n            id\n          }\n          name\n        }\n        role\n        studyLink\n      }\n    }\n    linkedFrom {\n      projectMembershipCollection(limit: 10) {\n        items {\n          user {\n            sys {\n              id\n            }\n          }\n          role\n          linkedFrom {\n            projectsCollection(limit: 1) {\n              items {\n                sys {\n                  id\n                }\n                title\n                status\n                membersCollection(limit: 25) {\n                  items {\n                    role\n                    user {\n                      sys {\n                        id\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      workingGroupMembershipCollection(limit: 10) {\n        items {\n          user {\n            sys {\n              id\n            }\n          }\n          role\n          linkedFrom {\n            workingGroupsCollection(limit: 1) {\n              items {\n                sys {\n                  id\n                }\n                title\n                membersCollection(limit: 25) {\n                  items {\n                    role\n                    user {\n                      sys {\n                        id\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  fragment UsersContentData on Users {\n    sys {\n      id\n      firstPublishedAt\n      publishedAt\n      publishedVersion\n    }\n    activatedDate\n    firstName\n    lastName\n    avatar {\n      url\n    }\n    degrees\n    country\n    city\n    region\n    email\n    alternativeEmail\n    telephoneCountryCode\n    telephoneNumber\n    keywords\n    biography\n    questions\n    fundingStreams\n    blog\n    linkedIn\n    twitter\n    github\n    googleScholar\n    orcid\n    researchGate\n    researcherId\n    connections\n    role\n    onboarded\n    positions\n    activatedDate\n    contributingCohortsCollection(limit: 100) {\n      items {\n        contributingCohort {\n          sys {\n            id\n          }\n          name\n        }\n        role\n        studyLink\n      }\n    }\n    linkedFrom {\n      projectMembershipCollection(limit: 10) {\n        items {\n          user {\n            sys {\n              id\n            }\n          }\n          role\n          linkedFrom {\n            projectsCollection(limit: 1) {\n              items {\n                sys {\n                  id\n                }\n                title\n                status\n                membersCollection(limit: 25) {\n                  items {\n                    role\n                    user {\n                      sys {\n                        id\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      workingGroupMembershipCollection(limit: 10) {\n        items {\n          user {\n            sys {\n              id\n            }\n          }\n          role\n          linkedFrom {\n            workingGroupsCollection(limit: 1) {\n              items {\n                sys {\n                  id\n                }\n                title\n                membersCollection(limit: 25) {\n                  items {\n                    role\n                    user {\n                      sys {\n                        id\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n'];
export function gql(
  source: '\n  query FetchUserById($id: String!) {\n    users(id: $id) {\n      ...UsersContentData\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchUserById($id: String!) {\n    users(id: $id) {\n      ...UsersContentData\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchUsers(\n    $limit: Int\n    $skip: Int\n    $order: [UsersOrder]\n    $where: UsersFilter\n  ) {\n    usersCollection(limit: $limit, skip: $skip, order: $order, where: $where) {\n      total\n      items {\n        ...UsersContentData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchUsers(\n    $limit: Int\n    $skip: Int\n    $order: [UsersOrder]\n    $where: UsersFilter\n  ) {\n    usersCollection(limit: $limit, skip: $skip, order: $order, where: $where) {\n      total\n      items {\n        ...UsersContentData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchUsersByProjectId($id: [String]!, $limit: Int, $skip: Int) {\n    projectsCollection(\n      limit: $limit\n      skip: $skip\n      where: { sys: { id_in: $id } }\n    ) {\n      total\n      items {\n        sys {\n          id\n        }\n        membersCollection {\n          total\n          items {\n            user {\n              sys {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  query FetchUsersByProjectId($id: [String]!, $limit: Int, $skip: Int) {\n    projectsCollection(\n      limit: $limit\n      skip: $skip\n      where: { sys: { id_in: $id } }\n    ) {\n      total\n      items {\n        sys {\n          id\n        }\n        membersCollection {\n          total\n          items {\n            user {\n              sys {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n'];
export function gql(
  source: '\n  query FetchUsersByWorkingGroupId($id: [String]!, $limit: Int, $skip: Int) {\n    workingGroupsCollection(\n      limit: $limit\n      skip: $skip\n      where: { sys: { id_in: $id } }\n    ) {\n      total\n      items {\n        sys {\n          id\n        }\n        membersCollection {\n          total\n          items {\n            user {\n              sys {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  query FetchUsersByWorkingGroupId($id: [String]!, $limit: Int, $skip: Int) {\n    workingGroupsCollection(\n      limit: $limit\n      skip: $skip\n      where: { sys: { id_in: $id } }\n    ) {\n      total\n      items {\n        sys {\n          id\n        }\n        membersCollection {\n          total\n          items {\n            user {\n              sys {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n'];
export function gql(
  source: '\n  fragment WorkingGroupNetworkContentData on WorkingGroupNetwork {\n    supportCollection(limit: 10) {\n      total\n      items {\n        ...WorkingGroupsContentData\n      }\n    }\n    monogenicCollection(limit: 10) {\n      total\n      items {\n        ...WorkingGroupsContentData\n      }\n    }\n    operationalCollection(limit: 10) {\n      total\n      items {\n        ...WorkingGroupsContentData\n      }\n    }\n    complexDiseaseCollection(limit: 10) {\n      total\n      items {\n        ...WorkingGroupsContentData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  fragment WorkingGroupNetworkContentData on WorkingGroupNetwork {\n    supportCollection(limit: 10) {\n      total\n      items {\n        ...WorkingGroupsContentData\n      }\n    }\n    monogenicCollection(limit: 10) {\n      total\n      items {\n        ...WorkingGroupsContentData\n      }\n    }\n    operationalCollection(limit: 10) {\n      total\n      items {\n        ...WorkingGroupsContentData\n      }\n    }\n    complexDiseaseCollection(limit: 10) {\n      total\n      items {\n        ...WorkingGroupsContentData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchWorkingGroupNetwork {\n    workingGroupNetworkCollection(limit: 1) {\n      total\n      items {\n        ...WorkingGroupNetworkContentData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchWorkingGroupNetwork {\n    workingGroupNetworkCollection(limit: 1) {\n      total\n      items {\n        ...WorkingGroupNetworkContentData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment WorkingGroupsContentData on WorkingGroups {\n    sys {\n      id\n    }\n    title\n    shortDescription\n    description\n    primaryEmail\n    secondaryEmail\n    leadingMembers\n    membersCollection(limit: 50) {\n      total\n      items {\n        sys {\n          id\n        }\n        role\n        user {\n          sys {\n            id\n          }\n          firstName\n          lastName\n          onboarded\n          avatar {\n            url\n          }\n        }\n      }\n    }\n    milestonesCollection(limit: 10) {\n      total\n      items {\n        sys {\n          id\n        }\n        description\n        externalLink\n        status\n        title\n      }\n    }\n    resourcesCollection(limit: 10) {\n      total\n      items {\n        sys {\n          id\n        }\n        type\n        title\n        description\n        externalLink\n      }\n    }\n    calendar {\n      sys {\n        id\n      }\n      name\n    }\n  }\n',
): (typeof documents)['\n  fragment WorkingGroupsContentData on WorkingGroups {\n    sys {\n      id\n    }\n    title\n    shortDescription\n    description\n    primaryEmail\n    secondaryEmail\n    leadingMembers\n    membersCollection(limit: 50) {\n      total\n      items {\n        sys {\n          id\n        }\n        role\n        user {\n          sys {\n            id\n          }\n          firstName\n          lastName\n          onboarded\n          avatar {\n            url\n          }\n        }\n      }\n    }\n    milestonesCollection(limit: 10) {\n      total\n      items {\n        sys {\n          id\n        }\n        description\n        externalLink\n        status\n        title\n      }\n    }\n    resourcesCollection(limit: 10) {\n      total\n      items {\n        sys {\n          id\n        }\n        type\n        title\n        description\n        externalLink\n      }\n    }\n    calendar {\n      sys {\n        id\n      }\n      name\n    }\n  }\n'];
export function gql(
  source: '\n  query FetchWorkingGroupById($id: String!) {\n    workingGroups(id: $id) {\n      ...WorkingGroupsContentData\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchWorkingGroupById($id: String!) {\n    workingGroups(id: $id) {\n      ...WorkingGroupsContentData\n    }\n  }\n  \n'];

export function gql(source: string): unknown;
export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
