version: '2.1'
services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: unless-stopped

  squidex:
    image: 'squidex/squidex:latest'
    ports:
      - '${SQUIDEX_PORT:-4004}:80'
    environment:
      - URLS__BASEURL=${SQUIDEX_URL:-http://localhost:4004}
      - EVENTSTORE__MONGODB__CONFIGURATION=mongodb://mongo
      - STORE__MONGODB__CONFIGURATION=mongodb://mongo
      - IDENTITY__ADMINEMAIL=${SQUIDEX_ADMINEMAIL:-admin@squidex.io}
      - IDENTITY__ADMINPASSWORD=${SQUIDEX_ADMINPASSWORD:-SuperS3cure?}
    depends_on:
      - mongo
    restart: unless-stopped

  setup_squidex:
    build:
      dockerfile: dev/local-setup.Dockerfile
      context: ..
    depends_on:
      - mongo
      - squidex
