name: 'Slack notification'
description: 'Notifies of success or failure via Slack'
inputs:
  message:
    description: 'Slack notification message'
    default: 'Custom workflow'
  webhook:
    description: 'Slack webhook'
    required: true
  status:
    description: 'Status'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ inputs.webhook }}
        SLACK_MESSAGE: ${{ inputs.message }}
        SLACK_ICON: https://asap-misc.s3.eu-west-1.amazonaws.com/robot.png
        SLACK_USERNAME: ASAP robot
        SLACK_COLOR: ${{ (inputs.status == 'success' && '#35a64f') || (inputs.status == 'failure' && '#FF0000') || '#E3256B' }}
