name: 'Setup Environment'
description: 'Generates the environment variables for the workflow'
inputs:
  environment-name:
    description: 'Current environment'
    required: true
outputs:
  algolia-app-name:
    description: 'Algolia App Name'
    value: ${{ steps.vars.outputs.algolia-app-name }}
  algolia-index:
    description: 'Algolia Index'
    value: ${{ steps.vars.outputs.algolia-index }}
  api-hostname:
    description: 'API Hostname'
    value: ${{ steps.vars.outputs.api-hostname }}
  app-hostname:
    description: 'App Hostname'
    value: ${{ steps.vars.outputs.app-hostname }}
  app-release:
    description: 'App Release'
    value: ${{ steps.vars.outputs.app-release }}
  asap-api-url:
    description: 'ASAP API Url'
    value: ${{ steps.vars.outputs.asap-api-url }}
  asap-app-url:
    description: 'ASAP APP Url'
    value: ${{ steps.vars.outputs.asap-app-url }}
  asap-host-name:
    description: 'ASAP Host Name'
    value: ${{ steps.vars.outputs.asap-host-name }}
  auth0-client-id:
    description: 'Auth0 Client ID'
    value: ${{ steps.vars.outputs.auth0-client-id }}
  auth0-domain:
    description: 'Auth0 Domain'
    value: ${{ steps.vars.outputs.auth0-domain }}
  aws-acm-asap-science-certificate-arn:
    description: 'AWS ACM ASAP Science Certificate ARN'
    value: arn:aws:acm:us-east-1:249832953260:certificate/91e951dd-8819-4459-b69a-b9413760c4d6
  aws-acm-certificate-arn:
    description: 'AWS ACM Certificate ARN'
    value: arn:aws:acm:us-east-1:249832953260:certificate/91e951dd-8819-4459-b69a-b9413760c4d6
  aws-default-region:
    description: 'AWS Default Region'
    value: us-east-1
  aws-region:
    description: 'AWS Region'
    value: us-east-1
  bucket-name:
    description: 'Bucket Name'
    value: ${{ steps.vars.outputs.bucket-name }}
  ecr-project:
    description: 'ECR Project'
    value: asap-hub
  ecr-registry:
    description: 'ECR Registry'
    value: 249832953260.dkr.ecr.ap-southeast-2.amazonaws.com
  pr-number:
    description: 'PR Number'
    value: ${{ steps.vars.outputs.pr-number }}
  print-sync-logs-on-success:
    description: 'Print sync logs on success'
    value: 'TRUE'
  react-app-environment:
    description: 'React App Environment'
    value: ${{ steps.vars.outputs.react-app-environment }}
  react-app-gtm-container-id:
    description: 'React App GTM Container ID'
    value: ${{ steps.vars.outputs.react-app-gtm-container-id }}
  react-app-sentry-dsn:
    description: 'React App Sentry DSN'
    value: ${{ steps.vars.outputs.react-app-sentry-dsn }}
  sentry-dsn-api:
    description: 'Sentry DSN API'
    value: https://c61a36e015ef481bb29e0bd2a9f84aa3@o850903.ingest.sentry.io/5817859
  sentry-dsn-calendar:
    description: 'Sentry DSN Calendar'
    value: https://ec081bcc80474f9fab7e36c6e0a22da6@o850903.ingest.sentry.io/5823490
  sentry-dsn-user-invite:
    description: 'Sentry DSN User Invite'
    value: https://1f86813cefa5461183129f9143b4f78a@o850903.ingest.sentry.io/5997162
  ses-region:
    description: 'SES Region'
    value: ${{ steps.vars.outputs.ses-region }}
  sls-stage:
    description: 'SLS Stage'
    value: ${{ steps.vars.outputs.sls-stage }}
  squidex-app-name:
    description: 'Squidex App Name'
    value: ${{ steps.vars.outputs.squidex-app-name }}
  squidex-base-url:
    description: 'Squidex Base Url'
    value: https://cloud.squidex.io
  squidex-client-id:
    description: 'Squidex Client ID'
    value: ${{ steps.vars.outputs.squidex-client-id }}
runs:
  using: 'composite'
  steps:
    - name: Setup
      id: vars
      shell: bash
      run: |
        ASAP_HOSTNAME="hub.asap.science"
        echo "::set-output name=asap-host-name::$ASAP_HOSTNAME"

        if [ "$ENVIRONMENT_NAME" = "Branch" ]; then
          echo "Setting up branch environment"
          PR_NUMBER=${{ github.event.number || github.event.inputs.prNumber }}
          echo "::set-output name=pr-number::$PR_NUMBER"
          echo "::set-output name=algolia-app-name::algolia-app-id-dev"
          echo "::set-output name=algolia-index::asap-hub_CI-$PR_NUMBER"
          echo "::set-output name=app-release::'${{ github.run_id }}-dev'"
          echo "::set-output name=asap-api-url::https://api-$PR_NUMBER.$ASAP_HOSTNAME"
          echo "::set-output name=asap-app-url::https://$PR_NUMBER.$ASAP_HOSTNAME"
          echo "::set-output name=auth0-client-id::xRDvgZe3Ql3LSZDs2dWQYzcohFnLyeL2"
          echo "::set-output name=auth0-domain::dev-asap-hub.us.auth0.com"
          echo "::set-output name=bucket-name::asap-hub-dev-algolia-backup"
          echo "::set-output name=react-app-environment::development"
          echo "::set-output name=sls-stage::$PR_NUMBER"
          echo "::set-output name=squidex-app-name::$PR_NUMBER"
          echo "::set-output name=squidex-client-id::6058c1ce6d296b4d1681c3ad"
        elif [ "$ENVIRONMENT_NAME" = 'Development' ]; then
          echo "Setting up development environment"
          echo "::set-output name=algolia-app-name::algolia-app-id-dev"
          echo "::set-output name=algolia-index::"
          echo "::set-output name=api-hostname::dev-api.$ASAP_HOSTNAME"
          echo "::set-output name=app-hostname::dev.$ASAP_HOSTNAME"
          echo "::set-output name=app-release::'${{ github.run_id }}-dev'"
          echo "::set-output name=asap-api-url::https://api-dev.$ASAP_HOSTNAME"
          echo "::set-output name=asap-app-url::https://dev.$ASAP_HOSTNAME"
          echo "::set-output name=auth0-client-id::xRDvgZe3Ql3LSZDs2dWQYzcohFnLyeL2"
          echo "::set-output name=auth0-domain::dev-asap-hub.us.auth0.com"
          echo "::set-output name=react-app-environment::development"
          echo "::set-output name=react-app-sentry-dsn::https://8cd3c59be8ec4118aa6f6c59487b9e56@o850903.ingest.sentry.io/5893160"
          echo "::set-output name=ses-region::eu-west-1"
          echo "::set-output name=sls-stage::dev"
          echo "::set-output name=squidex-app-name::asap-hub-dev"
          echo "::set-output name=squidex-app-name::asap-hub-dev:default"
        elif [ "$ENVIRONMENT_NAME" = 'Production' ]; then
          echo "Setting up production environment"
          echo "::set-output name=algolia-app-name::"
          echo "::set-output name=algolia-index::"
          echo "::set-output name=api-hostname::api.$ASAP_HOSTNAME"
          echo "::set-output name=app-hostname::$ASAP_HOSTNAME"
          echo "::set-output name=app-release::'${{ github.run_id }}-prod'"
          echo "::set-output name=asap-api-url::https://api.$ASAP_HOSTNAME"
          echo "::set-output name=asap-app-url::https://$ASAP_HOSTNAME"
          echo "::set-output name=auth0-client-id::Av2psgVspAN00Kez9v1vR2c496a9zCW3"
          echo "::set-output name=auth0-domain::asap-hub.us.auth0.com"
          echo "::set-output name=react-app-environment::production"
          echo "::set-output name=react-app-gtm-container-id::GTM-M5HZBRZ"
          echo "::set-output name=react-app-sentry-dsn::https://8cd3c59be8ec4118aa6f6c59487b9e56@o850903.ingest.sentry.io/5893160"
          echo "::set-output name=ses-region::eu-east-1"
          echo "::set-output name=sls-stage::production"
          echo "::set-output name=squidex-app-name::asap-hub"
          echo "::set-output name=squidex-app-name::asap-hub:default"
        else
          echo "Unknown environment: $ENVIRONMENT_NAME"
          exit 1
        fi
      env:
        ENVIRONMENT_NAME: ${{ inputs.environment-name }}
