name: 'Setup Environment'
description: 'Generates the environment variables for the workflow'
inputs:
  environment-name:
    description: 'Current environment'
    required: true
  pr-number:
    description: 'The PR number'
    required: true
  crn-create-env:
    description: 'Setup a dedicated CRN environment'
    required: false
  gp2-create-env:
    description: 'Setup a dedicated GP2 environment'
    required: false
outputs:
  app-release:
    description: 'App Release'
    value: ${{ steps.vars.outputs.app-release }}
  auth0-label:
    description: 'PR has auth0 label'
    value: ${{ steps.vars.outputs.auth0-label }}
  aws-acm-asap-science-certificate-arn:
    description: 'AWS ACM ASAP Science Certificate ARN'
    value: ${{ steps.vars.outputs.aws-acm-asap-science-certificate-arn }}
  aws-default-region:
    description: 'AWS Default Region'
    value: ${{ steps.vars.outputs.aws-default-region }}
  aws-region:
    description: 'AWS Region'
    value: ${{ steps.vars.outputs.aws-region }}
  cache-prefix-definitions:
    description: 'Cache Prefix Definitions'
    value: ${{ steps.vars.outputs.cache-prefix-definitions }}
  cache-prefix-frontend:
    description: 'Cache Prefix Frontend'
    value: ${{ steps.vars.outputs.cache-prefix-frontend }}
  cache-prefix-transpile:
    description: 'Cache Prefix Transpile'
    value: ${{ steps.vars.outputs.cache-prefix-transpile }}
  contentful-app-date-field-as-first-published-at:
    description: 'Contentful App Extension Date Field as firstPublishedAt'
    value: ${{ steps.vars.outputs.contentful-app-date-field-as-first-published-at }}
  contentful-app-disabled-fields:
    description: 'Contentful App Extension Disabled Fields Id'
    value: ${{ steps.vars.outputs.contentful-app-disabled-fields }}
  contentful-app-clear-on-change:
    description: 'Contentful App Extension Clear Field On Change'
    value: ${{ steps.vars.outputs.contentful-app-clear-on-change }}
  contentful-app-event-additional-materials:
    description: 'Contentful App Extension Event Additional Materials Id'
    value: ${{ steps.vars.outputs.contentful-app-event-additional-materials }}
  contentful-app-event-custom-validation:
    description: 'Contentful App Extension Event Custom Validation'
    value: ${{ steps.vars.outputs.contentful-app-event-custom-validation }}
  contentful-app-event-speakers-title:
    description: 'Contentful App Extension Event Speakers Title Id'
    value: ${{ steps.vars.outputs.contentful-app-event-speakers-title }}
  contentful-app-event-speakers-gp2:
    description: 'Contentful App Extension Event Speakers Topic and User'
    value: ${{ steps.vars.outputs.contentful-app-event-speakers-gp2 }}
  contentful-app-field-as-updated-at:
    description: 'Contentful App Extension Field As Updated At Id'
    value: ${{ steps.vars.outputs.contentful-app-field-as-updated-at }}
  contentful-app-user-positions:
    description: 'Contentful App Extension User Positions Id'
    value: ${{ steps.vars.outputs.contentful-app-user-positions }}
  contentful-app-working-group-deliverables:
    description: 'Contentful App Extension Working Group Deliverables'
    value: ${{ steps.vars.outputs.contentful-app-working-group-deliverables }}
  contentful-app-membership-reference:
    description: 'Contentful App Extension Membership Reference'
    value: ${{ steps.vars.outputs.contentful-app-membership-reference }}
  contentful-app-membership-custom-validation:
    description: 'Contentful App Extension Membership Custom Validation'
    value: ${{ steps.vars.outputs.contentful-app-membership-custom-validation }}
  contentful-app-partial-last-updated:
    description: 'Contentful App Extension Partial Last Updated'
    value: ${{ steps.vars.outputs.contentful-app-partial-last-updated }}
  contentful-app-auto-populate-date-field:
    description: 'Contentful App Extension Auto Populate Date Field'
    value: ${{ steps.vars.outputs.contentful-app-auto-populate-date-field }}
  contentful-environment:
    description: 'Contentful Environment'
    value: ${{ steps.vars.outputs.contentful-environment }}
  contentful-organization-id:
    description: 'Contentful Organization Id'
    value: ${{ steps.vars.outputs.contentful-organization-id }}
  crn-algolia-api-key-name:
    description: 'CRN Algolia Api key SSM Name'
    value: ${{ steps.vars.outputs.crn-algolia-api-key-name }}
  crn-algolia-app-id-name:
    description: 'CRN Algolia App id SSM name'
    value: ${{ steps.vars.outputs.crn-algolia-app-id-name }}
  crn-algolia-index:
    description: 'CRN Algolia Index'
    value: ${{ steps.vars.outputs.crn-algolia-index }}
  crn-api-url:
    description: 'CRN API Url'
    value: ${{ steps.vars.outputs.crn-api-url }}
  crn-app-url:
    description: 'CRN APP Url'
    value: ${{ steps.vars.outputs.crn-app-url }}
  crn-auth-url:
    description: 'CRN Auth Url'
    value: ${{ steps.vars.outputs.crn-auth-url }}
  crn-auth0-additional-claim-domain:
    description: 'CRN Auth0 Additional Claim Domain'
    value: ${{ steps.vars.outputs.crn-auth0-additional-claim-domain }}
  crn-auth0-audience:
    description: 'CRN Auth0 Audience'
    value: ${{ steps.vars.outputs.crn-auth0-audience }}
  crn-auth0-client-id:
    description: 'CRN Auth0 Client ID'
    value: ${{ steps.vars.outputs.crn-auth0-client-id }}
  crn-auth0-domain:
    description: 'CRN Auth0 Domain'
    value: ${{ steps.vars.outputs.crn-auth0-domain }}
  crn-aws-acm-certificate-arn:
    description: 'CRN AWS ACM Certificate ARN'
    value: ${{ steps.vars.outputs.crn-aws-acm-certificate-arn }}
  crn-base-pr-app-domain:
    description: 'CRN Base PR App Domain'
    value: ${{ steps.vars.outputs.crn-base-pr-app-domain }}
  crn-ci-auth0-client-id:
    description: 'CRN CI Auth0 Client Id'
    value: ${{ steps.vars.outputs.crn-ci-auth0-client-id }}
  crn-contentful-backup-bucket-name:
    description: 'CRN Contentful Backup Bucket Name'
    value: ${{ steps.vars.outputs.crn-contentful-backup-bucket-name }}
  crn-contentful-env-id:
    description: 'CRN Environment ID for Contentful'
    value: ${{ steps.vars.outputs.crn-contentful-env-id }}
  crn-contentful-space-id:
    description: 'CRN Contentful Space ID'
    value: ${{ steps.vars.outputs.crn-contentful-space-id }}
  crn-max-contentful-envs:
    description: 'Maximum CRN Contentful environments'
    value: ${{ steps.vars.outputs.crn-max-contentful-envs }}
  crn-sentry-dsn-api:
    description: 'CRN Sentry DSN API'
    value: ${{ steps.vars.outputs.crn-sentry-dsn-api }}
  crn-sentry-dsn-handlers:
    description: 'CRN Sentry DSN Handlers'
    value: ${{ steps.vars.outputs.crn-sentry-dsn-handlers }}
  crn-ses-region:
    description: 'CRN SES Region'
    value: ${{ steps.vars.outputs.crn-ses-region }}
  gp2-algolia-api-key-name:
    description: 'GP2 Algolia Api key SSM Name'
    value: ${{ steps.vars.outputs.gp2-algolia-api-key-name }}
  gp2-algolia-app-id-name:
    description: 'GP2 Algolia App id SSM name'
    value: ${{ steps.vars.outputs.gp2-algolia-app-id-name }}
  gp2-algolia-index:
    description: 'GP2 Algolia Index'
    value: ${{ steps.vars.outputs.gp2-algolia-index }}
  gp2-api-url:
    description: 'GP2 API Url'
    value: ${{ steps.vars.outputs.gp2-api-url }}
  gp2-app-url:
    description: 'GP2 APP Url'
    value: ${{ steps.vars.outputs.gp2-app-url }}
  gp2-auth-url:
    description: 'GP2 Auth Url'
    value: ${{ steps.vars.outputs.gp2-auth-url }}
  gp2-auth0-additional-claim-domain:
    description: 'GP2 Auth0 Additional Claim Domain'
    value: ${{ steps.vars.outputs.gp2-auth0-additional-claim-domain }}
  gp2-auth0-audience:
    description: 'GP2 Auth0 Audience'
    value: ${{ steps.vars.outputs.gp2-auth0-audience }}
  gp2-auth0-client-id:
    description: 'GP2 Auth0 Client ID'
    value: ${{ steps.vars.outputs.gp2-auth0-client-id }}
  gp2-auth0-domain:
    description: 'GP2 Auth0 Domain'
    value: ${{ steps.vars.outputs.gp2-auth0-domain }}
  gp2-aws-acm-certificate-arn:
    description: 'GP2 AWS ACM Certificate ARN'
    value: ${{ steps.vars.outputs.gp2-aws-acm-certificate-arn }}
  gp2-base-pr-app-domain:
    description: 'GP2 Base PR App Domain'
    value: ${{ steps.vars.outputs.gp2-base-pr-app-domain }}
  gp2-ci-auth0-client-id:
    description: 'GP2 CI Auth0 Client Id'
    value: ${{ steps.vars.outputs.gp2-ci-auth0-client-id }}
  gp2-contentful-backup-bucket-name:
    description: 'GP2 Contentful Backup Bucket Name'
    value: ${{ steps.vars.outputs.gp2-contentful-backup-bucket-name }}
  gp2-contentful-env-id:
    description: 'GP2 Environment ID for Contentful'
    value: ${{ steps.vars.outputs.gp2-contentful-env-id }}
  gp2-contentful-space-id:
    description: 'GP2 Contentful Space ID'
    value: ${{ steps.vars.outputs.gp2-contentful-space-id }}
  gp2-hostname:
    description: 'GP2 Hostname'
    value: ${{ steps.vars.outputs.gp2-hostname }}
  gp2-max-contentful-envs:
    description: 'Maximum GP2 Contentful environments'
    value: ${{ steps.vars.outputs.gp2-max-contentful-envs }}
  gp2-sentry-dsn-api:
    description: 'GP2 Sentry DSN API'
    value: ${{ steps.vars.outputs.gp2-sentry-dsn-api }}
  gp2-sentry-dsn-handlers:
    description: 'GP2 Sentry DSN Handlers'
    value: ${{ steps.vars.outputs.gp2-sentry-dsn-handlers }}
  gp2-ses-region:
    description: 'GP2 SES Region'
    value: ${{ steps.vars.outputs.gp2-ses-region }}
  pr-number:
    description: 'PR Number'
    value: ${{ steps.vars.outputs.pr-number }}
  print-sync-logs-on-success:
    description: 'Print sync logs on success'
    value: ${{ steps.vars.outputs.print-sync-logs-on-success }}
  react-app-crn-sentry-dsn:
    description: 'React App CRN Sentry DSN'
    value: ${{ steps.vars.outputs.react-app-crn-sentry-dsn }}
  react-app-environment:
    description: 'React App Environment'
    value: ${{ steps.vars.outputs.react-app-environment }}
  react-app-gp2-sentry-dsn:
    description: 'React App GP2 Sentry DSN'
    value: ${{ steps.vars.outputs.react-app-gp2-sentry-dsn }}
  react-app-crn-gtm-container-id:
    description: 'React App CRN GTM Container ID'
    value: ${{ steps.vars.outputs.react-app-crn-gtm-container-id }}
  react-app-gp2-gtm-container-id:
    description: 'React App GP2 GTM Container ID'
    value: ${{ steps.vars.outputs.react-app-gp2-gtm-container-id }}
  sls-stage:
    description: 'SLS Stage'
    value: ${{ steps.vars.outputs.sls-stage }}
  crn-on-branch-env:
    description: 'Whether the crn Contentful environment being used is a PR environment'
    value: ${{ steps.vars.outputs.crn-on-branch-env }}
  gp2-on-branch-env:
    description: 'Whether the gp2 Contentful environment being used is a PR environment'
    value: ${{ steps.vars.outputs.gp2-on-branch-env }}
runs:
  using: 'composite'
  steps:
    - name: Setup
      id: vars
      shell: bash
      run: |

        function set_outputs () {
          while IFS="=" read name value
          do
              echo "$name=$value" >> $GITHUB_OUTPUT
          done < ./.github/environment/$1
        }

        set_outputs Base
        set_outputs $ENVIRONMENT_NAME

        if [ "$ENVIRONMENT_NAME" = "Branch" ]; then
          PR_NUMBER=${{ github.event.number || github.event.inputs.pr-number || inputs.pr-number }}
          HAS_CONTENTFUL_LABEL=${{ contains(github.event.pull_request.labels.*.name, 'contentful') }}
          AUTH0_LABEL=${{contains(github.event.pull_request.labels.*.name, 'use-pr-auth0-tenant') }}
          echo "auth0-label=$AUTH0_LABEL" >> $GITHUB_OUTPUT
          if [ "$AUTH0_LABEL" = true ]; then
            echo "gp2-auth0-additional-claim-domain=https://$PR_NUMBER.gp2.asap.science" >> $GITHUB_OUTPUT
            echo "gp2-auth0-audience=https://pr.gp2.asap.science" >> $GITHUB_OUTPUT
            echo "gp2-auth-url=https://$PR_NUMBER.gp2.asap.science/.auth/" >> $GITHUB_OUTPUT
            echo "gp2-auth0-client-id=Um9rLU2D9MjAA4LzKZz5MVRl5ESodg4B" >> $GITHUB_OUTPUT
            echo "gp2-ci-auth0-client-id=FUhxz0YEhaLGIfBYOyzJ7ed3e32CCMpW" >> $GITHUB_OUTPUT
            echo "gp2-auth0-domain=pr-gp2-hub.us.auth0.com" >> $GITHUB_OUTPUT

            echo "crn-auth0-additional-claim-domain=https://$PR_NUMBER.hub.asap.science/" >> $GITHUB_OUTPUT
            echo "crn-auth0-audience=https://pr.hub.asap.science" >> $GITHUB_OUTPUT
            echo "crn-auth-url=https://$PR_NUMBER.hub.asap.science/.auth/" >> $GITHUB_OUTPUT
            echo "crn-auth0-client-id=s1ZOMWgaQKtCeRSnr7LRamFWh0WD8azN" >> $GITHUB_OUTPUT
            echo "crn-ci-auth0-client-id=WHi7btcaXqs2lJnvVyp6SP12onYNbkIA" >> $GITHUB_OUTPUT
            echo "crn-auth0-domain=pr-asap-hub.us.auth0.com" >> $GITHUB_OUTPUT
          fi

          CRN_CREATE_CONTENTFUL_PR_ENV=${{ contains(github.event.pull_request.labels.*.name, 'crn-create-environment') || inputs.crn-create-env }}
          GP2_CREATE_CONTENTFUL_PR_ENV=${{ contains(github.event.pull_request.labels.*.name, 'gp2-create-environment') || inputs.gp2-create-env }}
          
          echo "crn-on-branch-env=$CRN_CREATE_CONTENTFUL_PR_ENV" >> $GITHUB_OUTPUT
          echo "gp2-on-branch-env=$GP2_CREATE_CONTENTFUL_PR_ENV" >> $GITHUB_OUTPUT

          echo "pr-number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "sls-stage=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "app-release=${{ github.run_id }}-dev" >> $GITHUB_OUTPUT

          echo "crn-app-url=https://$PR_NUMBER.hub.asap.science" >> $GITHUB_OUTPUT
          echo "crn-api-url=https://api-$PR_NUMBER.hub.asap.science" >> $GITHUB_OUTPUT
          echo "gp2-app-url=https://$PR_NUMBER.gp2.asap.science" >> $GITHUB_OUTPUT
          echo "gp2-api-url=https://api-$PR_NUMBER.gp2.asap.science" >> $GITHUB_OUTPUT

          if [ "$CRN_CREATE_CONTENTFUL_PR_ENV" = true ]; then
            echo "setting up dedicated PR env"
            echo "crn-algolia-index=asap-hub_CI-$PR_NUMBER" >> $GITHUB_OUTPUT
            echo "crn-contentful-env-id=crn-$PR_NUMBER" >> $GITHUB_OUTPUT
          else
            echo "setting up PR pointing to DEV env"
            echo "crn-algolia-index=asap-hub_dev" >> $GITHUB_OUTPUT
            echo "crn-contentful-env-id=Development" >> $GITHUB_OUTPUT
          fi

          if [ "$GP2_CREATE_CONTENTFUL_PR_ENV" = true ]; then
            echo "gp2-algolia-index=gp2-hub_CI-$PR_NUMBER" >> $GITHUB_OUTPUT
            echo "gp2-contentful-env-id=gp2-$PR_NUMBER" >> $GITHUB_OUTPUT
          else
            echo "gp2-algolia-index=gp2-hub_dev" >> $GITHUB_OUTPUT
            echo "gp2-contentful-env-id=Development" >> $GITHUB_OUTPUT
          fi

        elif [ "$ENVIRONMENT_NAME" = 'Development' ]; then
          echo "app-release=${{ github.run_id }}-dev" >> $GITHUB_OUTPUT
        elif [ "$ENVIRONMENT_NAME" = 'Production' ]; then
          echo "app-release=${{ github.run_id }}-prod" >> $GITHUB_OUTPUT
        else
          echo "Unknown environment: $ENVIRONMENT_NAME"
          exit 1
        fi

      env:
        ENVIRONMENT_NAME: ${{ inputs.environment-name }}
