name: 'Setup Environment'
description: 'Generates the environment variables for the workflow'
inputs:
  environment-name:
    description: 'Current environment'
    required: true
  pr-number:
    description: 'The PR number'
    required: true
outputs:
  algolia-app-id-name:
    description: 'Algolia App id SSM name'
    value: ${{ steps.vars.outputs.algolia-app-id-name }}
  algolia-api-key-name:
    description: 'Algolia Api key SSM Name'
    value: ${{ steps.vars.outputs.algolia-api-key-name }}
  algolia-index:
    description: 'Algolia Index'
    value: ${{ steps.vars.outputs.algolia-index }}
  app-release:
    description: 'App Release'
    value: ${{ steps.vars.outputs.app-release }}
  crn-api-url:
    description: 'CRN API Url'
    value: ${{ steps.vars.outputs.crn-api-url }}
  crn-app-url:
    description: 'CRN APP Url'
    value: ${{ steps.vars.outputs.crn-app-url }}
  crn-auth0-audience:
    description: 'CRN Auth0 Audience'
    value: ${{ steps.vars.outputs.crn-auth0-audience }}
  crn-auth0-client-id:
    description: 'CRN Auth0 Client ID'
    value: ${{ steps.vars.outputs.crn-auth0-client-id }}
  crn-auth0-domain:
    description: 'CRN Auth0 Domain'
    value: ${{ steps.vars.outputs.crn-auth0-domain }}
  aws-acm-asap-science-certificate-arn:
    description: 'AWS ACM ASAP Science Certificate ARN'
    value: ${{ steps.vars.outputs.aws-acm-asap-science-certificate-arn }}
  aws-default-region:
    description: 'AWS Default Region'
    value: ${{ steps.vars.outputs.aws-default-region }}
  aws-region:
    description: 'AWS Region'
    value: ${{ steps.vars.outputs.aws-region }}
  algolia-backup-bucket-name:
    description: 'Algolia Backup Bucket Name'
    value: ${{ steps.vars.outputs.algolia-backup-bucket-name }}
  cache-prefix-definitions:
    description: 'Cache Prefix Definitions'
    value: ${{ steps.vars.outputs.cache-prefix-definitions }}
  cache-prefix-frontend:
    description: 'Cache Prefix Frontend'
    value: ${{ steps.vars.outputs.cache-prefix-frontend }}
  cache-prefix-transpile:
    description: 'Cache Prefix Transpile'
    value: ${{ steps.vars.outputs.cache-prefix-transpile }}
  crn-aws-acm-certificate-arn:
    description: 'CRN AWS ACM Certificate ARN'
    value: ${{ steps.vars.outputs.crn-aws-acm-certificate-arn }}
  gp2-api-url:
    description: 'GP2 API Url'
    value: ${{ steps.vars.outputs.gp2-api-url }}
  gp2-app-url:
    description: 'GP2 APP Url'
    value: ${{ steps.vars.outputs.gp2-app-url }}
  gp2-aws-acm-certificate-arn:
    description: 'GP2 AWS ACM Certificate ARN'
    value: ${{ steps.vars.outputs.gp2-aws-acm-certificate-arn }}
  gp2-hostname:
    description: 'GP2 Hostname'
    value: ${{ steps.vars.outputs.gp2-hostname }}
  gp2-auth0-audience:
    description: 'GP2 Auth0 Audience'
    value: ${{ steps.vars.outputs.gp2-auth0-audience }}
  gp2-auth0-client-id:
    description: 'GP2 Auth0 Client ID'
    value: ${{ steps.vars.outputs.gp2-auth0-client-id }}
  gp2-auth0-domain:
    description: 'GP2 Auth0 Domain'
    value: ${{ steps.vars.outputs.gp2-auth0-domain }}
  pr-number:
    description: 'PR Number'
    value: ${{ steps.vars.outputs.pr-number }}
  print-sync-logs-on-success:
    description: 'Print sync logs on success'
    value: ${{ steps.vars.outputs.print-sync-logs-on-success }}
  react-app-environment:
    description: 'React App Environment'
    value: ${{ steps.vars.outputs.react-app-environment }}
  react-app-gtm-container-id:
    description: 'React App GTM Container ID'
    value: ${{ steps.vars.outputs.react-app-gtm-container-id }}
  react-app-sentry-dsn:
    description: 'React App Sentry DSN'
    value: ${{ steps.vars.outputs.react-app-sentry-dsn }}
  crn-sentry-dsn-api:
    description: 'CRN Sentry DSN API'
    value: ${{ steps.vars.outputs.crn-sentry-dsn-api }}
  crn-sentry-dsn-handlers:
    description: 'CRN Sentry DSN Handlers'
    value: ${{ steps.vars.outputs.crn-sentry-dsn-handlers }}
  gp2-sentry-dsn-api:
    description: 'GP2 Sentry DSN API'
    value: ${{ steps.vars.outputs.gp2-sentry-dsn-api }}
  gp2-sentry-dsn-handlers:
    description: 'GP2 Sentry DSN Handlers'
    value: ${{ steps.vars.outputs.gp2-sentry-dsn-handlers }}
  ses-region:
    description: 'SES Region'
    value: ${{ steps.vars.outputs.ses-region }}
  sls-stage:
    description: 'SLS Stage'
    value: ${{ steps.vars.outputs.sls-stage }}
  crn-squidex-app-name:
    description: 'CRN Squidex App Name'
    value: ${{ steps.vars.outputs.crn-squidex-app-name }}
  crn-squidex-app-name-legacy:
    description: 'Legacy CRN Squidex App Name'
    value: ${{ steps.vars.outputs.crn-squidex-app-name-legacy }}
  crn-squidex-backup-bucket-name:
    description: 'CRN Squidex Backup Bucket Name'
    value: ${{ steps.vars.outputs.crn-squidex-backup-bucket-name }}
  squidex-base-url:
    description: 'Squidex Base Url'
    value: ${{ steps.vars.outputs.squidex-base-url }}
  crn-squidex-api-client-id:
    description: 'CRN API Squidex Client ID'
    value: ${{ steps.vars.outputs.crn-squidex-api-client-id }}
  crn-squidex-ci-client-id:
    description: 'CRN CI Squidex Client ID'
    value: ${{ steps.vars.outputs.crn-squidex-ci-client-id }}
  gp2-squidex-app-name:
    description: 'GP2 Squidex App Name'
    value: ${{ steps.vars.outputs.gp2-squidex-app-name }}
  gp2-squidex-backup-bucket-name:
    description: 'GP2 Squidex Backup Bucket Name'
    value: ${{ steps.vars.outputs.gp2-squidex-backup-bucket-name }}
  gp2-squidex-api-client-id:
    description: 'GP2 API Squidex Client ID'
    value: ${{ steps.vars.outputs.gp2-squidex-api-client-id }}
  gp2-squidex-ci-client-id:
    description: 'GP2 CI Squidex Client ID'
    value: ${{ steps.vars.outputs.gp2-squidex-ci-client-id }}
runs:
  using: 'composite'
  steps:
    - name: Setup
      id: vars
      shell: bash
      run: |

        function set_outputs () {
          while IFS="=" read name value
          do
              echo "::set-output name=$name::$value"
          done < ./.github/environment/$1
        }

        set_outputs Base
        set_outputs $ENVIRONMENT_NAME

        if [ "$ENVIRONMENT_NAME" = "Branch" ]; then
          PR_NUMBER=${{ github.event.number || github.event.inputs.pr-number || inputs.pr-number }}
          echo "::set-output name=algolia-index::asap-hub_CI-$PR_NUMBER"
          echo "::set-output name=app-release::${{ github.run_id }}-dev"
          echo "::set-output name=crn-api-url::https://api-$PR_NUMBER.hub.asap.science"
          echo "::set-output name=crn-app-url::https://$PR_NUMBER.hub.asap.science"
          echo "::set-output name=gp2-api-url::https://api-$PR_NUMBER.gp2.asap.science"
          echo "::set-output name=gp2-app-url::https://$PR_NUMBER.gp2.asap.science"
          echo "::set-output name=pr-number::$PR_NUMBER"
          echo "::set-output name=sls-stage::$PR_NUMBER"
          echo "::set-output name=crn-squidex-app-name::crn-$PR_NUMBER"
          echo "::set-output name=crn-squidex-app-name-legacy::$PR_NUMBER"
          echo "::set-output name=gp2-squidex-app-name::gp2-$PR_NUMBER"
        elif [ "$ENVIRONMENT_NAME" = 'Development' ]; then
          echo "::set-output name=app-release::${{ github.run_id }}-dev"
        elif [ "$ENVIRONMENT_NAME" = 'Production' ]; then
          echo "::set-output name=app-release::${{ github.run_id }}-prod"
        else
          echo "Unknown environment: $ENVIRONMENT_NAME"
          exit 1
        fi

      env:
        ENVIRONMENT_NAME: ${{ inputs.environment-name }}
