import { pixels } from '@asap-hub/react-components';

import { workingGroupsImage } from '../images';
import { mainStyles } from '../layout';
import { PageBanner } from '../organisms';
import PageNotifications from './PageNotifications';

const { rem } = pixels;

const bannerProps = {
  image: workingGroupsImage,
  position: 'center',
  title: 'Outputs',
  description: 'Explore the research outputs generated by the GP2 network.',
};

const OutputsPage: React.FC = ({ children }) => (
  <PageNotifications page="outputs">
    {(notification) => (
      <article
        css={notification ? { position: 'relative', marginTop: rem(48) } : {}}
      >
        <PageBanner {...bannerProps}></PageBanner>
        <main css={mainStyles}>{children}</main>
      </article>
    )}
  </PageNotifications>
);
export default OutputsPage;
