import { css } from '@emotion/react';
import { pixels } from '@asap-hub/react-components';
import { workingGroupsImage } from '../images';
import { mainStyles, layoutContentStyles } from '../layout';
import { OutputDropdown, PageBanner } from '../organisms';

const { rem } = pixels;

const bannerProps = {
  image: workingGroupsImage,
  position: 'center',
  title: 'Outputs',
  description: 'Explore the research outputs generated by the GP2 network.',
};

const buttonStyles = css({
  maxWidth: rem(181),
});

const OutputsPage: React.FC = ({ children }) => (
  <article>
    <div css={layoutContentStyles}>
      <PageBanner {...bannerProps}>
        <div css={buttonStyles}>
          <OutputDropdown />
        </div>
      </PageBanner>
      <main css={mainStyles}>{children}</main>
    </div>
  </article>
);
export default OutputsPage;
