name: 'Algolia Sync Settings'
description: 'Sync Algolia settings'
inputs:
  algolia-app-id-name:
    description: 'SSM Algolia app id name'
    required: true
  algolia-api-key-name:
    description: 'SSM Algolia api key name'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-default-region:
    description: 'AWS Region'
    required: true
  algolia-index:
    description: 'Algolia Index'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Environment Variables
      shell: bash
      run: |
        echo "ALGOLIA_APP_ID=$(aws ssm get-parameter --name '${{ inputs.algolia-app-id-name }}' --query Parameter.Value --output text)" >> $GITHUB_ENV
        echo "ALGOLIA_API_KEY=$(aws ssm get-parameter --name '${{ inputs.algolia-api-key-name }}' --query Parameter.Value --output text)" >> $GITHUB_ENV
        echo "::add-mask::$ALGOLIA_API_KEY"
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-default-region }}
    - name: Synchronize Schema
      shell: bash
      run: |
        yarn run algolia:upload
      env:
        ALGOLIA_INDEX: ${{ inputs.algolia-index }}
