import {
  CalendarDataObject,
  CalendarResponse,
  isGoogleLegacyCalendarColor,
} from '@asap-hub/model';
import { CalendarsFlatDataDto } from '../autogenerated-gql/graphql';
import { parseCalendarDataObjectToResponse } from '../controllers/calendars';

export const parseGraphqlCalendarToResponse = (
  graphqlCalendar: Pick<
    CalendarsFlatDataDto,
    'name' | 'googleCalendarId' | 'color'
  >,
): CalendarResponse =>
  parseCalendarDataObjectToResponse(
    parseGraphqlCalendarPartialToDataObject(graphqlCalendar),
  );

export const parseGraphqlCalendarPartialToDataObject = (
  graphqlCalendar: Pick<
    CalendarsFlatDataDto,
    'name' | 'googleCalendarId' | 'color'
  >,
): Pick<CalendarDataObject, 'name' | 'googleCalendarId' | 'color'> => ({
  color: isGoogleLegacyCalendarColor(graphqlCalendar.color)
    ? graphqlCalendar.color
    : ('#333333' as const),
  googleCalendarId: graphqlCalendar.googleCalendarId ?? '',
  name: graphqlCalendar.name ?? '',
});
