import {
  CalendarResponse,
  GroupDataObject,
  GroupLeader,
  GroupRole,
  GroupTeam,
  GroupTools,
  UserDataObject,
  isGroupRole,
} from '@asap-hub/model';
import { parseDate } from '@asap-hub/squidex';
import { URL } from 'url';
import { FetchGroupQuery } from '../autogenerated-gql/graphql';
import { parseGraphQLUserToDataObject } from '../data-providers/users.data-provider';
import { createUrl } from '../utils/urls';
import { parseGraphqlCalendarToResponse } from './calendar';
import { parseGraphQLTeam } from './team';

export const parseInterestGroupLeader = (
  user: UserDataObject,
): GroupLeader['user'] => ({
  id: user.id,
  firstName: user.firstName,
  lastName: user.lastName,
  displayName: `${user.firstName} ${user.lastName}`,
  email: user.email,
  teams: user.teams,
  avatarUrl: user.avatarUrl,
  alumniSinceDate: user.alumniSinceDate,
});

export const parseGraphQLInterestGroup = (
  item: NonNullable<FetchGroupQuery['findGroupsContent']>,
): GroupDataObject => {
  const createdDate = parseDate(item.created).toISOString();
  const teams: GroupTeam[] = (item.flatData.teams || []).map((t) => {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { members, labCount, ...team } = parseGraphQLTeam(t);
    return team;
  });
  const calendars: CalendarResponse[] = (item.flatData?.calendars || []).map(
    (c) => parseGraphqlCalendarToResponse(c.flatData),
  );

  const leaders = (item.flatData.leaders || []).reduce(
    (leaderList: GroupLeader[], leader) => {
      if (leader.user === null || !leader.user[0]) {
        return leaderList;
      }
      if (!isGroupRole(leader.role)) {
        throw new Error(`Invalid group role on leaders : ${leader.role}`);
      }

      return [
        ...leaderList,
        {
          user: parseInterestGroupLeader(
            parseGraphQLUserToDataObject(leader.user[0]),
          ),
          role: leader.role as GroupRole,
          inactiveSinceDate: leader.inactiveSinceDate ?? undefined,
        },
      ];
    },
    [],
  );

  let tools: GroupTools = {};
  if (item.flatData.tools?.length) {
    const [groupTools] = item.flatData.tools;
    if (groupTools?.slack) {
      tools = { ...tools, slack: groupTools.slack };
    }

    if (groupTools?.googleDrive) {
      tools = { ...tools, googleDrive: groupTools.googleDrive };
    }
  }

  if (item.flatData.calendars?.length) {
    const url = new URL('https://calendar.google.com/calendar/r');
    url.searchParams.set('cid', item.flatData.calendars[0]?.id || '');
    tools = { ...tools, googleCalendar: url.toString() };
  }

  return {
    id: item.id,
    createdDate,
    active: item.flatData.active ?? true,
    name: item.flatData.name || '',
    tags: item.flatData.tags || [],
    description: item.flatData.description || '',
    contactEmails: leaders
      .filter(
        ({ role, inactiveSinceDate, user: { alumniSinceDate } }) =>
          role === 'Project Manager' && !alumniSinceDate && !inactiveSinceDate,
      )
      .map(({ user }) => user.email),
    tools,
    teams,
    leaders,
    calendars,
    thumbnail: item.flatData.thumbnail?.length
      ? createUrl(item.flatData.thumbnail.map((t) => t.id))[0]
      : undefined,
    lastModifiedDate: parseDate(item.lastModified).toISOString(),
  };
};
