import {
  isResearchOutputDocumentType,
  DecisionOption,
  ResearchOutputResponse,
  ResearchOutputSharingStatus,
  researchOutputMapType,
  sharingStatuses,
  TeamResponse,
} from '@asap-hub/model';
import { parseDate } from '@asap-hub/squidex';
import {
  FetchResearchOutputQuery,
  Labs,
  Scalars,
} from '../autogenerated-gql/graphql';
import { parseGraphQLUser } from './user';

export const parseGraphQLResearchOutput = (
  output: NonNullable<FetchResearchOutputQuery['findResearchOutputsContent']>,
  options?: {
    includeAuthors?: boolean;
    includeTeams?: boolean;
  },
):
  | Omit<ResearchOutputResponse, 'authors' | 'teams'>
  | Partial<Pick<ResearchOutputResponse, 'authors' | 'teams'>> => {
  const optionalAuthors = options?.includeAuthors
    ? {
        authors:
          output.flatData.authors
            ?.filter(
              (author) =>
                author.__typename !== 'Users' ||
                author.flatData?.onboarded !== false,
            )
            .map((author) => {
              if (author.__typename === 'Users') {
                return parseGraphQLUser(author);
              }

              return {
                id: author.id,
                displayName: author.flatData?.name,
                orcid: author.flatData?.orcid,
              };
            }) || [],
      }
    : {};

  const optionalTeams = options?.includeTeams
    ? {
        teams:
          output.referencingTeamsContents?.map((team) =>
            parseGraphqlTeamLite(team),
          ) || [],
      }
    : {};

  const contactEmails =
    output.referencingTeamsContents?.flatMap((team) =>
      team.referencingUsersContents
        ?.filter(
          (user) =>
            user.flatData.teams &&
            user.flatData.teams.filter(
              (innerTeam) =>
                innerTeam.role === 'Project Manager' &&
                innerTeam.id?.[0]?.id === team.id,
            ).length !== 0,
        )
        .map((user) => user.flatData?.email),
    ) || [];

  const filteredContactEmails = contactEmails?.filter(
    (email): email is string => email !== undefined,
  ) as string[];

  const uniqueContactEmails = [...new Set(filteredContactEmails)];

  const data = output.flatData;
  const type = researchOutputMapType(data.type);

  return {
    id: output.id,
    created: parseDate(output.created).toISOString(),
    link: data.link || undefined,
    documentType:
      data.documentType && isResearchOutputDocumentType(data.documentType)
        ? data.documentType
        : 'Grant Document',
    type: type || undefined,
    title: data.title || '',
    description: data.description || '',
    tags: data.tags || [],
    publishDate: data.publishDate || undefined,
    labCatalogNumber: data.labCatalogNumber || undefined,
    doi: data.doi || undefined,
    accession: data.accession || undefined,
    rrid: data.rrid || undefined,
    addedDate: data.addedDate,
    lastUpdatedPartial:
      data.lastUpdatedPartial || output.lastModified || output.created,
    accessInstructions: data.accessInstructions || undefined,
    ...optionalAuthors,
    ...optionalTeams,
    sharingStatus:
      data.sharingStatus !== null && isSharingStatus(data.sharingStatus)
        ? data.sharingStatus
        : 'Network Only',
    asapFunded: convertDecisionToBoolean(data.asapFunded),
    usedInPublication: convertDecisionToBoolean(data.usedInAPublication),
    contactEmails: uniqueContactEmails,
    labs:
      data.labs
        ?.filter((lab): lab is LabWithName => lab.flatData.name !== null)
        .map((lab) => ({
          id: lab.id,
          name: lab.flatData.name,
        })) || [],
    methods:
      data.methods?.flatMap((method) =>
        method.flatData.name ? [method.flatData.name] : [],
      ) || [],
    organisms:
      data.organisms?.flatMap((organism) =>
        organism.flatData.name ? [organism.flatData.name] : [],
      ) || [],
    environments:
      data.environments?.flatMap((environment) =>
        environment.flatData.name ? [environment.flatData.name] : [],
      ) || [],
    subtype: data.subtype?.[0]?.flatData.name || undefined,
  };
};

const parseGraphqlTeamLite = (
  graphqlTeam: FetchResearchOutputTeamContents,
): Pick<TeamResponse, 'id' | 'displayName'> => ({
  id: graphqlTeam.id,
  displayName: graphqlTeam.flatData?.displayName || '',
});

const convertDecisionToBoolean = (
  decision: string | null,
): boolean | undefined =>
  decision && ['Yes', 'No'].includes(decision) ? decision === 'Yes' : undefined;

export const convertBooleanToDecision = (bool?: boolean): DecisionOption => {
  if (typeof bool === 'undefined') {
    return 'Not Sure';
  }
  return bool ? 'Yes' : 'No';
};

const isSharingStatus = (
  status: string,
): status is ResearchOutputSharingStatus =>
  (sharingStatuses as ReadonlyArray<string>).includes(status);

type FetchResearchOutputTeamContents = NonNullable<
  NonNullable<
    FetchResearchOutputQuery['findResearchOutputsContent']
  >['referencingTeamsContents']
>[number];

type LabWithName = Pick<Labs, 'id'> & {
  flatData: {
    name: Scalars['String'];
  };
};
