import { TutorialsResponse } from '@asap-hub/model';
import { parseDate } from '@asap-hub/squidex';
import {
  Tutorials,
  TutorialsFlatDataDto,
  Asset,
  Maybe,
} from '../autogenerated-gql/graphql';
import { createUrl } from '../utils/urls';

type Item = Pick<Tutorials, 'id' | 'created'> & {
  flatData: Pick<
    TutorialsFlatDataDto,
    'title' | 'shortText' | 'text' | 'link' | 'linkText'
  > & {
    thumbnail: Maybe<Pick<Asset, 'id'>[]>;
  };
};

export const parseGraphQLTutorials = (item: Item): TutorialsResponse => {
  const createdDate = parseDate(item.created).toISOString();
  return {
    id: item.id,
    created: createdDate,
    title: item.flatData.title || '',
    shortText: item.flatData.shortText || '',
    text: item.flatData.text || undefined,
    link: item.flatData.link || undefined,
    linkText: item.flatData.linkText || undefined,
    thumbnail: item.flatData.thumbnail?.length
      ? createUrl(item.flatData.thumbnail.map((t) => t.id))[0]
      : undefined,
  };
};
