name: 'Algolia Sync Settings'
description: 'Sync Algolia settings'
inputs:
  algolia-app-id-name:
    description: 'SSM Algolia app id name'
    required: true
  algolia-api-key-name:
    description: 'SSM Algolia api key name'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-default-region:
    description: 'AWS Region'
    required: true
  algolia-index:
    description: 'Algolia Index'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Get Algolia Keys
      id: algolia-keys
      uses: ./.github/actions/algolia-keys
      with:
        algolia-app-id-name: ${{ inputs.algolia-app-id-name }}
        algolia-api-key-name: ${{ inputs.algolia-api-key-name }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-default-region: ${{ inputs.aws-default-region }}
    - name: Synchronize Schema
      shell: bash
      run: |
        yarn run algolia:upload
      env:
        ALGOLIA_API_KEY: ${{ steps.algolia-keys.outputs.algolia-api-key }}
        ALGOLIA_APP_ID: ${{ steps.algolia-keys.outputs.algolia-app-id }}
        ALGOLIA_INDEX: ${{ inputs.algolia-index }}
