name: 'Test Integration'
description: 'Runs Test Integration'
inputs:
  squidex-app-name:
    description: 'Squidex App Name'
    required: true
  squidex-base-url:
    description: 'Squidex Base Url'
    required: true
  squidex-client-id:
    description: 'Squidex Client ID'
    required: true
  squidex-client-secret:
    description: 'Squidex Client Secret'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup app
      shell: bash
      run: |
        python ci/integration/scripts/create-app.py
        yarn test:integration
      env:
        SQUIDEX_APP_NAME: ${{ inputs.squidex-app-name }}
        SQUIDEX_CLIENT_ID: ${{ inputs.squidex-client-id }}
        SQUIDEX_CLIENT_SECRET: ${{ inputs.squidex-client-secret }}
        SQUIDEX_BASE_URL: ${{ inputs.squidex-base-url }}
    - name: Delete app
      shell: bash
      if: always()
      run: python ci/integration/scripts/delete-app.py
      env:
        SQUIDEX_APP_NAME: ${{ inputs.squidex-app-name }}
        SQUIDEX_CLIENT_ID: ${{ inputs.squidex-client-id }}
        SQUIDEX_CLIENT_SECRET: ${{ inputs.squidex-client-secret }}
        SQUIDEX_BASE_URL: ${{ inputs.squidex-base-url }}
