name: 'Cache transpile'
description: 'Cache transpile'
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v3
      with:
        path: |
          apps/**/build*
          packages/**/build*
        key: transpile-output-${{ inputs.environment-name }}-${{ github.sha }}
