name: Contentful Setup
description: Setup Webhooks for Contentful

inputs:
  contentful-space-id:
    description: 'Contenful Space ID'
    required: true
  contentful-environment:
    description: 'Contentful Environment'
    required: true
  contentful-token:
    description: 'Contentful Management Token'
    required: true
  api-url:
    description: 'API URL'
    required: true
  contentful-webhook-authentication-token:
    description: 'Contentful Webhook Authentication Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Contentful Webhook
      shell: bash
      run: |
        yarn workspace @asap-hub/contentful space:setup-webhook
      env:
        CONTENTFUL_SPACE_ID: ${{ inputs.contentful-space-id }}
        CONTENTFUL_ENVIRONMENT: ${{ inputs.contentful-environment }}
        CONTENTFUL_MANAGEMENT_ACCESS_TOKEN: ${{ inputs.contentful-token }}
        CONTENTFUL_WEBHOOK_AUTHENTICATION_TOKEN: ${{ inputs.contentful-webhook-authentication-token }}
        API_URL: ${{ inputs.api-url }}
