name: 'Cache definitions'
description: 'Cache definitions'
inputs:
  cache-prefix:
    description: 'The name of the cache'
    required: true
  environment-name:
    description: 'The name of the environment to cache'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup
      id: setup
      uses: ./.github/actions/setup-environment
      with:
        environment-name: ${{ inputs.environment-name }}
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          apps/**/build*
          apps/**/dist*
          packages/**/build*
        key: ${{ inputs.cache-prefix }}-${{ inputs.environment-name }}-${{ github.sha }}-${{ steps.setup.outputs.crn-algolia-index }}-${{ steps.setup.outputs.gp2-algolia-index }}
