import { SquidexGraphqlClient } from '@asap-hub/squidex';
import { GraphQLFileLoader } from '@graphql-tools/graphql-file-loader';
import { loadSchemaSync } from '@graphql-tools/load';
import { addMocksToSchema, createMockStore } from '@graphql-tools/mock';
import {
  ASTNode,
  DocumentNode,
  ExecutionResult,
  graphql,
  print,
} from 'graphql';
import { getSquidexGraphqlCalendar } from '../fixtures/calendars.fixtures';
import { getSquidexGraphqlDashboard } from '../fixtures/dashboard.fixtures';
import { getSquidexGraphqlDiscover } from '../fixtures/discover.fixtures';
import { getSquidexGraphqlEvent } from '../fixtures/events.fixtures';
import { getSquidexGraphqlGroup } from '../fixtures/groups.fixtures';
import { getSquidexGraphqlLab } from '../fixtures/labs.fixtures';
import { getSquidexGraphqlResearchOutput } from '../fixtures/research-output.fixtures';
import { getSquidexGraphqlTeam } from '../fixtures/teams.fixtures';
import { getGraphQLUser } from '../fixtures/users.fixtures';
import { getGraphQLExternalAuthor } from '../fixtures/external-authors.fixtures';
import { getSquidexGraphqlResearchTags } from '../fixtures/research-tag.fixtures';

export const getSquidexGraphqlClientMockServer = (): SquidexGraphqlClient => {
  const schema = loadSchemaSync(
    '../../src/schema/autogenerated-schema.graphql',
    {
      cwd: __dirname,
      loaders: [new GraphQLFileLoader()],
    },
  );
  const resultDto = () => ({
    items: [...new Array(1)],
    total: 1,
  });
  const mocks = {
    ExternalAuthors: () => getGraphQLExternalAuthor(),
    ExternalAuthorsDto: () => resultDto,
    Int: () => 8,
    Instant: () => '2021-10-12T15:42:05Z',
    JsonScalar: () => {},
    Groups: () => getSquidexGraphqlGroup(),
    GroupsResultDto: resultDto,
    ResearchOutputs: () => getSquidexGraphqlResearchOutput(),
    ResearchOutputsResultDto: resultDto,
    ResearchTags: () => getSquidexGraphqlResearchTags().items![0],
    ResearchTagsResultDto: resultDto,
    Users: () => getGraphQLUser(),
    UsersResultDto: resultDto,
    Teams: () => getSquidexGraphqlTeam({}),
    TeamsResultDto: resultDto,
    Discover: () => getSquidexGraphqlDiscover(),
    DiscoveryResultDto: resultDto,
    Dashboard: () => getSquidexGraphqlDashboard(),
    DashboardResultDto: resultDto,
    Calendars: () => getSquidexGraphqlCalendar(),
    CalendarsResultDto: resultDto,
    Events: () => getSquidexGraphqlEvent(),
    EventsResultDto: resultDto,
    Labs: () => getSquidexGraphqlLab(),
    LabsResultDto: resultDto,
    AppQueries: () => ({
      queryResearchOutputsContents: [...new Array(1)],
    }),
  };
  const store = createMockStore({
    schema,
    mocks,
    typePolicies: {
      ExternalAuthors: {
        keyFieldName: false,
      },
      UsersDataTeamsChildDto: {
        keyFieldName: false,
      },
      Teams: {
        keyFieldName: false,
      },
      Groups: {
        keyFieldName: false,
      },
      Calendars: {
        keyFieldName: false,
      },
      Events: {
        keyFieldName: false,
      },
      GroupsDataLeadersChildDto: {
        keyFieldName: false,
      },
      GroupsFlatDataDto: {
        keyFieldName: false,
      },
      Users: {
        keyFieldName: false,
      },
      ResearchTags: {
        keyFieldName: false,
      },
    },
  });
  const schemaWithMocks = addMocksToSchema({
    schema,
    store,
  });

  return {
    request: async <T extends { [key: string]: any }, V>(
      query: string | DocumentNode,
      variables?: V,
    ): Promise<T> => {
      const result = (await graphql(
        schemaWithMocks,
        print(query as ASTNode),
        undefined,
        undefined,
        variables,
      )) as ExecutionResult<T>;

      if (Array.isArray(result.errors) && result.errors.length > 0) {
        throw new Error(JSON.stringify(result.errors));
      }

      return result.data as T;
    },
  };
};
