import { GraphQLClient } from 'graphql-request';

type CreateClientParams = {
  space: string;
  accessToken: string;
  environment: string;
};
export const getGraphQLClient = ({
  space,
  accessToken,
  environment,
}: CreateClientParams) => {
  const endpoint = `https://graphql.contentful.com/content/v1/spaces/${space}/environments/${environment}`;
  return new GraphQLClient(endpoint, {
    headers: {
      authorization: `Bearer ${accessToken}`,
    },
  });
};

export { gql, GraphQLClient } from 'graphql-request';

export * from './utils';
export * from './mocks/graphql-client.mock';
export * from './crn/queries';
export type {
  FetchNewsByIdQuery,
  FetchNewsByIdQueryVariables,
  FetchNewsQuery,
  FetchNewsQueryVariables,
  FetchPagesQuery,
  FetchPagesQueryVariables,
  NewsFilter,
  QueryNewsCollectionArgs,
} from './crn/autogenerated-gql/graphql';
export { NewsOrder } from './crn/autogenerated-gql/graphql';
