export const map = {
  'Administrative Support': '5bdFIjmZHjlknn0F41Ih0p',
  'Advanced Parkinson’s therapies': '4eycY6l1kjBcYVtnP6882v',
  Biostatistics: '3tWD1TXFZOgGawK9xXEPyy',
  'BLAAC-PD': 'fQqVZ4ExVxTgBjKS3ve9o',
  'Botulinum toxin therapies': '1IQYJ5lB3FYkPH2BKCW2AR',
  Clinical: 'rbs8f3B4ec7iKt9JC5xxy',
  'Clinical Neuroscience': '5MooGRpbUDHRqsBrul5c3V',
  'Clinical Operations': '3mOWXwvhRppmmAHyKRUN3U',
  Cohort: '60xEWVJUh8s9PCjFtTaJyD',
  Communications: '5muWTqcj6Gz5sw77GZgFvX',
  'Course Management': 'z69R4Vo0kJeOXYujDLUzP',
  'Data Science': '7irK5DxApcg92rHQNbOSLb',
  'Database and clinical information management': '25WxYIGwHjjqszua2houqk',
  Dementia: '3iWucPNKUYEXhGRjwjWdJk',
  Diversity: '7x1CVxrYt4nAdJfDbXE1bs',
  Dystonia: '1fl4vU1ZPBu4Nk2cMTskk1',
  Education: '4GSZbIsm8HU1yEoJneGcsc',
  Epidemiology: '6Q3N9IFdxd0ZWtWZIFRh3J',
  GBA1: '6I6CxpFsPzFCq9QnR6R7SZ',
  'GCH-1': '1leH6aeuj6WZwcZJYBiZwE',
  Genetics: '67GoOnTwA1dGqAeJ8QNToj',
  'Genetics of Parkinson’s': '3iIECj9XM2fLUdzucwLThV',
  'Genetics of Progressive supranuclear palsy': '2RvEirhQC13KvZYEAboLP8',
  Genomics: '6QzE7PjJz6e90L2SbsZh07',
  'Grants administration': '1ZmZVSs0WkO0IdqjstcSlP',
  GWAS: '14E2O4gHYYDszsQb9HWGKZ',
  'Information Technology': '3vr5jQMCYnGhd5rhdMKJx',
  'Laboratory Science': '1Jg5deONJY4taj422bIbCs',
  LatinX: '36Fx5bpgvdLReUJOLXo7MO',
  'Machine Learning': 'yDD5bfwoXXHFNKRF1TpbL',
  'Molecular Biology': '1q1hFJLJElWb8tOiGybypg',
  'Movement Disorders': '3GAIgO0FtPVQpMuGdK9tCZ',
  Neurodegeneration: '6GvNNM0v5htmVSS0J3sUuh',
  Neurogenetics: 'nOIuzrhCWcizgb9sPmAx4',
  Neurology: '1VkXK5guxpJtsWunSUa2OJ',
  'Parkinson-plus syndromes': '66z87yHZmJ3JUiY8wPKoZB',
  'Patient Engagement': '5vno35aFCtrJqaFW4UMksc',
  Pharmacogenomics: '4mYU6HSHvLK9fM8yOqakS5',
  'Progressive supranuclear palsy (PSP)': '3efdoXkgl6VjliBJfJAskz',
  'Project Management': 'Zwe3yMLWR47epR71wWytt',
  'Program Management': '3nfqRgu11QlJANQONSMMIR',
  PRS: '7zfr6LX6hjE97WOJY8gdgC',
  'Rare Genetic Disorders': '7wM5joEjAEzRBo9IrabNRk',
  'Research Communications': '5uEIh164yhGhhcfc6obPJ7',
  Trainee: '8lvq7pKP0j8XV2xBbrXni',
  'Training Opportunities': '1BOJtvvnKjzU9Ys3FKwjsk',
};
