export const map = {
  'Administrative Support': '2wLE9ongyVPva1pq6IUIZJ',
  'Advanced Parkinson’s therapies': '5wVUEuV1JuBDB86sUTodU9',
  Biostatistics: '4mbMjQigzFLMIyc0KCDbcU',
  'BLAAC-PD': '4JtQkag0ubTVzuZKAoEavJ',
  'Botulinum toxin therapies': '3dhneFovKelVykIwcyjhZI',
  Clinical: '4kYbuQlBgXnz6OKKInXSDO',
  'Clinical Neuroscience': '5kq6GnKJehaE2QEyLuuxnm',
  'Clinical Operations': '7I7HFiWhT7xhY8bekcTHEz',
  Cohort: '5PJlH43ZByjfYNM6BlWze4',
  Communications: '4q3PN6Lm38avb3FT5dRvyQ',
  'Course Management': '1knTqMotYHxt88KkzdQANn',
  'Data Science': '3gJLgW2vT2wQSDP4nbFs22',
  'Database and clinical information management': '6Bvf492CAskeq8GnxvAiVe',
  Dementia: '0173OTOwDc1g9AbKfm2Ahj',
  Diversity: '24AIcoREW0mwfI61VcA3L5',
  Dystonia: '1G5uEQCpv6aeACeurcF9BQ',
  Education: '1rfsOe46Jlm08wheoKA7Lk',
  Epidemiology: '6HrSZcI3skFYZKDtCrCKcl',
  GBA1: '4tfEPq1Y5hBbEMyUH2XGN1',
  'GCH-1': '3zdzviiAgfKUMj5znSiHLc',
  Genetics: '6UO99DTmwhGbgZG774g0y5',
  'Genetics of Parkinson’s': '5gOcywTOhKuqLnXm6iJPvb',
  'Genetics of Progressive supranuclear palsy': '7qBBajCMwDDIO5Ld4GiOqG',
  Genomics: '6gWfOOvFvqyFz9dGhARpK6',
  'Grants administration': '2fsg8cAQltUF6AIVykgfZx',
  GWAS: '3Tab9x1zJxzBqiKgM5n30v',
  'Information Technology': '5CpDrAPHIXPEIbBIaIYALi',
  'Laboratory Science': '4VEgGu6LDrLlrRau2fxWyr',
  LatinX: '612thmSGDoVO9acpylpMi0',
  'Machine Learning': '37Mq9zKT84Jg7202RRWxbV',
  'Molecular Biology': '4n5LOakdVTcc8Ffy3Aeroy',
  'Movement Disorders': '2CbW2wNU0YOlFswXURo03W',
  Neurodegeneration: '1akhBSWqlbt4l3RyUD7Vmc',
  Neurogenetics: '5uYTTiBv2N4S2fp70ufGzx',
  Neurology: '1d0Fz58LHsIVzvXycEyGZw',
  'Parkinson-plus syndromes': '7irCTlKFCZW8ZALUrokHiD',
  'Patient Engagement': '1p72qCOxK0ac9eAiBQ7ueL',
  Pharmacogenomics: '3VJAHB9LUD0DwAKVGIpzqd',
  'Progressive supranuclear palsy (PSP)': '4VQ0nvdWEP7ZanpiIU6HwK',
  'Project management': '5oVPw9DXszWpLs3Cnkgsln',
  'Program Management': '7erlsQixrYNY2BlSEpZKbq',
  PRS: '6ly7LMQdtf3RfKrNL6YvD2',
  'Rare Genetic Disorders': '10kXGhb4rfQSHXOxYJxacE',
  'Research Communications': '5AoDDrGmZ4A2LgNguMdm2Q',
  Trainee: '43R5mXk2gz52unkn8vxD0c',
  'Training Opportunities': '7idDOEM8q8zKzF77piIf7v',
};
