import * as components from '@asap-hub/gp2-components';

export default { title: 'GP2 / Icons' };

export const addIcon = () => components.addIcon;
export const ArticleIcon = () => <components.ArticleIcon />;
export const binIcon = () => components.binIcon;
export const copyIcon = () => components.copyIcon;
export const dashboardIcon = () => components.dashboardIcon;
export const dateIcon = () => components.dateIcon;
export const editIcon = () => components.editIcon;
export const exportIcon = () => components.exportIcon;
export const gp2LogoFull = () => components.gp2LogoFull;
export const gp2LogoSmall = () => components.gp2LogoSmall;
export const leftArrowIcon = () => components.leftArrowIcon;
export const locationIcon = () => components.locationIcon;
export const projectIcon = () => components.projectIcon;
export const outputArticle = () => components.outputArticle;
export const outputCode = () => components.outputCode;
export const outputDataset = () => components.outputDataset;
export const outputForm = () => components.outputForm;
export const outputReport = () => components.outputReport;
export const outputMaterial = () => components.outputMaterial;
export const outputIcon = () => components.outputsIcon;
export const regionAfricaIcon = () => components.regionAfricaIcon;
export const regionAsiaIcon = () => components.regionAsiaIcon;
export const regionAustralasiaIcon = () => components.regionAustralasiaIcon;
export const regionEuropeIcon = () => components.regionEuropeIcon;
export const regionLatinAmericaIcon = () => components.regionLatinAmericaIcon;
export const regionNorthAmericaIcon = () => components.regionNorthAmericaIcon;
export const regionSouthAmericaIcon = () => components.regionSouthAmericaIcon;
export const rightArrowIcon = () => components.rightArrowIcon;
export const roleIcon = () => components.roleIcon;
export const usersIcon = () => components.usersIcon;
export const workingGroupIcon = () => components.workingGroupIcon;
