import * as components from '@asap-hub/gp2-components';

export default { title: 'GP2 / Icons' };

export const AddIcon = () => components.addIcon;
export const ArticleIcon = () => <components.ArticleIcon />;
export const BinIcon = () => components.binIcon;
export const DashboardIcon = () => components.dashboardIcon;
export const DateIcon = () => components.dateIcon;
export const EditIcon = () => components.editIcon;
export const ExportIcon = () => components.exportIcon;
export const Gp2LogoSmall = () => components.gp2LogoSmall;
export const LeftArrowIcon = () => components.leftArrowIcon;
export const LocationIcon = () => components.locationIcon;
export const ProjectIcon = () => components.projectIcon;
export const OutputArticle = () => components.outputArticle;
export const OutputCode = () => components.outputCode;
export const OutputDataset = () => components.outputDataset;
export const OutputForm = () => components.outputForm;
export const OutputReport = () => components.outputReport;
export const OutputMaterial = () => components.outputMaterial;
export const OutputIcon = () => components.outputsIcon;
export const RegionAfricaIcon = () => components.regionAfricaIcon;
export const RegionAsiaIcon = () => components.regionAsiaIcon;
export const RegionAustralasiaIcon = () => components.regionAustralasiaIcon;
export const RegionEuropeIcon = () => components.regionEuropeIcon;
export const RegionLatinAmericaIcon = () => components.regionLatinAmericaIcon;
export const RegionNorthAmericaIcon = () => components.regionNorthAmericaIcon;
export const RegionSouthAmericaIcon = () => components.regionSouthAmericaIcon;
export const RightArrowIcon = () => components.rightArrowIcon;
export const RoleIcon = () => components.roleIcon;
export const UsersIcon = () => components.usersIcon;
export const WorkingGroupIcon = () => components.workingGroupIcon;
