import { DashboardDataObject, DashboardResponse } from '@asap-hub/model';
import { FetchDashboardQuery as FetchDashboardQueryContentful } from '@asap-hub/contentful';
import { FetchDashboardQuery } from '../../src/autogenerated-gql/graphql';
import { appName, baseUrl } from '../../src/config';
import { getContentfulNewsGraphqlResponse } from './news.fixtures';
import { getContentfulPagesGraphqlResponse } from './page.fixtures';

export const squidexGraphqlDashboardFlatData = (): NonNullable<
  NonNullable<FetchDashboardQuery['queryDashboardContents']>[number]['flatData']
> => ({
  news: [
    {
      id: 'news-1',
      created: '2020-09-08T16:35:28.000Z',
      lastModified: '2020-10-15T17:55:21Z',
      version: 42,
      flatData: {
        title: 'News 1',
        type: 'News',
        shortText: 'Short text of news 1',
        text: '<p>text</p>',
        frequency: 'News Articles',
        link: null,
        linkText: null,
        thumbnail: [
          {
            id: 'thumbnail-uuid1',
          },
        ],
      },
    },
  ],
  pages: [
    {
      id: 'some-id',
      created: '2020-09-08T16:35:28.000Z',
      lastModified: '2020-10-15T17:55:21Z',
      version: 42,
      flatData: {
        path: '/privacy-policy',
        shortText: 'short text',
        text: '<h1>Privacy Policy</h1>',
        title: 'Privacy Policy',
        link: 'link',
        linkText: 'linkText',
      },
    },
  ],
});

export const getSquidexGraphqlDashboard = () => ({
  id: 'ec3086d4-aa64-4f30-a0f7-5c5b95ffbcca',
  created: '2020-09-23T16:34:26.842Z',
  lastModified: '2021-05-14T14:48:46Z',
  version: 42,
  flatData: squidexGraphqlDashboardFlatData(),
});

export const getContentfulDashboardGraphqlResponse =
  (): FetchDashboardQueryContentful => ({
    dashboardCollection: {
      items: [
        {
          newsCollection: getContentfulNewsGraphqlResponse().newsCollection!,
          pagesCollection: getContentfulPagesGraphqlResponse().pagesCollection!,
        },
      ],
    },
  });

export const getDashboardDataObject = (): DashboardDataObject => ({
  news: [
    {
      created: '2020-09-08T16:35:28.000Z',
      id: 'news-1',
      shortText: 'Short text of news 1',
      text: '<p>text</p>',
      thumbnail: `${baseUrl}/api/assets/${appName}/thumbnail-uuid1`,
      title: 'News 1',
      type: 'News',
      frequency: 'News Articles',
    },
  ],
  pages: [
    {
      id: 'some-id',
      title: 'Privacy Policy',
      path: '/privacy-policy',
      shortText: 'short text',
      link: 'link',
      linkText: 'linkText',
      text: '<h1>Privacy Policy</h1>',
    },
  ],
});
``;

export const getDashboardResponse = (): DashboardResponse =>
  getDashboardDataObject();
