import {
  EventResponse,
  EventSpeaker,
  EventStatus,
  ListEventResponse,
} from '@asap-hub/model';
import { config, Event, RestEvent } from '@asap-hub/squidex';
import {
  EventContentFragment,
  FetchEventQuery,
  FetchEventsQuery,
} from '../../src/autogenerated-gql/graphql';
import { getGroupResponse, getSquidexGraphqlGroup } from './groups.fixtures';

export const getEventRestResponse = (): Event => ({
  googleId: 'google-event-id',
  title: 'Event Tittle',
  description: 'This event will be good',
  startDate: '2021-02-23T19:32:00Z',
  startDateTimeZone: 'Europe/Lisbon',
  endDate: '2021-02-23T19:32:00Z',
  endDateTimeZone: 'Europe/Lisbon',
  calendar: ['squidex-calendar-id'],
  status: 'Confirmed' as EventStatus,
  tags: [],
  hidden: false,
  meetingLink: 'https://zweem.com',
  hideMeetingLink: false,
});

export const getEventSpeaker = (): EventSpeaker => ({
  team: {
    id: 'team-id-3',
    displayName: 'The team three',
  },
  user: {
    id: 'user-id-3',
    firstName: 'Adam',
    lastName: 'Brown',
    displayName: 'Adam Brown',
  },
  role: 'Lead PI (Core Leadership)',
});

export const getEventResponse = (): EventResponse => ({
  id: 'ec3086d4-aa64-4f30-a0f7-5c5b95ffbcca',
  description: 'This event is awesome',
  lastModifiedDate: '2021-05-14T14:48:46.000Z',
  endDate: '2009-12-24T16:30:54.000Z',
  startDate: '2009-12-24T16:20:14.000Z',
  meetingLink: 'https://zoom.com/room/123',
  hideMeetingLink: false,
  status: 'Confirmed',
  tags: [],
  title: 'Example Event',
  startDateTimeZone: 'UTC',
  endDateTimeZone: 'UTC',
  notes: 'These are the notes from the meeting',
  videoRecording: '<embeded>video</embeded>',
  presentation: '<embeded>presentation</embeded>',
  meetingMaterials: [
    {
      title: 'My additional link',
      url: 'https://link.pt/additional-material',
    },
  ],
  thumbnail: `${config.baseUrl}/api/assets/${config.appName}/uuid-thumbnail-2`,
  calendar: {
    color: '#125A12',
    id: 'c_t92qa82jd702q1fkreoi0hf4hk@group.calendar.google.com',
    name: 'Tech 1 - Sequencing/omics',
  },
  group: getGroupResponse(),
  speakers: [getEventSpeaker()],
});

export const listEventResponse = {
  total: 1,
  items: [getEventResponse()],
};

export const getRestEvent = (): RestEvent => ({
  id: 'squidex-event-id',
  created: '2021-02-23T19:32:00Z',
  lastModified: '2021-02-23T19:32:00Z',
  version: 42,
  data: squidexRestEventData(),
});

export const squidexRestEventData = () => ({
  googleId: { iv: 'google-event-id' },
  title: { iv: 'Event Tittle' },
  description: { iv: 'This event will be good' },
  startDate: { iv: '2021-02-23T19:32:00Z' },
  startDateTimeZone: { iv: 'Europe/Lisbon' },
  endDate: { iv: '2021-02-23T19:32:00Z' },
  endDateTimeZone: { iv: 'Europe/Lisbon' },
  calendar: { iv: ['squidex-calendar-id'] },
  status: { iv: 'Confirmed' as EventStatus },
  tags: { iv: [] },
  hidden: { iv: false },
  meetingLink: { iv: 'https://zweem.com' },
  hideMeetingLink: { iv: false },
});

export const getSquidexGraphqlEvent = () => ({
  id: 'ec3086d4-aa64-4f30-a0f7-5c5b95ffbcca',
  created: '2020-09-23T16:34:26.842Z',
  lastModified: '2021-05-14T14:48:46Z',
  version: 43,
  flatData: squidexGraphqlEventsFlatData(),
});

export const getSquidexGraphqlEventSpeaker = () => ({
  team: [
    {
      id: 'team-id-3',
      flatData: {
        displayName: 'The team three',
      },
    },
  ],
  user: [
    {
      id: 'user-id-3',
      flatData: {
        avatar: [],
        firstName: 'Adam',
        lastName: 'Brown',
        teams: [
          {
            id: [
              {
                id: 'team-id-3',
              },
            ],
            role: 'Lead PI (Core Leadership)',
          },
        ],
      },
    },
  ],
});

const squidexGraphqlEventsFlatData = (): EventContentFragment['flatData'] => ({
  description: 'This event is awesome',
  endDate: '2009-12-24T16:30:54.000Z',
  startDate: '2009-12-24T16:20:14.000Z',
  meetingLink: 'https://zoom.com/room/123',
  hideMeetingLink: false,
  status: 'Confirmed',
  tags: [],
  title: 'Example Event',
  startDateTimeZone: 'UTC',
  endDateTimeZone: 'UTC',
  notesPermanentlyUnavailable: false,
  notes: 'These are the notes from the meeting',
  videoRecordingPermanentlyUnavailable: false,
  videoRecording: '<embeded>video</embeded>',
  presentationPermanentlyUnavailable: false,
  presentation: '<embeded>presentation</embeded>',
  meetingMaterialsPermanentlyUnavailable: false,
  meetingMaterials: [
    {
      title: 'My additional link',
      url: 'https://link.pt/additional-material',
    },
  ],
  thumbnail: [
    {
      id: 'uuid-thumbnail-2',
    },
  ],
  eventLink: 'https://zoom.com/room/123',
  calendar: [
    {
      flatData: {
        googleCalendarId:
          'c_t92qa82jd702q1fkreoi0hf4hk@group.calendar.google.com',
        color: '#125A12' as const,
        name: 'Tech 1 - Sequencing/omics',
      },
      referencingGroupsContents: [getSquidexGraphqlGroup()],
    },
  ],
  speakers: [getSquidexGraphqlEventSpeaker()],
});

export const getSquidexGraphqlEvents = (): ListEventResponse => ({
  items: [getEventResponse()],
  total: 1,
});
export const squidexGraphqlEventResponse = () => ({
  description: 'This event is awesome',
  meetingLink: 'https://zoom.com/room/123',
  endDate: '2009-12-24T16:30:54.000Z',
  startDate: '2009-12-24T16:20:14.000Z',
  status: 'Confirmed',
  tags: [],
  title: 'Example Event',
  calendar: {
    color: '#125A12',
    name: 'Tech 1 - Sequencing/omics',
    id: 'c_t92qa82jd702q1fkreoi0hf4hk@group.calendar.google.com',
  },
});

export const getSquidexEventsGraphqlResponse = (): FetchEventsQuery => ({
  queryEventsContentsWithTotal: {
    items: [getSquidexGraphqlEvent()],
    total: 1,
  },
});

export const getSquidexEventGraphqlResponse = (): FetchEventQuery => ({
  findEventsContent: getSquidexGraphqlEvent(),
});
