import {
  FetchEventsQuery as ContentfulFetchEventsQuery,
  FetchEventsByUserIdQuery,
  FetchEventsByExternalAuthorIdQuery,
  FetchEventsByTeamIdQuery,
  ContentfulWebhookPayload,
} from '@asap-hub/contentful';
import {
  EventCreateDataObject,
  EventDataObject,
  EventEvent,
  EventResponse,
  EventSpeakerUser,
  EventStatus,
  ListEventDataObject,
  ListEventResponse,
  WebhookDetail,
} from '@asap-hub/model';
import {
  RestEvent,
  SquidexWebhookPayload,
  Event as SquidexEvent,
} from '@asap-hub/squidex';
import { EventBridgeEvent } from 'aws-lambda';
import {
  EventContentFragment,
  FetchEventQuery,
  FetchEventsQuery,
} from '../../src/autogenerated-gql/graphql';
import { appName, baseUrl } from '../../src/config';
import { eventUnreadyResponse } from '../../src/data-providers/contentful/event.data-provider';
import { createEventBridgeEventMock } from '../helpers/events';
import { getGroupResponse, getSquidexGraphqlGroup } from './groups.fixtures';
import {
  getSquidexGraphqlWorkingGroup,
  getWorkingGroupResponse,
} from './working-groups.fixtures';

export const getContentfulUserSpeakerTeams = () => ({
  sys: {
    id: 'team-id-3',
  },
  role: 'Lead PI (Core Leadership)',
});

export const getContentfulGraphqlEvent = (): NonNullable<
  NonNullable<ContentfulFetchEventsQuery['eventsCollection']>['items'][number]
> => ({
  sys: {
    id: 'ec3086d4-aa64-4f30-a0f7-5c5b95ffbcca',
    publishedAt: '2021-05-14T14:48:46.000Z',
  },
  description: 'This event is awesome',
  endDate: '2009-12-24T16:30:54.000Z',
  endDateTimeZone: 'UTC',
  startDate: '2009-12-24T16:20:14.000Z',
  startDateTimeZone: 'UTC',
  meetingLink: 'https://zoom.com/room/123',
  hideMeetingLink: false,
  eventLink: 'https://zoom.com/room/123',
  status: 'Confirmed',
  hidden: false,
  tags: [],
  title: 'Example Event',
  notesPermanentlyUnavailable: false,
  notes: {
    json: {
      data: {},
      content: [
        {
          data: {},
          content: [
            {
              data: {},
              marks: [],
              value: 'These are the notes from the meeting',
              nodeType: 'text',
            },
          ],
          nodeType: 'paragraph',
        },
      ],
      nodeType: 'document',
    },
    links: {
      entries: {
        inline: [],
      },
      assets: {
        block: [],
      },
    },
  },
  notesUpdatedAt: '2010-10-01T08:00:04.000Z',
  videoRecordingPermanentlyUnavailable: false,
  videoRecording: {
    json: {
      nodeType: 'document',
      data: {},
      content: [
        {
          nodeType: 'paragraph',
          data: {},
          content: [
            {
              nodeType: 'text',
              value: '',
              marks: [],
              data: {},
            },
            {
              nodeType: 'embedded-entry-inline',
              data: {
                target: {
                  sys: {
                    id: 'video-id',
                    type: 'Link',
                    linkType: 'Entry',
                  },
                },
              },
              content: [],
            },
            {
              nodeType: 'text',
              value: '',
              marks: [],
              data: {},
            },
          ],
        },
      ],
    },
    links: {
      entries: {
        inline: [
          {
            sys: {
              id: 'video-id',
            },
            __typename: 'Media',
            url: 'https://player.vimeo.com/video/493052720',
          },
        ],
      },
      assets: {
        block: [],
      },
    },
  },
  videoRecordingUpdatedAt: '2010-08-01T08:00:04.000Z',
  presentationPermanentlyUnavailable: false,
  presentation: {
    json: {
      nodeType: 'document',
      data: {},
      content: [
        {
          nodeType: 'paragraph',
          data: {},
          content: [
            {
              nodeType: 'text',
              value: '',
              marks: [],
              data: {},
            },
            {
              nodeType: 'embedded-entry-inline',
              data: {
                target: {
                  sys: {
                    id: 'presentation-id',
                    type: 'Link',
                    linkType: 'Entry',
                  },
                },
              },
              content: [],
            },
            {
              nodeType: 'text',
              value: '',
              marks: [],
              data: {},
            },
          ],
        },
      ],
    },
    links: {
      entries: {
        inline: [
          {
            sys: {
              id: 'presentation-id',
            },
            __typename: 'Media',
            url: 'https://drive.google.com/file/d/1euARcFkYJoqj4c_oor_nYIMBDWOfL-3x/preview',
          },
        ],
      },
      assets: {
        block: [],
      },
    },
  },
  presentationUpdatedAt: '2010-09-01T08:00:04.000Z',
  meetingMaterialsPermanentlyUnavailable: false,
  meetingMaterials: [
    {
      title: 'My additional link',
      url: 'https://link.pt/additional-material',
    },
  ],
  calendar: {
    googleCalendarId: 'c_t92qa82jd702q1fkreoi0hf4hk@group.calendar.google.com',
    color: '#125A12' as const,
    name: 'Tech 1 - Sequencing/omics',
  },
  thumbnail: {
    url: 'https://images.ctfassets.net/5v6w5j61tndm/849855829/ac04300efa901ab22278b50d63bfde14/COSA-9900000000079e3c.png',
  },
  speakersCollection: {
    items: [
      {
        team: {
          sys: {
            id: 'team-id-3',
          },
          displayName: 'The team three',
          inactiveSince: '2022-10-24T11:00:00Z',
        },
        user: {
          __typename: 'Users',
          sys: {
            id: 'user-id-3',
          },
          alumniSinceDate: null,
          alumniLocation: 'some alumni location',
          firstName: 'Adam',
          lastName: 'Brown',
          onboarded: true,
          teamsCollection: {
            items: [getContentfulUserSpeakerTeams()],
          },
          avatar: null,
        },
      },
    ],
  },
});

export const getContentfulGraphqlEventsResponse =
  (): ContentfulFetchEventsQuery => ({
    eventsCollection: {
      total: 1,
      items: [getContentfulGraphqlEvent()],
    },
  });

export const getEventsByUserIdGraphqlResponse =
  (): FetchEventsByUserIdQuery => ({
    users: {
      linkedFrom: {
        eventSpeakersCollection: {
          items: [
            {
              linkedFrom: {
                eventsCollection: {
                  total: 1,
                  items: [getContentfulGraphqlEvent()],
                },
              },
            },
          ],
        },
      },
    },
  });

export const getEventsByExternalAuthorIdGraphqlResponse =
  (): FetchEventsByExternalAuthorIdQuery => ({
    externalAuthors: {
      linkedFrom: {
        eventSpeakersCollection: {
          items: [
            {
              linkedFrom: {
                eventsCollection: {
                  total: 1,
                  items: [getContentfulGraphqlEvent()],
                },
              },
            },
          ],
        },
      },
    },
  });

export const getEventsByTeamIdGraphqlResponse =
  (): FetchEventsByTeamIdQuery => ({
    teams: {
      linkedFrom: {
        eventSpeakersCollection: {
          items: [
            {
              linkedFrom: {
                eventsCollection: {
                  total: 1,
                  items: [getContentfulGraphqlEvent()],
                },
              },
            },
          ],
        },
      },
    },
  });

export const getEventSpeakerUser = (): EventSpeakerUser => ({
  team: {
    id: 'team-id-3',
    displayName: 'The team three',
    inactiveSince: '2022-10-24T11:00:00Z',
  },
  user: {
    id: 'user-id-3',
    firstName: 'Adam',
    lastName: 'Brown',
    displayName: 'Adam Brown',
    alumniSinceDate: undefined,
    avatarUrl: undefined,
  },
  role: 'Lead PI (Core Leadership)',
});

export const getContentfulEventDataObject = (): EventDataObject => ({
  ...getEventDataObject(),
  ...eventUnreadyResponse,
  notes: '<p>These are the notes from the meeting</p>',
  presentation:
    '<p><iframe src="https://drive.google.com/file/d/1euARcFkYJoqj4c_oor_nYIMBDWOfL-3x/preview"/></p>',
  videoRecording:
    '<p><iframe src="https://player.vimeo.com/video/493052720"/></p>',
  thumbnail:
    'https://images.ctfassets.net/5v6w5j61tndm/849855829/ac04300efa901ab22278b50d63bfde14/COSA-9900000000079e3c.png',
});

export const getContentfulEventResponse = (): EventResponse =>
  getEventDataObject();

export const getContentfulListEventDataObject = (): ListEventDataObject => ({
  total: 1,
  items: [getContentfulEventDataObject()],
});
export const getContentfulListEventResponse = (): ListEventResponse =>
  getContentfulListEventDataObject();

export const getEventDataObject = (): EventDataObject => ({
  id: 'ec3086d4-aa64-4f30-a0f7-5c5b95ffbcca',
  description: 'This event is awesome',
  lastModifiedDate: '2021-05-14T14:48:46.000Z',
  endDate: '2009-12-24T16:30:54.000Z',
  endDateTimestamp: 1261672254,
  startDate: '2009-12-24T16:20:14.000Z',
  startDateTimestamp: 1261671614,
  meetingLink: 'https://zoom.com/room/123',
  hideMeetingLink: false,
  status: 'Confirmed',
  hidden: false,
  tags: [],
  title: 'Example Event',
  startDateTimeZone: 'UTC',
  endDateTimeZone: 'UTC',
  notes: 'These are the notes from the meeting',
  notesUpdatedAt: '2010-10-01T08:00:04.000Z',
  videoRecording: '<embeded>video</embeded>',
  videoRecordingUpdatedAt: '2010-08-01T08:00:04.000Z',
  presentation: '<embeded>presentation</embeded>',
  presentationUpdatedAt: '2010-09-01T08:00:04.000Z',
  meetingMaterials: [
    {
      title: 'My additional link',
      url: 'https://link.pt/additional-material',
    },
  ],
  thumbnail: `${baseUrl}/api/assets/${appName}/uuid-thumbnail-2`,
  calendar: {
    color: '#125A12',
    id: 'c_t92qa82jd702q1fkreoi0hf4hk@group.calendar.google.com',
    name: 'Tech 1 - Sequencing/omics',
    groups: [],
    workingGroups: [],
  },
  group: getGroupResponse(),
  workingGroup: getWorkingGroupResponse(),
  speakers: [getEventSpeakerUser()],
});

export const getEventResponse = (): EventResponse => getEventDataObject();

export const getListEventDataObject = (): ListEventDataObject => ({
  total: 1,
  items: [getEventDataObject()],
});
export const getListEventResponse = (): ListEventResponse =>
  getListEventDataObject();

export const getRestEvent = (): RestEvent => ({
  id: 'squidex-event-id',
  created: '2021-02-23T19:32:00Z',
  lastModified: '2021-02-23T19:32:00Z',
  version: 42,
  data: getEventInput(),
});

export const getEventInput = () => ({
  googleId: { iv: 'google-event-id' },
  title: { iv: 'Event Tittle' },
  description: { iv: 'This event will be good' },
  startDate: { iv: '2021-02-23T19:32:00Z' },
  startDateTimeZone: { iv: 'Europe/Lisbon' },
  endDate: { iv: '2021-02-23T19:32:00Z' },
  endDateTimeZone: { iv: 'Europe/Lisbon' },
  calendar: { iv: ['squidex-calendar-id'] },
  status: { iv: 'Confirmed' as EventStatus },
  tags: { iv: [] },
  hidden: { iv: false },
  hideMeetingLink: { iv: false },
});

export const getEventCreateDataObject = (): EventCreateDataObject => ({
  googleId: 'google-event-id',
  title: 'Event Tittle',
  description: 'This event will be good',
  startDate: '2021-02-23T19:32:00Z',
  startDateTimeZone: 'Europe/Lisbon',
  endDate: '2021-02-23T19:32:00Z',
  endDateTimeZone: 'Europe/Lisbon',
  calendar: 'squidex-calendar-id',
  status: 'Confirmed' as EventStatus,
  tags: [],
  hidden: false,
  hideMeetingLink: false,
});

export const getSquidexGraphqlEvent = () => ({
  id: 'ec3086d4-aa64-4f30-a0f7-5c5b95ffbcca',
  created: '2020-09-23T16:34:26.842Z',
  lastModified: '2021-05-14T14:48:46Z',
  version: 43,
  flatData: squidexGraphqlEventsFlatData(),
});

export const getSquidexGraphqlEventSpeakerWithUser = (): NonNullable<
  NonNullable<EventContentFragment['flatData']['speakers']>[number]
> => ({
  team: [
    {
      id: 'team-id-3',
      flatData: {
        displayName: 'The team three',
        inactiveSince: '2022-10-24T11:00:00Z',
      },
    },
  ],
  user: [
    {
      __typename: 'Users',
      id: 'user-id-3',
      flatData: {
        alumniSinceDate: null,
        alumniLocation: 'some alumni location',
        avatar: [],
        firstName: 'Adam',
        lastName: 'Brown',
        onboarded: true,
        teams: [
          {
            id: [
              {
                id: 'team-id-3',
              },
            ],
            role: 'Lead PI (Core Leadership)',
          },
        ],
      },
    },
  ],
});

export const getSquidexGraphqlEventSpeakerWithExternalUser = (): NonNullable<
  EventContentFragment['flatData']['speakers']
>[number] => ({
  team: [],
  user: [
    {
      __typename: 'ExternalAuthors',
      id: 'user-id-3',
      flatData: {
        name: 'Adam Brown',
        orcid: 'https://orcid.org/0000-0002-1825-0097',
      },
    },
  ],
});

const squidexGraphqlEventsFlatData = (): EventContentFragment['flatData'] & {
  videoRecordingUpdatedAt: string;
  presentationUpdatedAt: string;
  notesUpdatedAt: string;
} => ({
  description: 'This event is awesome',
  endDate: '2009-12-24T16:30:54.000Z',
  startDate: '2009-12-24T16:20:14.000Z',
  videoRecordingUpdatedAt: '2010-08-01T08:00:04.000Z',
  presentationUpdatedAt: '2010-09-01T08:00:04.000Z',
  notesUpdatedAt: '2010-10-01T08:00:04.000Z',
  meetingLink: 'https://zoom.com/room/123',
  hideMeetingLink: false,
  status: 'Confirmed',
  hidden: false,
  tags: [],
  title: 'Example Event',
  startDateTimeZone: 'UTC',
  endDateTimeZone: 'UTC',
  notesPermanentlyUnavailable: false,
  notes: 'These are the notes from the meeting',
  videoRecordingPermanentlyUnavailable: false,
  videoRecording: '<embeded>video</embeded>',
  presentationPermanentlyUnavailable: false,
  presentation: '<embeded>presentation</embeded>',
  meetingMaterialsPermanentlyUnavailable: false,
  meetingMaterials: [
    {
      title: 'My additional link',
      url: 'https://link.pt/additional-material',
    },
  ],
  thumbnail: [
    {
      id: 'uuid-thumbnail-2',
    },
  ],
  eventLink: 'https://zoom.com/room/123',
  calendar: [
    {
      flatData: {
        googleCalendarId:
          'c_t92qa82jd702q1fkreoi0hf4hk@group.calendar.google.com',
        color: '#125A12' as const,
        name: 'Tech 1 - Sequencing/omics',
      },
      referencingGroupsContents: [getSquidexGraphqlGroup()],
      referencingWorkingGroupsContents: [getSquidexGraphqlWorkingGroup()],
    },
  ],
  speakers: [getSquidexGraphqlEventSpeakerWithUser()],
});

export const getSquidexGraphqlEvents = (): ListEventResponse => ({
  items: [getEventResponse()],
  total: 1,
});
export const squidexGraphqlEventResponse = () => ({
  description: 'This event is awesome',
  meetingLink: 'https://zoom.com/room/123',
  endDate: '2009-12-24T16:30:54.000Z',
  startDate: '2009-12-24T16:20:14.000Z',
  status: 'Confirmed',
  tags: [],
  title: 'Example Event',
  calendar: {
    color: '#125A12',
    name: 'Tech 1 - Sequencing/omics',
    id: 'c_t92qa82jd702q1fkreoi0hf4hk@group.calendar.google.com',
  },
});

export const getSquidexEventsGraphqlResponse = (): FetchEventsQuery => ({
  queryEventsContentsWithTotal: {
    items: [getSquidexGraphqlEvent()],
    total: 1,
  },
});

export const getSquidexEventGraphqlResponse = (): FetchEventQuery => ({
  findEventsContent: getSquidexGraphqlEvent(),
});

export const getEventPayload = (
  id: string,
  type: EventEvent,
): WebhookDetail<SquidexWebhookPayload<SquidexEvent, EventEvent>> => ({
  resourceId: id,
  type,
  timestamp: '2021-10-05T12:49:49Z',
  payload: {
    $type: 'EnrichedContentEvent',
    type: 'Updated',
    id,
    timestamp: '2021-10-05T12:49:49Z',
    data: {
      ...getEventInput(),
    },
    lastModified: '2021-10-05T12:49:49Z',
    created: '2021-10-05T12:49:49Z',
    version: 1,
  },
});

export const getEventSquidexEvent = (
  id: string,
  eventType: EventEvent,
): EventBridgeEvent<
  EventEvent,
  WebhookDetail<SquidexWebhookPayload<SquidexEvent, EventEvent>>
> => createEventBridgeEventMock(getEventPayload(id, eventType), eventType, id);

export const getEventContentfulWebhookDetail = (
  id: string,
): WebhookDetail<ContentfulWebhookPayload<'events'>> => ({
  resourceId: id,
  metadata: {
    tags: [],
  },
  sys: {
    type: 'Entry',
    id: 'fc496d00-053f-44fd-9bac-68dd9d959848',
    space: {
      sys: {
        type: 'Link',
        linkType: 'Space',
        id: '5v6w5j61tndm',
      },
    },
    environment: {
      sys: {
        id: 'crn-3046',
        type: 'Link',
        linkType: 'Environment',
      },
    },
    contentType: {
      sys: {
        type: 'Link',
        linkType: 'ContentType',
        id: 'events',
      },
    },
    createdBy: {
      sys: {
        type: 'Link',
        linkType: 'User',
        id: '2SHvngTJ24kxZGAPDJ8J1y',
      },
    },
    updatedBy: {
      sys: {
        type: 'Link',
        linkType: 'User',
        id: '2SHvngTJ24kxZGAPDJ8J1y',
      },
    },
    revision: 14,
    createdAt: '2023-05-17T13:39:03.250Z',
    updatedAt: '2023-05-18T16:17:36.425Z',
  },
  fields: {
    title: {
      'en-US':
        'Sci 7 - Inflammation & Immune Reg., Presenting Teams: Sulzer, Desjardins, Kordower',
    },
    startDate: {
      'en-US': '2021-04-27T18:00:00Z',
    },
    status: {
      'en-US': 'Confirmed',
    },
    calendar: {
      'en-US': {
        sys: {
          type: 'Link',
          linkType: 'Entry',
          id: '7dca2b08-828b-44ee-9e57-7675ff3f6693',
        },
      },
    },
    hidden: {
      'en-US': false,
    },
    meetingLink: {
      'en-US':
        'https://zoom.us/j/96449436221?pwd=MXpTbVJvdzRuMkhZM2YyMWxubStJdz09',
    },
    hideMeetingLink: {
      'en-US': false,
    },
    thumbnail: {
      'en-US': null,
    },
    notesPermanentlyUnavailable: {
      'en-US': null,
    },
    notes: {
      'en-US': {
        data: {},
        content: [
          {
            data: {},
            content: [
              {
                data: {},
                marks: [],
                value: 'material!',
                nodeType: 'text',
              },
            ],
            nodeType: 'paragraph',
          },
        ],
        nodeType: 'document',
      },
    },
    notesUpdatedAt: {
      'en-US': null,
    },
    videoRecordingPermanentlyUnavailable: {
      'en-US': null,
    },
    videoRecording: {
      'en-US': null,
    },
    videoRecordingUpdatedAt: {
      'en-US': null,
    },
    presentationPermanentlyUnavailable: {
      'en-US': null,
    },
    presentation: {
      'en-US': null,
    },
    presentationUpdatedAt: {
      'en-US': null,
    },
    meetingMaterials: {
      'en-US': [],
    },
    meetingMaterialsPermanentlyUnavailable: {
      'en-US': null,
    },
    description: {
      'en-US':
        '<b>Chair:</b> Xiqun Chen<br><b>PM: </b>Pranay Srivastava (email&nbsp;<a href="mailto:psrivastava3@mgh.harvard.edu">psrivastava3@mgh.harvard.edu</a> for any enquiries)<br>Anyone from the ASAP Network is welcome to attend<br>&nbsp;  <br>Inflammation and Immune Regulation ASAP CRN Subgroup Meeting<br>Presenting Teams: Sulzer, Desjardins, Kordower<br><br>Agenda to follow',
    },
    startDateTimeZone: {
      'en-US': 'America/New_York',
    },
    endDate: {
      'en-US': '2021-04-27T19:30:00Z',
    },
    endDateTimeZone: {
      'en-US': 'America/New_York',
    },
    eventLink: {
      'en-US': null,
    },
    googleId: {
      'en-US': '76fmieuhgnm0c15k327uvvi4tt',
    },
  },
});

export const getEventContentfulEvent = (
  id: string,
  eventType: EventEvent,
): EventBridgeEvent<
  EventEvent,
  WebhookDetail<ContentfulWebhookPayload<'events'>>
> =>
  createEventBridgeEventMock(
    getEventContentfulWebhookDetail(id),
    eventType,
    id,
  );
