import {
  EventHappeningNowReminder,
  EventHappeningTodayReminder,
  EventNotesReminder,
  ListReminderDataObject,
  ListReminderResponse,
  PresentationUpdatedReminder,
  PublishMaterialReminder,
  ReminderEventResponse,
  ReminderResponse,
  ResearchOutputDraftReminder,
  ResearchOutputInReviewReminder,
  ResearchOutputPublishedReminder,
  SharePresentationReminder,
  UploadPresentationReminder,
  VideoEventReminder,
} from '@asap-hub/model';
import { FetchReminderDataQuery } from '../../src/autogenerated-gql/graphql';
import {
  getEventResponse,
  getSquidexGraphqlEvent,
  getSquidexGraphqlEventSpeakerWithUser,
} from './events.fixtures';
import {
  getResearchOutputDataObject,
  getSquidexGraphqlResearchOutput,
} from './research-output.fixtures';
import { getSquidexGraphqlTeam } from './teams.fixtures';

export const getResearchOutputPublishedReminder =
  (): ResearchOutputPublishedReminder => {
    const researchOutputDataObject = getResearchOutputDataObject();
    return {
      id: 'research-output-published-ec3086d4-aa64-4f30-a0f7-5c5b95ffbcca',
      entity: 'Research Output',
      type: 'Published',
      data: {
        researchOutputId: researchOutputDataObject.id,
        documentType: researchOutputDataObject.documentType,
        title: researchOutputDataObject.title,
        addedDate: researchOutputDataObject.addedDate,
      },
    };
  };

export const getResearchOutputDraftTeamReminder =
  (): ResearchOutputDraftReminder => {
    const researchOutputDataObject = getResearchOutputDataObject();
    return {
      id: 'research-output-draft-ec3086d4-aa64-4f30-a0f7-5c5b95ffbcca',
      entity: 'Research Output',
      type: 'Draft',
      data: {
        researchOutputId: researchOutputDataObject.id,
        title: researchOutputDataObject.title,
        addedDate: researchOutputDataObject.created,
        associationName: researchOutputDataObject.teams[0]?.displayName || '',
        associationType: 'team',
        createdBy: 'Tom Hardy',
      },
    };
  };

export const getResearchOutputDraftWorkingGroupReminder =
  (): ResearchOutputDraftReminder => {
    const researchOutputDataObject = getResearchOutputDataObject();
    return {
      id: 'research-output-draft-ec3086d4-aa64-4f30-a0f7-5c5b95ffbcca',
      entity: 'Research Output',
      type: 'Draft',
      data: {
        researchOutputId: researchOutputDataObject.id,
        title: researchOutputDataObject.title,
        addedDate: researchOutputDataObject.created,
        associationName: 'Working Group 1',
        associationType: 'working group',
        createdBy: 'Tom Hardy',
      },
    };
  };

export const getResearchOutputInReviewTeamReminder =
  (): ResearchOutputInReviewReminder => {
    const researchOutputDataObject = getResearchOutputDataObject();
    return {
      id: 'research-output-in-review-ec3086d4-aa64-4f30-a0f7-5c5b95ffbcca',
      entity: 'Research Output',
      type: 'In Review',
      data: {
        researchOutputId: researchOutputDataObject.id,
        title: researchOutputDataObject.title,
        addedDate: researchOutputDataObject.created,
        associationName: researchOutputDataObject.teams[0]?.displayName || '',
        associationType: 'team',
        documentType: researchOutputDataObject.documentType,
        reviewRequestedBy: 'Tom Hardy',
      },
    };
  };

export const getResearchOutputInReviewWorkingGroupReminder =
  (): ResearchOutputInReviewReminder => {
    const researchOutputDataObject = getResearchOutputDataObject();
    return {
      id: 'research-output-in-review-ec3086d4-aa64-4f30-a0f7-5c5b95ffbcca',
      entity: 'Research Output',
      type: 'In Review',
      data: {
        researchOutputId: researchOutputDataObject.id,
        title: researchOutputDataObject.title,
        addedDate: researchOutputDataObject.created,
        associationName: 'Working Group 1',
        associationType: 'working group',
        documentType: researchOutputDataObject.documentType,
        reviewRequestedBy: 'Tom Hardy',
      },
    };
  };

export const getEventHappeningTodayReminder =
  (): EventHappeningTodayReminder => {
    const eventResponse = getEventResponse();
    return {
      id: `event-happening-today-${eventResponse.id}`,
      entity: 'Event',
      type: 'Happening Today',
      data: {
        eventId: eventResponse.id,
        startDate: eventResponse.startDate,
        title: eventResponse.title,
      },
    };
  };

export const getEventHappeningNowReminder = (): EventHappeningNowReminder => {
  const eventResponse = getEventResponse();
  return {
    id: `event-happening-now-${eventResponse.id}`,
    entity: 'Event',
    type: 'Happening Now',
    data: {
      eventId: eventResponse.id,
      startDate: eventResponse.startDate,
      endDate: eventResponse.endDate,
      title: eventResponse.title,
    },
  };
};

export const getSharePresentationReminder = (): SharePresentationReminder => {
  const eventResponse = getEventResponse();
  return {
    id: `share-presentation-${eventResponse.id}`,
    entity: 'Event',
    type: 'Share Presentation',
    data: {
      eventId: eventResponse.id,
      title: eventResponse.title,
      endDate: eventResponse.endDate,
    },
  };
};

export const getUploadPresentationReminder = (): UploadPresentationReminder => {
  const eventResponse = getEventResponse();
  return {
    id: `upload-presentation-${eventResponse.id}`,
    entity: 'Event',
    type: 'Upload Presentation',
    data: {
      eventId: eventResponse.id,
      title: eventResponse.title,
      endDate: eventResponse.endDate,
    },
  };
};

export const getPublishMaterialReminder = (): PublishMaterialReminder => {
  const eventResponse = getEventResponse();
  return {
    id: `publish-material-${eventResponse.id}`,
    entity: 'Event',
    type: 'Publish Material',
    data: {
      eventId: eventResponse.id,
      title: eventResponse.title,
      endDate: eventResponse.endDate,
    },
  };
};

export const getVideoEventUpdatedReminder = (): VideoEventReminder => {
  const eventResponse = getEventResponse() as ReminderEventResponse;
  eventResponse.videoRecordingUpdatedAt = '2010-08-01T08:00:04.000Z';

  return {
    id: `video-event-updated-${eventResponse.id}`,
    entity: 'Event',
    type: 'Video Updated',
    data: {
      eventId: eventResponse.id,
      title: eventResponse.title,
      videoRecordingUpdatedAt: eventResponse.videoRecordingUpdatedAt,
    },
  };
};

export const getPresentationUpdatedReminder =
  (): PresentationUpdatedReminder => {
    const eventResponse = getEventResponse() as ReminderEventResponse;
    eventResponse.presentationUpdatedAt = '2010-08-01T08:00:04.000Z';

    return {
      id: `presentation-event-updated-${eventResponse.id}`,
      entity: 'Event',
      type: 'Presentation Updated',
      data: {
        eventId: eventResponse.id,
        title: eventResponse.title,
        presentationUpdatedAt: eventResponse.presentationUpdatedAt,
      },
    };
  };

export const getNotesUpdatedReminder = (): EventNotesReminder => {
  const eventResponse = getEventResponse() as ReminderEventResponse;
  eventResponse.notesUpdatedAt = '2010-08-01T08:00:04.000Z';

  return {
    id: `notes-event-updated-${eventResponse.id}`,
    entity: 'Event',
    type: 'Notes Updated',
    data: {
      eventId: eventResponse.id,
      title: eventResponse.title,
      notesUpdatedAt: eventResponse.notesUpdatedAt,
    },
  };
};

export const getListReminderDataObject = (): ListReminderDataObject => ({
  total: 1,
  items: [getResearchOutputPublishedReminder()],
});

export const getReminderResponse = (): ReminderResponse => {
  return {
    id: 'research-output-published-ec3086d4-aa64-4f30-a0f7-5c5b95ffbcca',
    description:
      'Test Proposal 1234 Bioinformatics from your ASAP Team is now published on the Hub. If there are errors, please let your PM know.',
    entity: 'Research Output',
    href: '/shared-research/ec3086d4-aa64-4f30-a0f7-5c5b95ffbcca',
  };
};

export const getListReminderResponse = (): ListReminderResponse => ({
  total: 1,
  items: [getReminderResponse()],
});

export const getReferencingWorkingGroupsContents = () => {
  return {
    id: 'wg-id-1',
    flatData: {
      complete: true,
      leaders: [
        {
          role: 'Project Manager',
          inactiveSinceDate: null,
          user: [
            {
              id: '5678',
            },
          ],
        },
      ],
    },
  };
};

export const getSquidexRemindersGraphqlResponse =
  (): FetchReminderDataQuery => ({
    findUsersContent: {
      referencingWorkingGroupsContents: [getReferencingWorkingGroupsContents()],
      flatData: {
        role: 'Grantee',
        teams: [
          {
            id: [{ id: getSquidexGraphqlTeam({}).id }],
            role: 'Project Manager',
          },
        ],
      },
    },
    draftResearchOutputs: [getSquidexReminderReseachOutputsDraftTeamContents()],
    queryResearchOutputsContents: [getSquidexReminderReseachOutputsContents()],
    queryEventsContents: [getSquidexReminderEventsContents()],
    inReviewResearchOutputs: [
      getSquidexReminderReseachOutputsInReviewTeamContents(),
    ],
  });

export const getSquidexReminderReseachOutputsContents = (): NonNullable<
  FetchReminderDataQuery['queryResearchOutputsContents']
>[number] => {
  const researchOutput = getSquidexGraphqlResearchOutput();

  return {
    id: researchOutput.id,
    created: '2021-10-24T11:00:00Z',
    status: 'Published',
    flatData: {
      addedDate: researchOutput.flatData.addedDate,
      documentType: researchOutput.flatData.documentType,
      title: researchOutput.flatData.title,
      teams: [{ id: researchOutput.flatData.teams![0]!.id }],
      workingGroups: [{ id: 'wg-id-1' }],
    },
  };
};
export const getSquidexReminderReseachOutputsDraftTeamContents =
  (): NonNullable<FetchReminderDataQuery['draftResearchOutputs']>[number] => {
    const researchOutput = getSquidexGraphqlResearchOutput();

    return {
      id: researchOutput.id,
      created: researchOutput.created,
      status: 'Draft',
      flatData: {
        documentType: researchOutput.flatData.documentType,
        title: researchOutput.flatData.title,
        createdBy: [
          {
            id: 'user-id-1',
            flatData: { firstName: 'Tom', lastName: 'Hardy' },
          },
        ],
        teams: [
          {
            id: researchOutput.flatData.teams![0]!.id,
            flatData: {
              displayName:
                researchOutput.flatData.teams![0]!.flatData.displayName,
            },
          },
        ],
        workingGroups: [],
      },
    };
  };
export const getSquidexReminderReseachOutputsInReviewTeamContents =
  (): NonNullable<
    FetchReminderDataQuery['inReviewResearchOutputs']
  >[number] => {
    const researchOutput = getSquidexGraphqlResearchOutput();

    return {
      id: researchOutput.id,
      created: researchOutput.created,
      status: 'Draft',
      flatData: {
        reviewRequestedBy: [
          {
            id: 'user-id-1',
            flatData: { firstName: 'Tom', lastName: 'Hardy' },
          },
        ],
        documentType: researchOutput.flatData.documentType,
        title: researchOutput.flatData.title,
        createdBy: [
          {
            id: 'user-id-1',
            flatData: { firstName: 'Tom', lastName: 'Hardy' },
          },
        ],
        teams: [
          {
            id: researchOutput.flatData.teams![0]!.id,
            flatData: {
              displayName:
                researchOutput.flatData.teams![0]!.flatData.displayName,
            },
          },
        ],
        workingGroups: [],
      },
    };
  };
export const getSquidexReminderReseachOutputsDraftWorkingGroupContents =
  (): NonNullable<FetchReminderDataQuery['draftResearchOutputs']>[number] => {
    const researchOutput = getSquidexGraphqlResearchOutput();

    return {
      id: researchOutput.id,
      created: researchOutput.created,
      status: 'Draft',
      flatData: {
        documentType: researchOutput.flatData.documentType,
        title: researchOutput.flatData.title,
        createdBy: [
          {
            id: 'user-id-1',
            flatData: { firstName: 'Tom', lastName: 'Hardy' },
          },
        ],
        teams: [
          {
            id: researchOutput.flatData.teams![0]!.id,
            flatData: {
              displayName:
                researchOutput.flatData.teams![0]!.flatData.displayName,
            },
          },
        ],
        workingGroups: [
          {
            id: 'wg-id-1',
            flatData: {
              title: 'Working Group 1',
            },
          },
        ],
      },
    };
  };

export const getSquidexReminderEventsContents = (): NonNullable<
  FetchReminderDataQuery['queryEventsContents']
>[number] => {
  const event = getSquidexGraphqlEvent();

  const speaker = {
    ...getSquidexGraphqlEventSpeakerWithUser(),
    team: [
      {
        id: 'team-id-3',
        flatData: {
          displayName: 'The team three',
          inactiveSince: '2022-10-24T11:00:00Z',
        },
        referencingUsersContents: [],
      },
    ],
  };
  return {
    id: event.id,
    flatData: {
      startDate: event.flatData.startDate,
      endDate: event.flatData.endDate,
      title: event.flatData.title,
      speakers: [speaker],
      videoRecordingUpdatedAt: event.flatData.videoRecordingUpdatedAt,
      presentationUpdatedAt: event.flatData.presentationUpdatedAt,
      notesUpdatedAt: event.flatData.notesUpdatedAt,
    },
  };
};
