import { TutorialsDataObject, TutorialsResponse } from '@asap-hub/model';
import { FetchTutorialsQuery } from '../../src/autogenerated-gql/graphql';
import { appName, baseUrl } from '../../src/config';

export const getTutorialResponse = (): TutorialsResponse =>
  getTutorialsDataObject();

export const getTutorialsDataObject = (): TutorialsDataObject => ({
  id: 'tutorial-1',
  title: 'Tutorial 1',
  shortText: 'Short text of tutorial 1',
  text: '<p>text</p>',
  link: 'https://parkinsonsroadmap.org/#',
  linkText: 'ASAP',
  thumbnail: `${baseUrl}/api/assets/${appName}/thumbnail-uuid1`,
  created: '2020-09-08T16:35:28.000Z',
});

export const getSquidexGraphqlTutorial = (): NonNullable<
  FetchTutorialsQuery['findTutorialsContent']
> => {
  return {
    id: 'tutorial-1',
    created: '2020-09-08T16:35:28.000Z',
    flatData: {
      title: 'Tutorial 1',
      shortText: 'Short text of tutorial 1',
      text: '<p>text</p>',
      link: 'https://parkinsonsroadmap.org/#',
      linkText: 'ASAP',
      thumbnail: [
        {
          id: 'thumbnail-uuid1',
        },
      ],
    },
  };
};

export const getSquidexTeamGraphqlResponse = (): FetchTutorialsQuery => ({
  findTutorialsContent: getSquidexGraphqlTutorial(),
});
