import {
  WorkingGroupDataObject,
  WorkingGroupListDataObject,
  WorkingGroupResponse,
} from '@asap-hub/model';
import {
  FetchWorkingGroupQuery,
  FetchWorkingGroupsQuery,
} from '../../src/autogenerated-gql/graphql';

export const getListWorkingGroupsDataObject =
  (): WorkingGroupListDataObject => ({
    total: 2,
    items: [
      getWorkingGroupDataObject(),
      {
        ...getWorkingGroupDataObject(),
        id: '124',
        title: 'Working Group Title 2',
        description: 'Second working gorup description',
        deliverables: [],
        lastModifiedDate: '2021-01-01T00:00:00.000Z',
        externalLink: 'https://www.example.com',
        externalLinkText: 'External Link Text 2',
        complete: true,
      },
    ],
  });

export const getWorkingGroupDataObject = (): WorkingGroupDataObject => ({
  id: '123',
  title: 'Working Group Title',
  description: 'Working Group Description',
  deliverables: [],
  members: [],
  complete: false,
  lastModifiedDate: '2021-01-01T00:00:00.000Z',
  externalLink: 'https://example.com',
  externalLinkText: 'External Link Text',
});

export const getWorkingGroupResponse = (): WorkingGroupResponse =>
  getWorkingGroupDataObject();

export const getSquidexWorkingGroupGraphqlResponse =
  (): FetchWorkingGroupQuery => ({
    findWorkingGroupsContent: getSquidexGraphqlWorkingGroup(),
  });

export const getSquidexWorkingGroupsGraphqlResponse =
  (): FetchWorkingGroupsQuery => ({
    queryWorkingGroupsContentsWithTotal: {
      total: 1,
      items: [
        {
          id: '123',
          lastModified: '2021-01-01T00:00:00.000Z',
          flatData: {
            title: 'Working Group Title',
            description: 'Working Group Description',
            externalLink: 'https://example.com',
            externalLinkText: 'External Link Text',
            deliverables: [],
          },
        },
      ],
    },
  });

export const getSquidexGraphqlWorkingGroup =
  (): FetchWorkingGroupQuery['findWorkingGroupsContent'] => ({
    id: '123',
    lastModified: '2021-01-01T00:00:00.000Z',
    flatData: {
      title: 'Working Group Title',
      description: 'Working Group Description',
      externalLink: 'https://example.com',
      externalLinkText: 'External Link Text',
      deliverables: [],
    },
  });
