import * as components from '@asap-hub/react-components';

export default { title: 'Atoms / Icons' };

export const Alert = () => <components.AlertIcon />;
export const Calendar = () => components.calendarIcon;
export const ChevronCircleDown = () => components.chevronCircleDownIcon;
export const ChevronCircleLeft = () => components.chevronCircleLeftIcon;
export const ChevronCircleUp = () => components.chevronCircleUpIcon;
export const ChevronDown = () => components.chevronDownIcon;
export const ChevronUp = () => components.chevronUpIcon;
export const Clock = () => components.clockIcon;
export const Cross = () => components.crossIcon;
export const Discover = () => components.discoverIcon;
export const Docs = () => components.docsIcon;
export const DropdownChevron = () => components.dropdownChevronIcon;
export const Edit = () => components.editIcon;
export const EventPlaceholder = () => components.eventPlaceholderIcon;
export const ExternalLink = () => components.externalLinkIcon;
export const Feedback = () => components.feedbackIcon;
export const Filter = () => components.filterIcon;
export const FirstPage = () => components.firstPageIcon;
export const Github = () => components.githubIcon;
export const Globe = () => components.globeIcon;
export const Google = () => components.googleIcon;
export const GoogleCalendar = () => components.googleCalendarIcon;
export const GoogleDrive = () => components.googleDriveIcon;
export const GoogleScholar = () => components.googleScholarIcon;
export const GoogleSigninLightNormal = () =>
  components.googleSigninLightNormalIcon;
export const Groups = () => components.groupsIcon;
export const HidePassword = () => components.hidePasswordIcon;
export const InfoCircle = () => components.infoCircleIcon;
export const Info = () => components.infoIcon;
export const Lab = () => components.labIcon;
export const LastPage = () => components.lastPageIcon;
export const Link = () => components.linkIcon;
export const LinkedIn = () => components.linkedInIcon;
export const ListView = () => components.listViewIcon;
export const Location = () => components.locationIcon;
export const Logout = () => components.logoutIcon;
export const Menu = () => components.menuIcon;
export const Network = () => components.networkIcon;
export const News = () => components.newsIcon;
export const NewsEventPlaceholder = () => components.newsEventPlaceholderIcon;
export const NewsPlaceholder = () => components.newsPlaceholder;
export const NextPage = () => components.nextPageIcon;
export const Orcid = () => components.orcidIcon;
export const OrcidSocial = () => components.orcidSocialIcon;
export const Outlook = () => components.outlookIcon;
export const Padlock = () => components.padlockIcon;
export const PaperClip = () => components.paperClipIcon;
export const Placeholder = () => components.placeholderIcon;
export const Plus = () => components.plusIcon;
export const PreviousPage = () => components.previousPageIcon;
export const Protocols = () => components.protocolsIcon;
export const ResearchGate = () => components.researchGateIcon;
export const ResearcherId = () => components.researcherIdIcon;
export const Search = () => components.searchIcon;
export const Settings = () => components.settingsIcon;
export const SharedResearch = () => components.libraryIcon;
export const ShowPassword = () => components.showPasswordIcon;
export const Slack = () => components.slackIcon;
export const SystemCalendar = () => components.systemCalendar;
export const TeamMembers = () => components.teamIcon;
export const Tick = () => components.tickIcon;
export const TrainingPlaceholderIcon = () => components.trainingPlaceholderIcon;
export const Twitter = () => components.twitterIcon;
export const Upload = () => components.uploadIcon;
export const User = () => components.userIcon;
export const UserPlaceholder = () => components.userPlaceholderIcon;
export const ValidTick = () => components.validTickIcon;
export const VerticalDivider = () => components.verticalDividerIcon;
export const Warning = () => components.warningIcon;
