name: 'Algolia Create Index'
description: 'Create Algolia Index'
inputs:
  algolia-api-key-name:
    description: 'SSM Algolia api key name'
    required: true
  algolia-app-id-name:
    description: 'SSM Algolia app id name'
    required: true
  algolia-index:
    description: 'Algolia Index'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-default-region:
    description: 'AWS Region'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  algolia-backup-bucket-name:
    description: 'Algolia Backup Bucket Name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Get Algolia Keys
      id: algolia-keys
      uses: ./.github/actions/algolia-keys
      with:
        algolia-app-id-name: ${{ inputs.algolia-app-id-name }}
        algolia-api-key-name: ${{ inputs.algolia-api-key-name }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-default-region: ${{ inputs.aws-default-region }}
    - name: Get the latest backup directory name
      shell: bash
      run: echo "MOST_RECENT_BACKUP_DIR=$(aws s3api list-objects-v2 --bucket $BUCKET_NAME --query 'sort_by(Contents, &LastModified)[-1].Key' --output=text | cut -d'/' -f 1)" >> $GITHUB_ENV
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-default-region }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        BUCKET_NAME: ${{ inputs.algolia-backup-bucket-name }}
    - name: Download the files and restore the index
      shell: bash
      run: |
        aws s3 cp s3://$BUCKET_NAME/$MOST_RECENT_BACKUP_DIR $MOST_RECENT_BACKUP_DIR --recursive
        export ALGOLIA_BACKUP=$(readlink -f $MOST_RECENT_BACKUP_DIR)
        yarn workspace @asap-hub/crn-server run algolia import -s $ALGOLIA_BACKUP -a $ALGOLIA_APP_ID -k $ALGOLIA_API_KEY -n $ALGOLIA_INDEX
      env:
        ALGOLIA_API_KEY: ${{ steps.algolia-keys.outputs.algolia-api-key }}
        ALGOLIA_APP_ID: ${{ steps.algolia-keys.outputs.algolia-app-id }}
        ALGOLIA_INDEX: ${{ inputs.algolia-index }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-default-region }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        BUCKET_NAME: ${{ inputs.algolia-backup-bucket-name }}
