name: Teardown environment
description: Teardown a PR environment
inputs:
  prNumber:
    required: true
    description: Choose which PR number to destroy
  AWS_ACCESS_KEY_ID:
    required: true
    description: The AWS access key
  AWS_SECRET_ACCESS_KEY:
    required: true
    description: The AWS secret
  AWS_ACM_CETRIFICATE_ARN:
    required: true
    description: The AWS ACM Certificate
  AWS_REGION:
    required: true
    description: The AWS default region
  SQUIDEX_CLIENT_ID:
    required: true
    description: The Squidex client id
  SQUIDEX_CLIENT_SECRET:
    required: true
    description: The Squidex client secret
runs:
  using: composite
  steps:
    - name: Remove CF Stack
      if: ${{ inputs.prNumber != 'production' && inputs.prNumber != 'dev' }}
      run: yarn sls remove --verbose
      shell: bash
      env:
        SLS_STAGE: ${{ inputs.prNumber }}
        NODE_ENV: 'production'
        ASAP_HOSTNAME: 'hub.asap.science'
        ASAP_API_URL: 'https://api-${{ inputs.prNumber }}.hub.asap.science'
        ASAP_APP_URL: 'https://${{ inputs.prNumber }}.hub.asap.science'
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_ACM_CERTIFICATE_ARN: ${{ inputs.AWS_ACM_CERTIFICATE_ARN }}
        AWS_REGION: ${{ inputs.AWS_REGION }}
    - name: Remove GitLab CF Stack
      env:
        SLS_STAGE: ${{ inputs.prNumber }}-gitlab
      if: ${{ env.SLS_STAGE != 'production' && env.SLS_STAGE != 'dev' }}
      shell: bash
      run: yarn sls remove --verbose
    - name: Delete PR Squidex App
      run: python ci/integration/scripts/delete-app.py
      shell: bash
      env:
        SQUIDEX_APP_NAME: ${{ inputs.prNumber }}
        SQUIDEX_CLIENT_ID: ${{ inputs.SQUIDEX_CLIENT_ID }}
        SQUIDEX_CLIENT_SECRET: ${{ inputs.SQUIDEX_CLIENT_SECRET }}
    - name: Delete PR Squidex App created by gitlab
      env:
        SQUIDEX_APP_NAME: ${{ inputs.prNumber }}-gitlab
      shell: bash
      run: python ci/integration/scripts/delete-app.py
