import { RestEvent } from '@asap-hub/squidex';
import {
  getGroupResponse,
  getSquidexGraphqlGroup,
} from '../fixtures/groups.fixtures';
import {
  FetchEventQuery,
  FetchEventsQuery,
} from '../../src/autogenerated-gql/graphql';
import { EventResponse, ListEventResponse } from '@asap-hub/model';

export const eventResponse: EventResponse = {
  id: 'ec3086d4-aa64-4f30-a0f7-5c5b95ffbcca',
  description: 'This event is awesome',
  lastModifiedDate: '2021-05-14T14:48:46.000Z',
  endDate: '2009-12-24T16:30:54.000Z',
  startDate: '2009-12-24T16:20:14.000Z',
  meetingLink: 'https://zoom.com/room/123',
  status: 'Confirmed',
  tags: [],
  title: 'Example Event',
  startDateTimeZone: 'UTC',
  endDateTimeZone: 'UTC',
  notes: 'These are the notes from the meeting',
  videoRecording: '<embeded>video</embeded>',
  presentation: '<embeded>presentation</embeded>',
  meetingMaterials: [
    {
      title: 'My additional link',
      url: 'https://link.pt/additional-material',
    },
  ],
  thumbnail:
    'https://cloud.squidex.io/api/assets/asap-hub-dev/uuid-thumbnail-2',
  calendar: {
    color: '#125A12',
    id: 'c_t92qa82jd702q1fkreoi0hf4hk@group.calendar.google.com',
    name: 'Tech 1 - Sequencing/omics',
  },
  group: getGroupResponse(),
};

export const listEventResponse = {
  total: 1,
  items: [eventResponse],
};

export const getRestEvent = (): RestEvent => ({
  id: 'squidex-event-id',
  created: '2021-02-23T19:32:00Z',
  lastModified: '2021-02-23T19:32:00Z',
  version: 42,
  data: {
    googleId: { iv: 'google-event-id' },
    title: { iv: 'Event Tittle' },
    description: { iv: 'This event will be good' },
    startDate: { iv: '2009-12-24T16:20:14.000Z' },
    startDateTimeZone: { iv: 'Europe/Lisbon' },
    endDate: { iv: '2009-12-24T16:30:54.000Z' },
    endDateTimeZone: { iv: 'Europe/Lisbon' },
    calendar: { iv: ['squidex-calendar-id'] },
    status: { iv: 'Confirmed' },
    tags: { iv: [] },
    meetingLink: { iv: 'https://meetings.com' },
    hidden: { iv: false },
  },
});
export const getSquidexGraphqlEvent = () => ({
  id: 'ec3086d4-aa64-4f30-a0f7-5c5b95ffbcca',
  created: '2020-09-23T16:34:26.842Z',
  lastModified: '2021-05-14T14:48:46Z',
  version: 43,
  flatData: squidexGraphqlEventsFlatData(),
});

const squidexGraphqlEventsFlatData = () => ({
  description: 'This event is awesome',
  endDate: '2009-12-24T16:30:54.000Z',
  startDate: '2009-12-24T16:20:14.000Z',
  meetingLink: 'https://zoom.com/room/123',
  status: 'Confirmed',
  tags: [],
  title: 'Example Event',
  startDateTimeZone: 'UTC',
  endDateTimeZone: 'UTC',
  notesPermanentlyUnavailable: false,
  notes: 'These are the notes from the meeting',
  videoRecordingPermanentlyUnavailable: false,
  videoRecording: '<embeded>video</embeded>',
  presentationPermanentlyUnavailable: false,
  presentation: '<embeded>presentation</embeded>',
  meetingMaterialsPermanentlyUnavailable: false,
  meetingMaterials: [
    {
      title: 'My additional link',
      url: 'https://link.pt/additional-material',
    },
  ],
  thumbnail: [
    {
      id: 'uuid-thumbnail-2',
    },
  ],
  eventLink: 'https://zoom.com/room/123',
  calendar: [
    {
      flatData: {
        googleCalendarId:
          'c_t92qa82jd702q1fkreoi0hf4hk@group.calendar.google.com',
        color: '#125A12' as const,
        name: 'Tech 1 - Sequencing/omics',
      },
      referencingGroupsContents: [getSquidexGraphqlGroup()],
    },
  ],
});

export const getSquidexGraphqlEvents = (): ListEventResponse => ({
  items: [eventResponse],
  total: 1,
});

export const squidexGraphqlEventResponse = () => ({
  description: 'This event is awesome',
  meetingLink: 'https://zoom.com/room/123',
  endDate: '2009-12-24T16:30:54.000Z',
  startDate: '2009-12-24T16:20:14.000Z',
  status: 'Confirmed',
  tags: [],
  title: 'Example Event',
  calendar: {
    color: '#125A12',
    name: 'Tech 1 - Sequencing/omics',
    id: 'c_t92qa82jd702q1fkreoi0hf4hk@group.calendar.google.com',
  },
});

export const getSquidexEventsGraphqlResponse = (): FetchEventsQuery => ({
  queryEventsContentsWithTotal: {
    items: [getSquidexGraphqlEvent()],
    total: 1,
  },
});

export const getSquidexEventGraphqlResponse = (): FetchEventQuery => ({
  findEventsContent: getSquidexGraphqlEvent(),
});
