import { ManuscriptVersionExport } from '@asap-hub/model';

export const mapToSheetRow = (
  manuscriptVersion: ManuscriptVersionExport,
): string[] => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const safe = (val: any) => (val ?? '').toString();

  return [
    safe(manuscriptVersion.id),
    safe(manuscriptVersion.title),
    safe(manuscriptVersion.manuscriptId),
    safe(manuscriptVersion.url),
    safe(manuscriptVersion.type),
    safe(manuscriptVersion.lifecycle),
    safe(manuscriptVersion.preprintDoi),
    safe(manuscriptVersion.publicationDoi),
    safe(manuscriptVersion.otherDetails),
    safe(manuscriptVersion.manuscriptFile),
    safe(manuscriptVersion.keyResourceTable),
    safe(manuscriptVersion.additionalFiles),
    safe(manuscriptVersion.description),
    safe(manuscriptVersion.shortDescription),
    safe(manuscriptVersion.mainProject),
    safe(manuscriptVersion.teams),
    safe(manuscriptVersion.firstAuthors),
    safe(manuscriptVersion.labs),
    safe(manuscriptVersion.correspondingAuthor),
    safe(manuscriptVersion.additionalAuthors),
    safe(manuscriptVersion.status),
    safe(manuscriptVersion.acknowledgedGrantNumber),
    safe(manuscriptVersion.acknowledgedGrantNumberDetails),
    safe(manuscriptVersion.asapAffiliationIncluded),
    safe(manuscriptVersion.asapAffiliationIncludedDetails),
    safe(manuscriptVersion.availabilityStatement),
    safe(manuscriptVersion.availabilityStatementDetails),
    safe(manuscriptVersion.codeDeposited),
    safe(manuscriptVersion.codeDepositedDetails),
    safe(manuscriptVersion.datasetsDeposited),
    safe(manuscriptVersion.datasetsDepositedDetails),
    safe(manuscriptVersion.labMaterialsRegistered),
    safe(manuscriptVersion.labMaterialsRegisteredDetails),
    safe(manuscriptVersion.protocolsDeposited),
    safe(manuscriptVersion.protocolsDepositedDetails),
    safe(manuscriptVersion.manuscriptLicense),
    safe(manuscriptVersion.manuscriptLicenseDetails),
    safe(manuscriptVersion.complianceReportDescription),
    safe(manuscriptVersion.complianceReportUrl),
    safe(manuscriptVersion.apcRequested),
    safe(manuscriptVersion.apcAmountRequested),
    safe(manuscriptVersion.apcCoverageRequestStatus),
    safe(manuscriptVersion.apcAmountPaid),
    safe(manuscriptVersion.declinedReason),
    safe(manuscriptVersion.assignedUsers),
    safe(manuscriptVersion.impact),
    safe(manuscriptVersion.categories),
    safe(manuscriptVersion.versionLastUpdatedDate),
  ];
};
