#!/bin/bash -e

if [[ $APP_NAME = "gp2" ]]
then
  CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID:-$GP2_CONTENTFUL_SPACE_ID}
  CONTENTFUL_ENV_ID=${CONTENTFUL_ENV_ID:-$GP2_CONTENTFUL_ENV_ID}
else
  CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID:-$CRN_CONTENTFUL_SPACE_ID}
  CONTENTFUL_ENV_ID=${CONTENTFUL_ENV_ID:-$CRN_CONTENTFUL_ENV_ID}
  APP_NAME="crn"
fi

CONTENTFUL_MIGRATIONS_DIR=migrations/$APP_NAME
echo $CONTENTFUL_MIGRATIONS_DIR
echo $APP_NAME
echo $CONTENTFUL_SPACE_ID
echo $CONTENTFUL_ENV_ID
echo $CONTENTFUL_MANAGEMENT_ACCESS_TOKEN

CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID CONTENTFUL_ENV_ID=$CONTENTFUL_ENV_ID CONTENTFUL_MANAGEMENT_ACCESS_TOKEN=$CONTENTFUL_MANAGEMENT_ACCESS_TOKEN CONTENTFUL_MIGRATIONS_DIR=$CONTENTFUL_MIGRATIONS_DIR yarn workspace @asap-hub/contentful space:migrate:count

