#!/bin/bash -e

if [[ $APP = "gp2" ]]
then
  CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID:-$GP2_CONTENTFUL_SPACE_ID}
  CONTENTFUL_ENV_ID=${CONTENTFUL_ENV_ID:-$GP2_CONTENTFUL_ENV_ID}
else
  CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID:-$CRN_CONTENTFUL_SPACE_ID}
  CONTENTFUL_ENV_ID=${CONTENTFUL_ENV_ID:-$CRN_CONTENTFUL_ENV_ID}
  APP="crn"
fi

CONTENTFUL_MIGRATIONS_DIR=migrations/$APP

CONTENTFUL_MIGRATIONS_DIR=$CONTENTFUL_MIGRATION_DIR yarn workspace @asap-hub/contentful contentful space generate migration -s $CONTENTFUL_SPACE_ID -e $CONTENTFUL_ENV_ID --mt $CONTENTFUL_MANAGEMENT_ACCESS_TOKEN

