#!/bin/bash -e

if [[ "$APP" == "gp2" ]]
then
  CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID:-$GP2_CONTENTFUL_SPACE_ID}
  CONTENTFUL_ENV_ID=${CONTENTFUL_ENV_ID:-$GP2_CONTENTFUL_ENV_ID}
else
  CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID:-$CRN_CONTENTFUL_SPACE_ID}
  CONTENTFUL_ENV_ID=${CONTENTFUL_ENV_ID:-$CRN_CONTENTFUL_ENV_ID}
  APP="crn"
fi

CONTENTFUL_MIGRATIONS_DIR=migrations/$APP

CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID CONTENTFUL_ENV_ID=$CONTENTFUL_ENV_ID CONTENTFUL_MANAGEMENT_ACCESS_TOKEN=$CONTENTFUL_MANAGEMENT_ACCESS_TOKEN CONTENTFUL_MIGRATIONS_DIR=$CONTENTFUL_MIGRATIONS_DIR yarn workspace @asap-hub/contentful space:migrate:count

