#!/bin/bash -e

if [ -z "$MIGRATION_TYPE" ]; then
    echo "missing environment variable - MIGRATION_TYPE"
    exit
fi
if [ -z "$MIGRATION_NAME" ]; then
    echo "missing environment variable - MIGRATION_NAME"
    exit
fi

if [[ "$APP" == "gp2" ]]
then
  CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID:-$GP2_CONTENTFUL_SPACE_ID}
  CONTENTFUL_ENV_ID=${CONTENTFUL_ENV_ID:-$GP2_CONTENTFUL_ENV_ID}
  CONTENTFUL_ACCESS_TOKEN=${CONTENTFUL_ACCESS_TOKEN:-$GP2_CONTENTFUL_ACCESS_TOKEN}
else
  CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID:-$CRN_CONTENTFUL_SPACE_ID}
  CONTENTFUL_ENV_ID=${CONTENTFUL_ENV_ID:-$CRN_CONTENTFUL_ENV_ID}
  CONTENTFUL_ACCESS_TOKEN=${CONTENTFUL_ACCESS_TOKEN:-$CRN_CONTENTFUL_ACCESS_TOKEN}
  APP="crn"
fi

CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID CONTENTFUL_ENV_ID=$CONTENTFUL_ENV_ID CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN CONTENTFUL_MIGRATIONS_DIR=migrations/$APP yarn workspace @asap-hub/contentful ctf-migrate create $MIGRATION_NAME -c $MIGRATION_TYPE
