import { gp2 as gp2Model } from '@asap-hub/model';
import {
  gp2 as gp2Squidex,
  parseToSquidex,
  SquidexGraphqlClient,
  SquidexRestClient,
} from '@asap-hub/squidex';
import Boom from '@hapi/boom';
import { Filter } from 'odata-query';
import {
  FetchOutputQuery,
  FetchOutputQueryVariables,
  FetchOutputsQuery,
  FetchOutputsQueryVariables,
} from '../autogenerated-gql/graphql';
import { parseGraphQLOutput } from '../entities/output';
import { FETCH_OUTPUT, FETCH_OUTPUTS } from '../queries/outputs.queries';
import logger from '../utils/logger';
import { buildODataFilter } from '../utils/odata';

export const makeODataFilter = (
  filter?: gp2Model.FetchOutputFilter,
): Filter | null => {
  if (!filter) {
    return null;
  }

  const entries = Object.entries(filter).reduce<Filter[]>((res, [key, val]) => {
    if (Array.isArray(val)) {
      return res.concat({
        or: val.map((valElement) => ({
          [`data/${key}/iv`]: valElement,
        })),
      });
    }

    return res.concat({ [`data/${key}/iv`]: val });
  }, []);

  return entries.length === 1 ? (entries[0] as Filter) : entries;
};

export interface OutputDataProvider {
  fetchById(id: string): Promise<gp2Model.OutputDataObject | null>;
  fetch(
    options: gp2Model.FetchOutputOptions,
  ): Promise<gp2Model.ListOutputDataObject>;
  create(input: gp2Model.OutputCreateDataObject): Promise<string>;
  update(id: string, input: gp2Model.OutputUpdateDataObject): Promise<string>;
}

export class OutputSquidexDataProvider implements OutputDataProvider {
  constructor(
    private squidexGraphqlClient: SquidexGraphqlClient,
    private squidexRestClient: SquidexRestClient<
      gp2Squidex.RestOutput,
      gp2Squidex.InputOutput
    >,
  ) {}
  async fetchById(id: string): Promise<gp2Model.OutputDataObject | null> {
    const outputGraphqlResponse = await this.squidexGraphqlClient.request<
      FetchOutputQuery,
      FetchOutputQueryVariables
    >(FETCH_OUTPUT, { id });

    const { findOutputsContent: outputContent } = outputGraphqlResponse;

    if (!outputContent) {
      throw Boom.notFound();
    }

    return parseGraphQLOutput(outputContent);
  }

  async fetch({
    take = 8,
    skip = 0,
    search,
    filter,
    includeDrafts,
  }: gp2Model.FetchOutputOptions): Promise<gp2Model.ListOutputDataObject> {
    const containsFilters = (search || '')
      .split(' ')
      .filter(Boolean)
      .reduce<Filter[]>(
        (res, word: string) => [
          ...res,
          {
            [`data/title/iv`]: {
              contains: word,
            },
          },
        ],
        [],
      );

    const searchQ = containsFilters.length
      ? containsFilters.length === 1
        ? containsFilters[0]
        : { or: containsFilters }
      : null;
    const filterQ = makeODataFilter(filter);
    const filtersAndSearch = [filterQ, searchQ].filter(Boolean);
    const query =
      filtersAndSearch.length === 1 ? filtersAndSearch[0] : filtersAndSearch;
    const filterGraphql = buildODataFilter(query as Filter);

    const { queryOutputsContentsWithTotal } =
      await this.squidexGraphqlClient.request<
        FetchOutputsQuery,
        FetchOutputsQueryVariables
      >(
        FETCH_OUTPUTS,
        {
          top: take,
          skip,
          filter: filterGraphql,
        },
        { includeDrafts },
      );

    if (queryOutputsContentsWithTotal === null) {
      logger.warn('queryOutputsContentsWithTotal returned null');
      return {
        total: 0,
        items: [],
      };
    }

    const { total, items: outputs } = queryOutputsContentsWithTotal;

    if (outputs === null) {
      logger.warn('queryOutputsContentsWithTotal items returned null');
      return {
        total: 0,
        items: [],
      };
    }

    return {
      total,
      items: outputs.map((item) => parseGraphQLOutput(item)),
    };
  }

  async create(input: gp2Model.OutputCreateDataObject): Promise<string> {
    const { authors, publishDate: _, ...outputData } = input;
    const output = parseToSquidex({
      ...outputData,
      authors: authors.map(getAuthorIdList),
      createdBy: [outputData.createdBy],
      updatedBy: [outputData.createdBy],
    });

    const { id: outputId } = await this.squidexRestClient.create(output);

    return outputId;
  }

  async update(
    outputId: string,
    outputToUpdate: gp2Model.OutputUpdateDataObject,
  ): Promise<string> {
    const { authors, publishDate: _, ...outputData } = outputToUpdate;
    const output = parseToSquidex({
      ...outputData,
      authors: authors.map(getAuthorIdList),
      updatedBy: [outputData.updatedBy],
    });

    await this.squidexRestClient.patch(outputId, output);

    return outputId;
  }
}

const getAuthorIdList = (authorDataObject: gp2Model.AuthorUpsertDataObject) => {
  if ('userId' in authorDataObject) {
    return authorDataObject.userId;
  }

  return authorDataObject.externalAuthorId;
};
