import { gp2 } from '@asap-hub/model';
import { isWorkingGroupMemberRole } from '@asap-hub/model/src/gp2';
import { SquidexGraphqlClient } from '@asap-hub/squidex';
import {
  FetchWorkingGroupsQuery,
  FetchWorkingGroupsQueryVariables,
} from '../autogenerated-gql/graphql';
import { FETCH_WORKING_GROUPS } from '../queries/working-groups.queries';
import { createUrl } from '../utils/urls';

export interface WorkingGroupDataProvider {
  fetch(): Promise<gp2.ListWorkingGroupDataObject>;
}
export class WorkingGroupSquidexDataProvider
  implements WorkingGroupDataProvider
{
  constructor(private squidexGraphlClient: SquidexGraphqlClient) {}
  async fetch(): Promise<gp2.ListWorkingGroupDataObject> {
    const result = await this.squidexGraphlClient.request<
      FetchWorkingGroupsQuery,
      FetchWorkingGroupsQueryVariables
    >(FETCH_WORKING_GROUPS);

    if (
      !result.queryWorkingGroupsContentsWithTotal ||
      !result.queryWorkingGroupsContentsWithTotal.items
    ) {
      return {
        total: 0,
        items: [],
      };
    }

    return {
      total: result.queryWorkingGroupsContentsWithTotal.total,
      items: result.queryWorkingGroupsContentsWithTotal.items.map(
        parseWorkingGroupToDataObject,
      ),
    };
  }
}
type Member = NonNullable<
  NonNullable<
    NonNullable<
      NonNullable<
        NonNullable<FetchWorkingGroupsQuery>['queryWorkingGroupsContentsWithTotal']
      >['items']
    >[number]['flatData']
  >['members']
>[number];

type User = NonNullable<NonNullable<Member>['user']>[number];

const parseWorkingGroupMembers = (
  user: User,
  role: gp2.WorkingGroupMemberRole,
) => {
  const flatAvatar = user.flatData.avatar || [];
  const avatarUrl =
    flatAvatar.length > 0
      ? createUrl(flatAvatar.map((a) => a.id))[0]
      : undefined;
  return {
    userId: user.id,
    role,
    firstName: user.flatData.firstName || '',
    lastName: user.flatData.lastName || '',
    avatarUrl,
  };
};

export function parseWorkingGroupToDataObject(
  workingGroup: NonNullable<
    NonNullable<
      NonNullable<FetchWorkingGroupsQuery>['queryWorkingGroupsContentsWithTotal']
    >['items']
  >[number],
): gp2.WorkingGroupDataObject {
  const members =
    workingGroup.flatData.members?.reduce(
      (membersList: gp2.WorkingGroupMember[], member: Member) => {
        if (!isWorkingGroupMemberRole(member.role)) {
          throw new Error(
            `Invalid working group role on members : ${member.role}`,
          );
        }
        const user = member.user && member.user[0];
        if (!user) {
          return membersList;
        }
        const groupMember = parseWorkingGroupMembers(user, member.role);
        return [...membersList, groupMember];
      },
      [],
    ) || [];

  return {
    id: workingGroup.id,
    title: workingGroup.flatData.title || '',
    shortDescription: workingGroup.flatData.shortDescription || '',
    leadingMembers: workingGroup.flatData.leadingMembers || '',
    members,
  };
}
