import { gp2 } from '@asap-hub/model';
import { SquidexGraphqlClient } from '@asap-hub/squidex';
import {
  FetchWorkingGroupsQuery,
  FetchWorkingGroupsQueryVariables,
} from '../autogenerated-gql/graphql';
import { FETCH_WORKING_GROUPS } from '../queries/working-groups.queries';

export interface WorkingGroupDataProvider {
  fetch(): Promise<gp2.ListWorkingGroupDataObject>;
}
export class WorkingGroupSquidexDataProvider
  implements WorkingGroupDataProvider
{
  constructor(private squidexGraphlClient: SquidexGraphqlClient) {}
  async fetch(): Promise<gp2.ListWorkingGroupDataObject> {
    const result = await this.squidexGraphlClient.request<
      FetchWorkingGroupsQuery,
      FetchWorkingGroupsQueryVariables
    >(FETCH_WORKING_GROUPS);

    if (
      !result.queryWorkingGroupsContentsWithTotal ||
      !result.queryWorkingGroupsContentsWithTotal.items
    ) {
      return {
        total: 0,
        items: [],
      };
    }

    return {
      total: result.queryWorkingGroupsContentsWithTotal.total,
      items: result.queryWorkingGroupsContentsWithTotal.items.map(
        (workingGroup) => {
          const members =
            workingGroup.flatData.members?.reduce(
              (membersList: gp2.WorkingGroupMember[], member) => {
                const user = member.user && member.user[0];
                if (!user) {
                  return membersList;
                }

                return [
                  ...membersList,
                  {
                    userId: user.id,
                    role: member.role as gp2.WorkingGroupMemberRole,
                    firstName: user.flatData.firstName || '',
                    lastName: user.flatData.lastName || '',
                  },
                ];
              },
              [],
            ) || [];
          return {
            ...workingGroup.flatData,
            id: workingGroup.id,
            title: workingGroup.flatData.title || '',
            shortDescription: workingGroup.flatData.shortDescription || '',
            leadingMembers: workingGroup.flatData.leadingMembers || '',
            members,
          };
        },
      ),
    };
  }
}
