name: Teardown environment
description: Teardown a PR environment
inputs:
  prNumber:
    required: true
    description: Choose which PR number to destroy
  AWS_ACCESS_KEY_ID:
    required: true
    description: The AWS access key
  AWS_SECRET_ACCESS_KEY:
    required: true
    description: The AWS secret

runs:
  using: composite
  steps:
    - name: Fetch the Algolia keys
      shell: bash
      run: |
        echo "ALGOLIA_APP_ID=$(aws ssm get-parameter --name 'algolia-app-id-dev' --query Parameter.Value --output text)" >> $GITHUB_ENV
        echo "ALGOLIA_API_KEY=$(aws ssm get-parameter --name 'algolia-api-key-ci-dev' --query Parameter.Value --output text)" >> $GITHUB_ENV
    - name: Delete the index
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
      run: |
        cd apps/crn-server
        export ALGOLIA_INDEX=asap-hub_CI-${{ inputs.prNumber }}
        yarn workspace @asap-hub/crn-server run algolia deleteindicespattern -a $ALGOLIA_APP_ID -k $ALGOLIA_API_KEY -r "^$ALGOLIA_INDEX$" -x false

