import {
  AuthorUpsertDataObject,
  convertBooleanToDecision,
  FetchOptions,
  ListResearchOutputDataObject,
  ResearchOutputCreateDataObject,
  ResearchOutputDataObject,
  ResearchOutputUpdateDataObject,
} from '@asap-hub/model';
import {
  InputResearchOutput,
  parseToSquidex,
  RestResearchOutput,
  RestTeam,
  SquidexGraphqlClient,
  SquidexRestClient,
} from '@asap-hub/squidex';
import Boom from '@hapi/boom';
import { Filter } from 'odata-query';
import {
  FetchResearchOutputQuery,
  FetchResearchOutputQueryVariables,
  FetchResearchOutputsQuery,
  FetchResearchOutputsQueryVariables,
} from '../autogenerated-gql/graphql';
import {
  FETCH_RESEARCH_OUTPUT,
  FETCH_RESEARCH_OUTPUTS,
} from '../queries/research-outputs.queries';
import { parseGraphQLResearchOutput } from '../entities/research-output';
import logger from '../utils/logger';
import { buildODataFilter } from '../utils/urls';

export interface ResearchOutputDataProvider {
  fetchById(id: string): Promise<ResearchOutputDataObject | null>;
  fetch(
    options: FetchResearchOutputOptions,
  ): Promise<ListResearchOutputDataObject>;
  create(input: ResearchOutputCreateDataObject): Promise<string>;
  update(id: string, input: ResearchOutputUpdateDataObject): Promise<string>;
}

export class ResearchOutputSquidexDataProvider
  implements ResearchOutputDataProvider
{
  constructor(
    private squidexGraphqlClient: SquidexGraphqlClient,
    private researchOutputSquidexRestClient: SquidexRestClient<
      RestResearchOutput,
      InputResearchOutput
    >,
    private teamSquidexRestClient: SquidexRestClient<RestTeam>,
  ) {}
  async fetchById(id: string): Promise<ResearchOutputDataObject | null> {
    const researchOutputGraphqlResponse =
      await this.squidexGraphqlClient.request<
        FetchResearchOutputQuery,
        FetchResearchOutputQueryVariables
      >(FETCH_RESEARCH_OUTPUT, { id, withTeams: true });

    const { findResearchOutputsContent: researchOutputContent } =
      researchOutputGraphqlResponse;

    if (!researchOutputContent) {
      throw Boom.notFound();
    }

    return parseGraphQLResearchOutput(researchOutputContent);
  }

  async fetch(options: {
    take?: number;
    skip?: number;
    search?: string;
    filter?: ResearchOutputFilter;
    includeDrafts?: boolean;
  }): Promise<ListResearchOutputDataObject> {
    const { search, filter, take = 8, skip = 0, includeDrafts } = options;

    const containsFilters = (search || '')
      .split(' ')
      .filter(Boolean)
      .reduce(
        (res, word: string) => [
          ...res,
          {
            [`data/title/iv`]: {
              contains: word,
            },
          },
          {
            [`data/tags/iv`]: {
              contains: word,
            },
          },
        ],
        [] as Filter[],
      );

    const searchQ = containsFilters.length
      ? containsFilters.length === 1
        ? containsFilters[0]
        : { or: containsFilters }
      : null;

    const filterQ = makeODataFilter(filter);
    const filtersAndSearch = [filterQ, searchQ].filter(Boolean);
    const query =
      filtersAndSearch.length === 1 ? filtersAndSearch[0] : filtersAndSearch;
    const filterGraphql = buildODataFilter(query as Filter);

    const { queryResearchOutputsContentsWithTotal } =
      await this.squidexGraphqlClient.request<
        FetchResearchOutputsQuery,
        FetchResearchOutputsQueryVariables
      >(
        FETCH_RESEARCH_OUTPUTS,
        {
          top: take,
          skip,
          filter: filterGraphql,
          withTeams: true,
        },
        {
          includeDrafts,
        },
      );

    if (queryResearchOutputsContentsWithTotal === null) {
      logger.warn('queryResearchOutputsContentsWithTotal returned null');
      return {
        total: 0,
        items: [],
      };
    }

    const { total, items: researchOutputs } =
      queryResearchOutputsContentsWithTotal;

    if (researchOutputs === null) {
      logger.warn('queryResearchOutputsContentsWithTotal items returned null');
      return {
        total: 0,
        items: [],
      };
    }

    return {
      total,
      items: researchOutputs.map((item) => parseGraphQLResearchOutput(item)),
    };
  }

  async create(input: ResearchOutputCreateDataObject): Promise<string> {
    const {
      authors,
      teamIds,
      labIds,
      methodIds,
      environmentIds,
      organismIds,
      subtypeId,
      ...researchOutputData
    } = input;
    const { usedInPublication, ...researchOutput } = parseToSquidex({
      ...researchOutputData,
      asapFunded: convertBooleanToDecision(researchOutputData.asapFunded),
      usedInPublication: convertBooleanToDecision(
        researchOutputData.usedInPublication,
      ),
      authors: authors.map(getAuthorIdList),
      createdBy: [researchOutputData.createdBy],
      updatedBy: [researchOutputData.createdBy],
      labs: labIds,
      methods: methodIds,
      environments: environmentIds,
      organisms: organismIds,
      subtype: (subtypeId && [subtypeId]) || [],
    });

    const { id: researchOutputId } =
      await this.researchOutputSquidexRestClient.create({
        doi: { iv: null },
        accession: { iv: null },
        rrid: { iv: null },
        ...researchOutput,
        usedInAPublication: usedInPublication,
      });

    await Promise.all(
      teamIds.map((teamId) =>
        this.associateResearchOutputToTeam(teamId, researchOutputId),
      ),
    );

    return researchOutputId;
  }

  async update(
    researchOutputId: string,
    input: ResearchOutputUpdateDataObject,
  ): Promise<string> {
    const {
      authors,
      teamIds: _teamIds,
      labIds,
      methodIds,
      environmentIds,
      organismIds,
      subtypeId,
      ...researchOutputData
    } = input;
    const { usedInPublication, ...researchOutput } = parseToSquidex({
      ...researchOutputData,
      asapFunded: convertBooleanToDecision(researchOutputData.asapFunded),
      usedInPublication: convertBooleanToDecision(
        researchOutputData.usedInPublication,
      ),
      authors: authors.map(getAuthorIdList),
      labs: labIds,
      methods: methodIds,
      environments: environmentIds,
      organisms: organismIds,
      subtype: (subtypeId && [subtypeId]) || [],
      updatedBy: [researchOutputData.updatedBy],
    });

    await this.researchOutputSquidexRestClient.patch(researchOutputId, {
      doi: { iv: null },
      accession: { iv: null },
      rrid: { iv: null },
      ...researchOutput,
      usedInAPublication: usedInPublication,
      labs: researchOutput.labs || { iv: null },
    });

    return researchOutputId;
  }

  private async associateResearchOutputToTeam(
    teamId: string,
    researchOutputId: string,
  ) {
    const { data } = await this.teamSquidexRestClient.fetchById(teamId, false);
    const existingOutputs = data.outputs?.iv || [];
    await this.teamSquidexRestClient.patch(teamId, {
      outputs: {
        iv: [...existingOutputs, researchOutputId],
      },
    });
  }
}

type ResearchOutputFilter = {
  documentType?: string | string[];
  title?: string;
  link?: string;
};

export type FetchResearchOutputOptions = FetchOptions<ResearchOutputFilter> & {
  includeDrafts?: boolean;
};

const makeODataFilter = (filter?: ResearchOutputFilter): Filter | null => {
  if (filter) {
    const entries = Object.entries(filter).reduce((res, [key, val]) => {
      if (Array.isArray(val)) {
        return res.concat({
          or: val.map((valElement) => ({
            [`data/${key}/iv`]: valElement,
          })),
        });
      }
      return res.concat({ [`data/${key}/iv`]: val });
    }, [] as Filter[]);

    return entries.length === 1 ? (entries[0] as Filter) : entries;
  }

  return null;
};

const getAuthorIdList = (authorDataObject: AuthorUpsertDataObject) => {
  if ('userId' in authorDataObject) {
    return authorDataObject.userId;
  }

  return authorDataObject.externalAuthorId;
};
