import { TutorialsDataObject, DataProvider } from '@asap-hub/model';
import { SquidexGraphqlClient } from '@asap-hub/squidex';
import {
  FetchTutorialsQuery,
  FetchTutorialsQueryVariables,
} from '../autogenerated-gql/graphql';
import { parseGraphQLTutorials } from '../entities';
import { FETCH_TUTORIAL } from '../queries/tutorials.queries';

export type TutorialsDataProvider = DataProvider<TutorialsDataObject>;

export class TutorialsSquidexDataProvider implements TutorialsDataProvider {
  constructor(private squidexGraphqlClient: SquidexGraphqlClient) {}

  async fetch(): Promise<{ items: TutorialsDataObject[]; total: number }> {
    throw new Error('Method not implemented.');
  }

  async fetchById(id: string): Promise<TutorialsDataObject | null> {
    const { findTutorialsContent } = await this.squidexGraphqlClient.request<
      FetchTutorialsQuery,
      FetchTutorialsQueryVariables
    >(FETCH_TUTORIAL, { id });

    if (!findTutorialsContent) {
      return null;
    }
    return parseGraphQLTutorials(findTutorialsContent);
  }
}
