import { TutorialsDataObject } from '@asap-hub/model';
import { SquidexGraphqlClient } from '@asap-hub/squidex';
import {
  FetchTutorialsQuery,
  FetchTutorialsQueryVariables,
} from '../autogenerated-gql/graphql';
import { parseGraphQLTutorials } from '../entities';
import { FETCH_TUTORIAL } from '../queries/tutorials.queries';

export interface TutorialsDataProvider {
  fetchById(id: string): Promise<TutorialsDataObject | null>;
}
export class TutorialsSquidexDataProvider implements TutorialsDataProvider {
  constructor(private squidexGraphlClient: SquidexGraphqlClient) {}
  async fetchById(id: string): Promise<TutorialsDataObject | null> {
    const { findTutorialsContent } = await this.queryFetchByIdData(id);

    if (!findTutorialsContent) {
      return null;
    }
    return parseGraphQLTutorials(findTutorialsContent);
  }

  private async queryFetchByIdData(id: string) {
    return this.squidexGraphlClient.request<
      FetchTutorialsQuery,
      FetchTutorialsQueryVariables
    >(FETCH_TUTORIAL, { id });
  }
}
