name: 'Run unit tests'
description: 'Check if a string is a number'
inputs:
  shard:
    description: 'The target shard'
    required: true
  total:
    description: 'The total shards'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Cache Jest cache
      uses: actions/cache@v3
      with:
        path: |
          .jest-cache/
        key: jest-cache-${{ inputs.since-master }}-${{ github.sha }}
        restore-keys: |
          jest-cache-${{ inputs.since-master }}-
          jest-cache-
    - name: Get number of CPU cores
      id: cpu-cores
      uses: SimenB/github-actions-cpu-cores@v1
    - name: Run all tests
      shell: bash
      run: yarn test --coverage --shard ${{ inputs.shard }}/${{ inputs.total }} --maxWorkers ${{ steps.cpu-cores.outputs.count }} --ci
    - name: move coverage
      shell: bash
      run: mv coverage/coverage-final.json coverage/${{matrix.shard}}.json
    - uses: actions/upload-artifact@v3
      with:
        name: coverage-artifacts
        path: coverage/
