name: 'Run unit tests'
description: 'Check if a string is a number'
inputs:
  since-master:
    description: 'Whether to run tests since master'
    required: false
    type: boolean
    default: false
  codecov-token:
    description: 'The environment name'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Cache Jest cache
      uses: actions/cache@v3
      with:
        path: |
          .jest-cache/
        key: jest-cache-${{ inputs.since-master }}-${{ github.sha }}
        restore-keys: |
          jest-cache-${{ inputs.since-master }}-
    - name: Get number of CPU cores
      id: cpu-cores
      uses: SimenB/github-actions-cpu-cores@v1
    - name: Fetch master branch
      shell: bash
      if: ${{ inputs.since-master == 'true' }}
      run: |
        chown -R root /__w/asap-hub/asap-hub
        git fetch --no-tags --depth=1 origin master
        git checkout -b master origin/master
        git checkout -
    - name: Run tests from diff with master
      shell: bash
      if: ${{ inputs.since-master == 'true' }}
      run: yarn test --maxWorkers ${{ steps.cpu-cores.outputs.count }} --ci --changedSince=master
    - name: Run all tests
      shell: bash
      if: ${{ inputs.since-master == 'false' }}
      run: yarn test --coverage --maxWorkers ${{ steps.cpu-cores.outputs.count }} --ci
    - uses: codecov/codecov-action@v3
      if: ${{ inputs.since-master == 'false' }}
      with:
        fail_ci_if_error: true
        directory: coverage
        verbose: true
      env:
        CODECOV_TOKEN: ${{ inputs.codecov-token }}
