name: 'Run unit tests'
description: 'Check if a string is a number'
inputs:
  shard:
    description: 'The target shard'
    required: true
  total:
    description: 'The total shards'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Cache Jest cache
      uses: actions/cache/restore@v3
      id: restore-cache
      with:
        path: |
          .jest-cache/
        key: jest-cache-shard-${{ inputs.shard }}
    - name: Get number of CPU cores
      id: cpu-cores
      uses: SimenB/github-actions-cpu-cores@v1
    - name: Run test shard
      shell: bash
      run: yarn test --coverage --shard ${{ inputs.shard }}/${{ inputs.total }} --maxWorkers ${{ steps.cpu-cores.outputs.count }} --ci
    - name: move coverage
      shell: bash
      run: mv coverage/coverage-final.json coverage/${{matrix.shard}}.json
    - uses: actions/upload-artifact@v3
      with:
        name: coverage-artifacts
        path: coverage/
    - uses: actions/cache/save@v3
      with:
        path: |
          .jest-cache/
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}
