import { gp2 } from '@asap-hub/model';
import { gp2 as gp2Squidex, parseToSquidex } from '@asap-hub/squidex';
import { FetchContributingCohortsQuery } from '../../src/autogenerated-gql/graphql';

export const getGraphQLContributingCohort = (): NonNullable<
  NonNullable<
    NonNullable<FetchContributingCohortsQuery>['queryContributingCohortsContentsWithTotal']
  >['items']
>[number] => ({
  id: '42',
  flatData: {
    name: 'some name',
  },
});
export const getSquidexContributingCohortGraphqlResponse =
  (): FetchContributingCohortsQuery => ({
    queryContributingCohortsContentsWithTotal: {
      total: 1,
      items: [getGraphQLContributingCohort()],
    },
  });

export const getContributingCohortDataObject =
  (): gp2.ContributingCohortDataObject => ({
    id: '42',
    name: 'some name',
  });

export const getListContributingCohortDataObject =
  (): gp2.ListContributingCohortDataObject => ({
    total: 1,
    items: [getContributingCohortDataObject()],
  });

export const getContributingCohortResponse =
  (): gp2.ContributingCohortResponse => getContributingCohortDataObject();

export const getListContributingCohortResponse =
  (): gp2.ListContributingCohortResponse => ({
    total: 1,
    items: [getContributingCohortDataObject()],
  });
export const getContributingCohortCreateDataObject =
  (): gp2.ContributingCohortCreateDataObject => {
    const { id: _id, ...created } = getContributingCohortDataObject();

    return created;
  };
export const fetchContributingCohortResponse = () => ({
  id: 'cohortId',
  data: {
    name: { iv: 'some name ' },
  },
});
export const getContributingCohortInput =
  (): gp2Squidex.InputContributingCohort['data'] => {
    const input = getContributingCohortCreateDataObject();

    return parseToSquidex(input);
  };
