import { gp2 as gp2Model } from '@asap-hub/model';
import { FetchNewsQuery } from '../../src/autogenerated-gql/graphql';

export const getGraphQLNews = (): NonNullable<
  NonNullable<
    NonNullable<FetchNewsQuery>['queryNewsAndEventsContentsWithTotal']
  >['items']
>[number] => ({
  id: '42',
  created: '2021-12-28',
  lastModified: '2021-12-28',
  version: 11,
  flatData: {
    title: 'a news item',
    shortText: 'the short text of the news',
    sampleCount: 3,
    articleCount: 11,
    cohortCount: 43,
    link: 'http://example.com/a-link',
    linkText: 'some link text',
  },
});
export const getSquidexNewsGraphqlResponse = (): FetchNewsQuery => ({
  queryNewsAndEventsContentsWithTotal: {
    total: 1,
    items: [getGraphQLNews()],
  },
});

export const getNewsDataObject = (): gp2Model.NewsDataObject => ({
  id: '42',
  title: 'a news item',
  shortText: 'the short text of the news',
  created: '2021-12-28T00:00:00.000Z',
  sampleCount: 3,
  articleCount: 11,
  cohortCount: 43,
  link: 'http://example.com/a-link',
  linkText: 'some link text',
});

export const getListNewsDataObject = (): gp2Model.ListNewsDataObject => ({
  total: 1,
  items: [getNewsDataObject()],
});

export const getNewsResponse = (): gp2Model.NewsResponse => getNewsDataObject();

export const getListNewsResponse = (): gp2Model.ListNewsResponse => ({
  total: 1,
  items: [getNewsResponse()],
});
