import type { gp2 } from '@asap-hub/model';
import { FetchWorkingGroupsQuery } from '../../src/autogenerated-gql/graphql';

export const getWorkingGroupDataObject = (): gp2.WorkingGroupDataObject => ({
  id: 'working-group-id-1',
  title: 'Working Group',
  shortDescription: 'Short description',
  leadingMembers: 'Leading members',
  members: [],
});

export const getListWorkingGroupDataObject =
  (): gp2.ListWorkingGroupResponse => ({
    total: 1,
    items: [getWorkingGroupDataObject()],
  });

export const getWorkingGroupResponse = (): gp2.WorkingGroupResponse =>
  getWorkingGroupDataObject();

export const getListWorkingGroupResponse =
  (): gp2.ListWorkingGroupResponse => ({
    total: 1,
    items: [getWorkingGroupResponse()],
  });

export const getSquidexWorkingGroupGraphqlResponse =
  (): FetchWorkingGroupsQuery => ({
    queryWorkingGroupsContentsWithTotal: {
      total: 1,
      items: [getGraphQLWorkingGroup()],
    },
  });

export const getGraphQLWorkingGroup = (): NonNullable<
  NonNullable<
    FetchWorkingGroupsQuery['queryWorkingGroupsContentsWithTotal']
  >['items']
>[number] => ({
  id: 'working-group-id-1',
  flatData: {
    title: 'Working Group',
    shortDescription: 'Short description',
    leadingMembers: 'Leading members',
  },
});
