name: 'Build Frontend'
description: 'Builds frontend'
inputs:
  algolia-app-name:
    description: 'Algolia App Name'
    required: true
  algolia-index:
    description: 'Algolia Index'
    required: true
  app-release:
    description: 'App Release'
    required: true
  asap-api-url:
    description: 'ASAP API Url'
    required: true
  auth0-client-id:
    description: 'Auth0 Client Id'
    required: true
  auth0-domain:
    description: 'Auth0 Domain'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  environment-name:
    description: 'Environment name'
    required: true
  react-app-environment:
    description: 'React App Environment'
    required: true
  react-app-gtm-container-id:
    description: 'GTM Container ID'
    required: true
  react-app-sentry-dsn:
    description: 'Sentry DSN'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Get Algolia app Id
      shell: bash
      env:
        ALGOLIA_APP_NAME: ${{ inputs.algolia-app-name }}
      id: get-algolia-app-id
      run: |
        REACT_APP_ALGOLIA_APP_ID=$(aws ssm get-parameter --name $ALGOLIA_APP_NAME --query Parameter.Value --output text)
        echo "::set-output name=id::$REACT_APP_ALGOLIA_APP_ID"

    - name: Cache transpile output
      uses: actions/cache@v2
      with:
        path: |
          apps/**/build*
          packages/**/build*
        key: transpile-output-${{ inputs.environment-name }}-${{ github.sha }}

    - name: Cache build typecheck output
      uses: actions/cache@v2
      with:
        path: |
          apps/**/build*
          packages/**/build*
        key: definitions-output-${{ inputs.environment-name }}-${{ github.sha }}

    - name: Build
      shell: bash
      env:
        AUTH0_CLIENT_ID: ${{ inputs.auth0-client-id }}
        AUTH0_DOMAIN: ${{ inputs.auth0-domain }}
        REACT_APP_ALGOLIA_APP_ID: ${{ steps.get-algolia-app-id.outputs.id }}
        REACT_APP_ALGOLIA_INDEX: ${{ inputs.algolia-index }}
        REACT_APP_API_BASE_URL: ${{ inputs.asap-api-url }}
        REACT_APP_ENVIRONMENT: ${{ inputs.react-app-environment }}
        REACT_APP_GTM_CONTAINER_ID: ${{ inputs.react-app-gtm-container-id }}
        REACT_APP_RELEASE: ${{ inputs.app-release }}
        REACT_APP_SENTRY_DSN: ${{ inputs.react-app-sentry-dsn }}
      run: |
        yarn build:frontend

    - name: Cache build output
      uses: actions/cache@v2
      with:
        path: |
          apps/**/build*
          packages/**/build*
        key: build-frontend-output-${{ inputs.environment-name }}-${{ github.sha }}
