#!/usr/bin/env sh

HOSTNAME=${BASE_HOSTNAME:-"hub.asap.science"}
APP_HOSTNAME=$HOSTNAME
API_HOSTNAME="api.$HOSTNAME"
if [ ! -z $CI_EXTERNAL_PULL_REQUEST_IID ]; then
    ENV=${CI_EXTERNAL_PULL_REQUEST_IID}
    API_HOSTNAME="api-${ENV}.${APP_HOSTNAME}"
    APP_HOSTNAME="${ENV}.${APP_HOSTNAME}"
fi

echo "APP_HOSTNAME=${APP_HOSTNAME}"
echo "API_HOSTNAME=${API_HOSTNAME}"
