import { gp2 } from '@asap-hub/model';
import { CalendarsFlatDataDto } from '../autogenerated-gql/graphql';
import { parseCalendarDataObjectToResponse } from '../controllers/calendar.controller';

export const parseGraphqlCalendarToResponse = (
  graphqlCalendar: Pick<
    CalendarsFlatDataDto,
    'name' | 'googleCalendarId' | 'color'
  >,
): gp2.CalendarResponse =>
  parseCalendarDataObjectToResponse(
    parseGraphqlCalendarPartialToDataObject(graphqlCalendar),
  );

export const parseGraphqlCalendarPartialToDataObject = (
  graphqlCalendar: Pick<
    CalendarsFlatDataDto,
    'name' | 'googleCalendarId' | 'color'
  >,
): Pick<gp2.CalendarDataObject, 'name' | 'googleCalendarId' | 'color'> => ({
  color: gp2.isGoogleLegacyCalendarColor(graphqlCalendar.color)
    ? graphqlCalendar.color
    : ('#333333' as const),
  googleCalendarId: graphqlCalendar.googleCalendarId ?? '',
  name: graphqlCalendar.name ?? '',
});
