export { default as appleCalendarIconImage } from './apple-calendar.png';
export { default as asapPaddedWhiteImage } from './asap-padded-white.png';
export { default as asapPaddedImage } from './asap-padded.png';
export { default as asapImage } from './asap.png';
export { default as backgroundBrainsImage } from './background-brains.png';
export { default as backgroundNeuronsImage } from './background-neurons.png';
export { default as loadingImage } from './loading.gif';
export { default as validTickGreenImage } from './valid-tick-green.gif';
export { default as validTickWhiteImage } from './valid-tick-white.gif';
