import { Entry, Link } from '@asap-hub/contentful';
import { eventsQuery as squidexEventsQuery } from './events.queries';
import {
  FetchEventsQuery as SquidexFetchEventsQuery,
  FetchEventsQueryVariables as SquidexFetchEventsQueryVariables,
} from '../autogenerated-gql/graphql';
import {
  createAsset,
  createCalendarLink,
  createDocumentIfNeeded,
  getSquidexAndContentfulClients,
  logger,
  paginatedFetch,
} from '../utils';
import { migrateFromSquidexToContentfulFactory } from '../utils/migration';
import { contentfulRateLimiter } from '../contentful-rate-limiter';

export type EventItem = NonNullable<
  NonNullable<SquidexFetchEventsQuery['queryEventsContentsWithTotal']>['items']
>[number];

export const migrateEvents = async () => {
  const { contentfulEnvironment, squidexGraphqlClient } =
    await getSquidexAndContentfulClients();

  const migrateFromSquidexToContentful = migrateFromSquidexToContentfulFactory(
    contentfulEnvironment,
    logger,
  );
  const fetchAllData = async (): Promise<EventItem[]> =>
    paginatedFetch<EventItem>(async (take: number, skip: number) => {
      const { queryEventsContentsWithTotal } =
        await squidexGraphqlClient.request<
          SquidexFetchEventsQuery,
          SquidexFetchEventsQueryVariables
        >(squidexEventsQuery, { take, skip });
      return queryEventsContentsWithTotal;
    });

  const fetchData = async () => {
    const entries = await fetchAllData();
    logger(`Loaded ${entries.length} entries...`, 'INFO');
    return entries;
  };

  const fetchContentfulEventByGoogleId = async (googleId: string) => {
    const events = await contentfulEnvironment.getEntries({
      content_type: 'events',
      'fields.googleId': googleId,
    });

    if (!events || !events.items.length) {
      return null;
    }

    return events.items[0];
  };

  const createSpeakerEntry = async (
    speakers: EventItem['flatData']['speakers'],
    eventId: string,
  ) => {
    if (speakers) {
      const speakersLinks = await Promise.all(
        speakers.map(async ({ team: squidexTeam, user: squidexUser }) => {
          const teamId = squidexTeam ? squidexTeam[0].id : null;
          const userId = squidexUser ? squidexUser[0]?.id : null;

          try {
            const contentfulTeam = teamId
              ? await contentfulEnvironment.getEntry(teamId)
              : null;
            await contentfulRateLimiter.removeTokens(1);

            const contentfulUser = userId
              ? await contentfulEnvironment.getEntry(userId)
              : null;
            await contentfulRateLimiter.removeTokens(1);

            if (contentfulTeam) {
              const speakerEntry = await contentfulEnvironment.createEntry(
                'eventSpeakers',
                {
                  fields: {
                    team: {
                      'en-US': {
                        sys: {
                          type: 'Link',
                          linkType: 'Entry',
                          id: teamId,
                        },
                      },
                    },
                    user: {
                      'en-US': {
                        sys: {
                          type: 'Link',
                          linkType: 'Entry',
                          id: userId,
                        },
                      },
                    },
                  },
                },
              );
              await contentfulRateLimiter.removeTokens(1);

              await speakerEntry.publish();
              await contentfulRateLimiter.removeTokens(1);
              return {
                sys: {
                  type: 'Link',
                  linkType: 'Entry',
                  id: speakerEntry.sys.id,
                },
              };
            }

            if (contentfulUser) {
              const speakerEntry = await contentfulEnvironment.createEntry(
                'eventSpeakers',
                {
                  fields: {
                    user: {
                      'en-US': {
                        sys: {
                          type: 'Link',
                          linkType: 'Entry',
                          id: userId,
                        },
                      },
                    },
                  },
                },
              );

              await speakerEntry.publish();

              return {
                sys: {
                  type: 'Link',
                  linkType: 'Entry',
                  id: speakerEntry.sys.id,
                },
              };
            }
          } catch {
            // edge case, this should not happen if the migration happened in the correct order
            logger(
              `Either user ${userId} or team ${teamId} do not exist in contentful. Please review event with id ${eventId}`,
              'ERROR',
            );
          }

          return null;
        }),
      );
      return speakersLinks.filter(Boolean) as Link<'Entry'>[];
    }

    return null;
  };

  const deletePreviousSpeakerReferences = async (contentfulEvent: Entry) => {
    if (contentfulEvent.fields.speakers) {
      await Promise.all(
        contentfulEvent.fields.speakers['en-US'].map(
          async (speakerLink: Link<'Entry'>) => {
            try {
              const entry = await contentfulEnvironment.getEntry(
                speakerLink.sys.id,
              );
              await contentfulRateLimiter.removeTokens(1);

              await entry.unpublish();
              await contentfulRateLimiter.removeTokens(1);

              await entry.delete();
              await contentfulRateLimiter.removeTokens(1);
            } catch {
              logger('Error deleting old speaker', 'ERROR');
            }
          },
        ),
      );
    }
  };

  const parseEventItem = async (event: EventItem) => {
    const { id, flatData: squidexFlatData } = event;
    const {
      googleId,
      hidden,
      meetingLink,
      hideMeetingLink,
      thumbnail,
      tags,
      speakers,
      notes,
      notesPermanentlyUnavailable,
      notesUpdatedAt,
      videoRecording,
      videoRecordingPermanentlyUnavailable,
      videoRecordingUpdatedAt,
      presentation,
      presentationPermanentlyUnavailable,
      presentationUpdatedAt,
      meetingMaterials,
      meetingMaterialsPermanentlyUnavailable,
      calendar,
    } = squidexFlatData;

    const materialsSpeakersThumbAndMeetingLink = {
      thumbnail: thumbnail?.length
        ? await createAsset(contentfulEnvironment, thumbnail)
        : null,
      speakers: await createSpeakerEntry(speakers, id),
      notes: await createDocumentIfNeeded(contentfulEnvironment, notes),
      videoRecording: await createDocumentIfNeeded(
        contentfulEnvironment,
        videoRecording,
      ),
      presentation: await createDocumentIfNeeded(
        contentfulEnvironment,
        presentation,
      ),
      // it throws an error if meetingLink is ''
      // because it's not a valid url
      meetingLink: meetingLink?.trim() === '' ? null : meetingLink?.trim(),
    };

    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const contentfulEvent = await fetchContentfulEventByGoogleId(googleId!);

    if (contentfulEvent) {
      await deletePreviousSpeakerReferences(contentfulEvent);

      return {
        id: contentfulEvent.sys.id,
        updateEntry: true,
        hidden,
        hideMeetingLink,
        tags,
        notesPermanentlyUnavailable,
        notesUpdatedAt,
        videoRecordingPermanentlyUnavailable,
        videoRecordingUpdatedAt,
        presentationPermanentlyUnavailable,
        presentationUpdatedAt,
        meetingMaterials,
        meetingMaterialsPermanentlyUnavailable,
        ...materialsSpeakersThumbAndMeetingLink,
      };
    }

    return {
      id,
      updateEntry: false,
      ...squidexFlatData,
      ...materialsSpeakersThumbAndMeetingLink,
      calendar: calendar?.[0]?.id
        ? await createCalendarLink(
            contentfulEnvironment,
            calendar[0].id,
            `Event with id ${id} is going to be created without a calendar.`,
          )
        : null,
    };
  };

  // this clearPreviousEntries should be set to false
  // in case we want to update the existing Contentful events
  // created during google calendar sync instead of creating
  // the events during the migration
  const clearPreviousEntries = true;

  await migrateFromSquidexToContentful<EventItem>(
    'events',
    fetchData,
    parseEventItem,
    clearPreviousEntries,
  );
};
