#!/bin/bash -e

SQUIDEX_CLIENT_ID=${SQUIDEX_CLIENT_ID:-$CRN_SQUIDEX_CLIENT_ID}
SQUIDEX_CLIENT_SECRET=${SQUIDEX_CLIENT_SECRET:-$CRN_SQUIDEX_CLIENT_SECRET}
export SQUIDEX_APP_NAME=${SQUIDEX_APP_NAME:-$CRN_SQUIDEX_APP_NAME}

export SQUIDEX_TOKEN=$(curl -s --request POST --url $SQUIDEX_BASE_URL/identity-server/connect/token --header 'Content-Type: application/x-www-form-urlencoded' --data grant_type=client_credentials --data client_id=$SQUIDEX_CLIENT_ID --data client_secret=$SQUIDEX_CLIENT_SECRET --data scope=squidex-api | grep 'access_token' | sed "s/.*\"access_token\": \"\([^\"]*\).*/\1/g")

graphql-codegen --config codegen.yml
yarn run prettier --write ./src/autogenerated-gql/*