name: Contentful Checks
description: Defines outputs to set up Contentful-based steps

inputs:
  contentful-space-id:
    description: 'Contentful Space ID'
    required: true
  contentful-token:
    description: 'Contentful access token'
    required: true
  contentful-environment-id:
    description: 'Contentful environment name'
    required: true
    type: string

outputs:
  contentful-env-exists:
    description: 'Whether the Contentful environment already exists'
    value: ${{ steps.check-contentful-exists.outputs.exists }}

runs:
  using: 'composite'
  steps:
    - name: Determine whether the Contentful environment has been created
      id: check-contentful-exists
      shell: bash
      run: |
        ENVIRONMENT_TYPE=$(curl --silent \
                                --request GET \
                                --header "Authorization: Bearer ${CONTENTFUL_MANAGEMENT_ACCESS_TOKEN}" \
                                https://api.contentful.com/spaces/${CONTENTFUL_SPACE_ID}/environments/${CONTENTFUL_ENV} \
                                | jq '.sys.type' -r)

        if [[ "$ENVIRONMENT_TYPE" == "Environment" ]]; then
          echo "Environment found, setting exists flag to true."
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "Environment not found, setting exists flag to false."
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      env:
        CONTENTFUL_ENV: ${{ inputs.contentful-environment-id }}
        CONTENTFUL_SPACE_ID: ${{ inputs.contentful-space-id }}
        CONTENTFUL_MANAGEMENT_ACCESS_TOKEN: ${{ inputs.contentful-token }}
