/* eslint-disable */
import * as graphql from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

const documents = {
  '\n  fragment CalendarsData on Calendars {\n    id\n    created\n    lastModified\n    version\n    flatData {\n      googleCalendarId\n      name\n      color\n      syncToken\n      resourceId\n      expirationDate\n    }\n    referencingProjectsContents {\n      id\n      flatData {\n        title\n      }\n    }\n    referencingWorkingGroupsContents {\n      id\n      flatData {\n        title\n      }\n    }\n  }\n':
    graphql.CalendarsDataFragmentDoc,
  '\n  query FetchCalendar($id: String!) {\n    findCalendarsContent(id: $id) {\n      ...CalendarsData\n    }\n  }\n  \n':
    graphql.FetchCalendarDocument,
  '\n  query FetchCalendars($top: Int, $skip: Int, $filter: String, $order: String) {\n    queryCalendarsContentsWithTotal(\n      top: $top\n      skip: $skip\n      filter: $filter\n      orderby: $order\n    ) {\n      total\n      items {\n        ...CalendarsData\n      }\n    }\n  }\n  \n':
    graphql.FetchCalendarsDocument,
  '\n  fragment ContributingCohortsData on ContributingCohorts {\n    id\n    flatData {\n      name\n    }\n  }\n':
    graphql.ContributingCohortsDataFragmentDoc,
  '\n  query FetchContributingCohorts($top: Int, $skip: Int) {\n    queryContributingCohortsContentsWithTotal(\n      top: $top\n      skip: $skip\n      orderby: "data/name/iv"\n    ) {\n      total\n      items {\n        ...ContributingCohortsData\n      }\n    }\n  }\n  \n':
    graphql.FetchContributingCohortsDocument,
  '\n  fragment EventData on Events {\n    id\n    lastModified\n    version\n    created\n    flatData {\n      description\n      endDate\n      endDateTimeZone\n      startDate\n      startDateTimeZone\n      meetingLink\n      hideMeetingLink\n      eventLink\n      status\n      tags\n      title\n      notesPermanentlyUnavailable\n      notes\n      videoRecordingPermanentlyUnavailable\n      videoRecording\n      presentationPermanentlyUnavailable\n      presentation\n      meetingMaterialsPermanentlyUnavailable\n      meetingMaterials {\n        url\n        title\n      }\n      calendar {\n        flatData {\n          googleCalendarId\n          color\n          name\n        }\n        referencingProjectsContents {\n          ...ProjectData\n        }\n        referencingWorkingGroupsContents {\n          ...WorkingGroupData\n        }\n      }\n      thumbnail {\n        id\n      }\n      speakers {\n        user {\n          __typename\n          ... on Users {\n            id\n            flatData {\n              firstName\n              lastName\n              onboarded\n              avatar {\n                id\n              }\n            }\n          }\n          ... on ExternalUsers {\n            id\n            flatData {\n              name\n              orcid\n            }\n          }\n        }\n        topic\n      }\n    }\n  }\n  ,\n  \n':
    graphql.EventDataFragmentDoc,
  '\n  query FetchEvents($top: Int, $skip: Int, $filter: String, $order: String) {\n    queryEventsContentsWithTotal(\n      top: $top\n      skip: $skip\n      filter: $filter\n      orderby: $order\n    ) {\n      total\n      items {\n        ...EventData\n      }\n    }\n  }\n  \n':
    graphql.FetchEventsDocument,
  '\n  query FetchEvent($id: String!) {\n    findEventsContent(id: $id) {\n      ...EventData\n    }\n  }\n  \n':
    graphql.FetchEventDocument,
  '\n  query FetchGroupCalendar($id: String!) {\n    findProjectsContent(id: $id) {\n      flatData {\n        calendars {\n          id\n        }\n      }\n    }\n  }\n':
    graphql.FetchGroupCalendarDocument,
  '\n  query FetchWorkingGroupCalendar($id: String!) {\n    findWorkingGroupsContent(id: $id) {\n      flatData {\n        calendars {\n          id\n        }\n      }\n    }\n  }\n':
    graphql.FetchWorkingGroupCalendarDocument,
  '\n  fragment ExternalUsersData on ExternalUsers {\n    id\n    flatData {\n      name\n      orcid\n    }\n  }\n':
    graphql.ExternalUsersDataFragmentDoc,
  '\n  query FetchExternalUser($id: String!) {\n    findExternalUsersContent(id: $id) {\n      ...ExternalUsersData\n    }\n  }\n  \n':
    graphql.FetchExternalUserDocument,
  '\n  query FetchExternalUsers($top: Int, $skip: Int, $filter: String) {\n    queryExternalUsersContentsWithTotal(\n      top: $top\n      skip: $skip\n      filter: $filter\n      orderby: "data/name/iv"\n    ) {\n      total\n      items {\n        ...ExternalUsersData\n      }\n    }\n  }\n  \n':
    graphql.FetchExternalUsersDocument,
  '\n  fragment NewsData on NewsAndEvents {\n    id\n    created\n    lastModified\n    version\n    flatData {\n      title\n      shortText\n      link\n      linkText\n      sampleCount\n      articleCount\n      cohortCount\n      link\n      linkText\n    }\n  }\n':
    graphql.NewsDataFragmentDoc,
  '\n  query FetchNews($top: Int, $skip: Int) {\n    queryNewsAndEventsContentsWithTotal(\n      top: $top\n      skip: $skip\n      orderby: "created desc"\n    ) {\n      total\n      items {\n        ...NewsData\n      }\n    }\n  }\n  \n':
    graphql.FetchNewsDocument,
  '\n  fragment OutputData on Outputs {\n    id\n    created\n    lastModified\n    version\n    flatData {\n      title\n      documentType\n      type\n      subtype\n      link\n      addedDate\n      publishDate\n      lastUpdatedPartial\n      authors {\n        __typename\n        ... on Users {\n          id\n          created\n          lastModified\n          version\n          flatData {\n            avatar {\n              id\n            }\n            firstName\n            lastName\n            onboarded\n            email\n          }\n        }\n        ... on ExternalUsers {\n          id\n          created\n          lastModified\n          version\n          flatData {\n            name\n            orcid\n          }\n        }\n      }\n      workingGroups {\n        id\n        flatData {\n          title\n        }\n      }\n      projects {\n        id\n        flatData {\n          title\n        }\n      }\n    }\n  }\n':
    graphql.OutputDataFragmentDoc,
  '\n  query FetchOutput($id: String!) {\n    findOutputsContent(id: $id) {\n      ...OutputData\n    }\n  }\n  \n':
    graphql.FetchOutputDocument,
  '\n  query FetchOutputs($top: Int, $skip: Int, $filter: String) {\n    queryOutputsContentsWithTotal(\n      top: $top\n      skip: $skip\n      filter: $filter\n      orderby: "created desc"\n    ) {\n      total\n      items {\n        ...OutputData\n      }\n    }\n  }\n  \n':
    graphql.FetchOutputsDocument,
  '\n  fragment ProjectData on Projects {\n    id\n    flatData {\n      title\n      startDate\n      endDate\n      status\n      projectProposal\n      description\n      pmEmail\n      leadEmail\n      keywords\n      traineeProject\n      opportunitiesLink\n      members {\n        role\n        user {\n          id\n          created\n          lastModified\n          version\n          flatData {\n            avatar {\n              id\n            }\n            firstName\n            lastName\n            onboarded\n          }\n        }\n      }\n      milestones {\n        title\n        description\n        status\n        link\n      }\n      resources {\n        type\n        title\n        description\n        externalLink\n      }\n      calendars {\n        id\n        flatData {\n          name\n        }\n      }\n    }\n  }\n':
    graphql.ProjectDataFragmentDoc,
  '\n  query FetchProject($id: String!) {\n    findProjectsContent(id: $id) {\n      ...ProjectData\n    }\n  }\n  \n':
    graphql.FetchProjectDocument,
  '\n  query FetchProjects($top: Int, $skip: Int) {\n    queryProjectsContentsWithTotal(\n      top: $top\n      skip: $skip\n      orderby: "created desc"\n    ) {\n      total\n      items {\n        ...ProjectData\n      }\n    }\n  }\n  \n':
    graphql.FetchProjectsDocument,
  '\n  fragment UsersData on Users {\n    id\n    created\n    lastModified\n    version\n    flatData {\n      avatar {\n        id\n      }\n      connections {\n        code\n      }\n      degree\n      email\n      firstName\n      lastName\n      region\n      role\n      country\n      city\n      positions {\n        role\n        department\n        institution\n      }\n      questions {\n        question\n      }\n      onboarded\n      secondaryEmail\n      telephoneCountryCode\n      telephoneNumber\n      keywords\n      fundingStreams\n      biography\n      contributingCohorts {\n        role\n        study\n        id {\n          id\n          flatData {\n            name\n          }\n        }\n      }\n      social {\n        googleScholar\n        orcid\n        researchGate\n        researcherId\n        blog\n        twitter\n        linkedIn\n        github\n      }\n      activatedDate\n    }\n    referencingProjectsContents {\n      id\n      flatData {\n        members {\n          role\n          user {\n            id\n          }\n        }\n        status\n        title\n      }\n    }\n    referencingWorkingGroupsContents {\n      id\n      flatData {\n        members {\n          role\n          user {\n            id\n          }\n        }\n        title\n      }\n    }\n  }\n':
    graphql.UsersDataFragmentDoc,
  '\n  query FetchUser($id: String!) {\n    findUsersContent(id: $id) {\n      ...UsersData\n    }\n  }\n  \n':
    graphql.FetchUserDocument,
  '\n  query FetchUsers($top: Int, $skip: Int, $filter: String) {\n    queryUsersContentsWithTotal(\n      top: $top\n      skip: $skip\n      filter: $filter\n      orderby: "data/firstName/iv,data/lastName/iv"\n    ) {\n      total\n      items {\n        ...UsersData\n      }\n    }\n  }\n  \n':
    graphql.FetchUsersDocument,
  '\n  fragment ProjectMembersData on Projects {\n    flatData {\n      members {\n        user {\n          id\n        }\n      }\n    }\n  }\n':
    graphql.ProjectMembersDataFragmentDoc,
  '\n  query FetchProjectsMembers($filter: String) {\n    queryProjectsContents(filter: $filter) {\n      ...ProjectMembersData\n    }\n  }\n  \n':
    graphql.FetchProjectsMembersDocument,
  '\n  fragment WorkingGroupMembersData on WorkingGroups {\n    flatData {\n      members {\n        user {\n          id\n        }\n      }\n    }\n  }\n':
    graphql.WorkingGroupMembersDataFragmentDoc,
  '\n  query FetchWorkingGroupsMembers($filter: String) {\n    queryWorkingGroupsContents(filter: $filter) {\n      ...WorkingGroupMembersData\n    }\n  }\n  \n':
    graphql.FetchWorkingGroupsMembersDocument,
  '\n  fragment WorkingGroupNetworkData on WorkingGroupNetwork {\n    id\n    flatData {\n      support {\n        ...WorkingGroupData\n      }\n      complexDisease {\n        ...WorkingGroupData\n      }\n      monogenic {\n        ...WorkingGroupData\n      }\n      operational {\n        ...WorkingGroupData\n      }\n    }\n  }\n  \n':
    graphql.WorkingGroupNetworkDataFragmentDoc,
  '\n  query FetchWorkingGroupNetwork {\n    queryWorkingGroupNetworkContents {\n      ...WorkingGroupNetworkData\n    }\n  }\n  \n':
    graphql.FetchWorkingGroupNetworkDocument,
  '\n  fragment WorkingGroupData on WorkingGroups {\n    id\n    flatData {\n      title\n      shortDescription\n      leadingMembers\n      description\n      primaryEmail\n      secondaryEmail\n      members {\n        role\n        user {\n          id\n          created\n          lastModified\n          version\n          flatData {\n            avatar {\n              id\n            }\n            firstName\n            lastName\n            onboarded\n          }\n        }\n      }\n      milestones {\n        title\n        description\n        status\n        link\n      }\n      resources {\n        type\n        title\n        description\n        externalLink\n      }\n      calendars {\n        id\n        flatData {\n          name\n        }\n      }\n    }\n  }\n':
    graphql.WorkingGroupDataFragmentDoc,
  '\n  query FetchWorkingGroup($id: String!) {\n    findWorkingGroupsContent(id: $id) {\n      ...WorkingGroupData\n    }\n  }\n  \n':
    graphql.FetchWorkingGroupDocument,
  '\n  query FetchWorkingGroups {\n    queryWorkingGroupsContentsWithTotal(orderby: "created desc") {\n      total\n      items {\n        ...WorkingGroupData\n      }\n    }\n  }\n  \n':
    graphql.FetchWorkingGroupsDocument,
};

export function gql(
  source: '\n  fragment CalendarsData on Calendars {\n    id\n    created\n    lastModified\n    version\n    flatData {\n      googleCalendarId\n      name\n      color\n      syncToken\n      resourceId\n      expirationDate\n    }\n    referencingProjectsContents {\n      id\n      flatData {\n        title\n      }\n    }\n    referencingWorkingGroupsContents {\n      id\n      flatData {\n        title\n      }\n    }\n  }\n',
): (typeof documents)['\n  fragment CalendarsData on Calendars {\n    id\n    created\n    lastModified\n    version\n    flatData {\n      googleCalendarId\n      name\n      color\n      syncToken\n      resourceId\n      expirationDate\n    }\n    referencingProjectsContents {\n      id\n      flatData {\n        title\n      }\n    }\n    referencingWorkingGroupsContents {\n      id\n      flatData {\n        title\n      }\n    }\n  }\n'];
export function gql(
  source: '\n  query FetchCalendar($id: String!) {\n    findCalendarsContent(id: $id) {\n      ...CalendarsData\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchCalendar($id: String!) {\n    findCalendarsContent(id: $id) {\n      ...CalendarsData\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchCalendars($top: Int, $skip: Int, $filter: String, $order: String) {\n    queryCalendarsContentsWithTotal(\n      top: $top\n      skip: $skip\n      filter: $filter\n      orderby: $order\n    ) {\n      total\n      items {\n        ...CalendarsData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchCalendars($top: Int, $skip: Int, $filter: String, $order: String) {\n    queryCalendarsContentsWithTotal(\n      top: $top\n      skip: $skip\n      filter: $filter\n      orderby: $order\n    ) {\n      total\n      items {\n        ...CalendarsData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment ContributingCohortsData on ContributingCohorts {\n    id\n    flatData {\n      name\n    }\n  }\n',
): (typeof documents)['\n  fragment ContributingCohortsData on ContributingCohorts {\n    id\n    flatData {\n      name\n    }\n  }\n'];
export function gql(
  source: '\n  query FetchContributingCohorts($top: Int, $skip: Int) {\n    queryContributingCohortsContentsWithTotal(\n      top: $top\n      skip: $skip\n      orderby: "data/name/iv"\n    ) {\n      total\n      items {\n        ...ContributingCohortsData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchContributingCohorts($top: Int, $skip: Int) {\n    queryContributingCohortsContentsWithTotal(\n      top: $top\n      skip: $skip\n      orderby: "data/name/iv"\n    ) {\n      total\n      items {\n        ...ContributingCohortsData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment EventData on Events {\n    id\n    lastModified\n    version\n    created\n    flatData {\n      description\n      endDate\n      endDateTimeZone\n      startDate\n      startDateTimeZone\n      meetingLink\n      hideMeetingLink\n      eventLink\n      status\n      tags\n      title\n      notesPermanentlyUnavailable\n      notes\n      videoRecordingPermanentlyUnavailable\n      videoRecording\n      presentationPermanentlyUnavailable\n      presentation\n      meetingMaterialsPermanentlyUnavailable\n      meetingMaterials {\n        url\n        title\n      }\n      calendar {\n        flatData {\n          googleCalendarId\n          color\n          name\n        }\n        referencingProjectsContents {\n          ...ProjectData\n        }\n        referencingWorkingGroupsContents {\n          ...WorkingGroupData\n        }\n      }\n      thumbnail {\n        id\n      }\n      speakers {\n        user {\n          __typename\n          ... on Users {\n            id\n            flatData {\n              firstName\n              lastName\n              onboarded\n              avatar {\n                id\n              }\n            }\n          }\n          ... on ExternalUsers {\n            id\n            flatData {\n              name\n              orcid\n            }\n          }\n        }\n        topic\n      }\n    }\n  }\n  ,\n  \n',
): (typeof documents)['\n  fragment EventData on Events {\n    id\n    lastModified\n    version\n    created\n    flatData {\n      description\n      endDate\n      endDateTimeZone\n      startDate\n      startDateTimeZone\n      meetingLink\n      hideMeetingLink\n      eventLink\n      status\n      tags\n      title\n      notesPermanentlyUnavailable\n      notes\n      videoRecordingPermanentlyUnavailable\n      videoRecording\n      presentationPermanentlyUnavailable\n      presentation\n      meetingMaterialsPermanentlyUnavailable\n      meetingMaterials {\n        url\n        title\n      }\n      calendar {\n        flatData {\n          googleCalendarId\n          color\n          name\n        }\n        referencingProjectsContents {\n          ...ProjectData\n        }\n        referencingWorkingGroupsContents {\n          ...WorkingGroupData\n        }\n      }\n      thumbnail {\n        id\n      }\n      speakers {\n        user {\n          __typename\n          ... on Users {\n            id\n            flatData {\n              firstName\n              lastName\n              onboarded\n              avatar {\n                id\n              }\n            }\n          }\n          ... on ExternalUsers {\n            id\n            flatData {\n              name\n              orcid\n            }\n          }\n        }\n        topic\n      }\n    }\n  }\n  ,\n  \n'];
export function gql(
  source: '\n  query FetchEvents($top: Int, $skip: Int, $filter: String, $order: String) {\n    queryEventsContentsWithTotal(\n      top: $top\n      skip: $skip\n      filter: $filter\n      orderby: $order\n    ) {\n      total\n      items {\n        ...EventData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchEvents($top: Int, $skip: Int, $filter: String, $order: String) {\n    queryEventsContentsWithTotal(\n      top: $top\n      skip: $skip\n      filter: $filter\n      orderby: $order\n    ) {\n      total\n      items {\n        ...EventData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchEvent($id: String!) {\n    findEventsContent(id: $id) {\n      ...EventData\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchEvent($id: String!) {\n    findEventsContent(id: $id) {\n      ...EventData\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchGroupCalendar($id: String!) {\n    findProjectsContent(id: $id) {\n      flatData {\n        calendars {\n          id\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  query FetchGroupCalendar($id: String!) {\n    findProjectsContent(id: $id) {\n      flatData {\n        calendars {\n          id\n        }\n      }\n    }\n  }\n'];
export function gql(
  source: '\n  query FetchWorkingGroupCalendar($id: String!) {\n    findWorkingGroupsContent(id: $id) {\n      flatData {\n        calendars {\n          id\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  query FetchWorkingGroupCalendar($id: String!) {\n    findWorkingGroupsContent(id: $id) {\n      flatData {\n        calendars {\n          id\n        }\n      }\n    }\n  }\n'];
export function gql(
  source: '\n  fragment ExternalUsersData on ExternalUsers {\n    id\n    flatData {\n      name\n      orcid\n    }\n  }\n',
): (typeof documents)['\n  fragment ExternalUsersData on ExternalUsers {\n    id\n    flatData {\n      name\n      orcid\n    }\n  }\n'];
export function gql(
  source: '\n  query FetchExternalUser($id: String!) {\n    findExternalUsersContent(id: $id) {\n      ...ExternalUsersData\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchExternalUser($id: String!) {\n    findExternalUsersContent(id: $id) {\n      ...ExternalUsersData\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchExternalUsers($top: Int, $skip: Int, $filter: String) {\n    queryExternalUsersContentsWithTotal(\n      top: $top\n      skip: $skip\n      filter: $filter\n      orderby: "data/name/iv"\n    ) {\n      total\n      items {\n        ...ExternalUsersData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchExternalUsers($top: Int, $skip: Int, $filter: String) {\n    queryExternalUsersContentsWithTotal(\n      top: $top\n      skip: $skip\n      filter: $filter\n      orderby: "data/name/iv"\n    ) {\n      total\n      items {\n        ...ExternalUsersData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment NewsData on NewsAndEvents {\n    id\n    created\n    lastModified\n    version\n    flatData {\n      title\n      shortText\n      link\n      linkText\n      sampleCount\n      articleCount\n      cohortCount\n      link\n      linkText\n    }\n  }\n',
): (typeof documents)['\n  fragment NewsData on NewsAndEvents {\n    id\n    created\n    lastModified\n    version\n    flatData {\n      title\n      shortText\n      link\n      linkText\n      sampleCount\n      articleCount\n      cohortCount\n      link\n      linkText\n    }\n  }\n'];
export function gql(
  source: '\n  query FetchNews($top: Int, $skip: Int) {\n    queryNewsAndEventsContentsWithTotal(\n      top: $top\n      skip: $skip\n      orderby: "created desc"\n    ) {\n      total\n      items {\n        ...NewsData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchNews($top: Int, $skip: Int) {\n    queryNewsAndEventsContentsWithTotal(\n      top: $top\n      skip: $skip\n      orderby: "created desc"\n    ) {\n      total\n      items {\n        ...NewsData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment OutputData on Outputs {\n    id\n    created\n    lastModified\n    version\n    flatData {\n      title\n      documentType\n      type\n      subtype\n      link\n      addedDate\n      publishDate\n      lastUpdatedPartial\n      authors {\n        __typename\n        ... on Users {\n          id\n          created\n          lastModified\n          version\n          flatData {\n            avatar {\n              id\n            }\n            firstName\n            lastName\n            onboarded\n            email\n          }\n        }\n        ... on ExternalUsers {\n          id\n          created\n          lastModified\n          version\n          flatData {\n            name\n            orcid\n          }\n        }\n      }\n      workingGroups {\n        id\n        flatData {\n          title\n        }\n      }\n      projects {\n        id\n        flatData {\n          title\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  fragment OutputData on Outputs {\n    id\n    created\n    lastModified\n    version\n    flatData {\n      title\n      documentType\n      type\n      subtype\n      link\n      addedDate\n      publishDate\n      lastUpdatedPartial\n      authors {\n        __typename\n        ... on Users {\n          id\n          created\n          lastModified\n          version\n          flatData {\n            avatar {\n              id\n            }\n            firstName\n            lastName\n            onboarded\n            email\n          }\n        }\n        ... on ExternalUsers {\n          id\n          created\n          lastModified\n          version\n          flatData {\n            name\n            orcid\n          }\n        }\n      }\n      workingGroups {\n        id\n        flatData {\n          title\n        }\n      }\n      projects {\n        id\n        flatData {\n          title\n        }\n      }\n    }\n  }\n'];
export function gql(
  source: '\n  query FetchOutput($id: String!) {\n    findOutputsContent(id: $id) {\n      ...OutputData\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchOutput($id: String!) {\n    findOutputsContent(id: $id) {\n      ...OutputData\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchOutputs($top: Int, $skip: Int, $filter: String) {\n    queryOutputsContentsWithTotal(\n      top: $top\n      skip: $skip\n      filter: $filter\n      orderby: "created desc"\n    ) {\n      total\n      items {\n        ...OutputData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchOutputs($top: Int, $skip: Int, $filter: String) {\n    queryOutputsContentsWithTotal(\n      top: $top\n      skip: $skip\n      filter: $filter\n      orderby: "created desc"\n    ) {\n      total\n      items {\n        ...OutputData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment ProjectData on Projects {\n    id\n    flatData {\n      title\n      startDate\n      endDate\n      status\n      projectProposal\n      description\n      pmEmail\n      leadEmail\n      keywords\n      traineeProject\n      opportunitiesLink\n      members {\n        role\n        user {\n          id\n          created\n          lastModified\n          version\n          flatData {\n            avatar {\n              id\n            }\n            firstName\n            lastName\n            onboarded\n          }\n        }\n      }\n      milestones {\n        title\n        description\n        status\n        link\n      }\n      resources {\n        type\n        title\n        description\n        externalLink\n      }\n      calendars {\n        id\n        flatData {\n          name\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  fragment ProjectData on Projects {\n    id\n    flatData {\n      title\n      startDate\n      endDate\n      status\n      projectProposal\n      description\n      pmEmail\n      leadEmail\n      keywords\n      traineeProject\n      opportunitiesLink\n      members {\n        role\n        user {\n          id\n          created\n          lastModified\n          version\n          flatData {\n            avatar {\n              id\n            }\n            firstName\n            lastName\n            onboarded\n          }\n        }\n      }\n      milestones {\n        title\n        description\n        status\n        link\n      }\n      resources {\n        type\n        title\n        description\n        externalLink\n      }\n      calendars {\n        id\n        flatData {\n          name\n        }\n      }\n    }\n  }\n'];
export function gql(
  source: '\n  query FetchProject($id: String!) {\n    findProjectsContent(id: $id) {\n      ...ProjectData\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchProject($id: String!) {\n    findProjectsContent(id: $id) {\n      ...ProjectData\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchProjects($top: Int, $skip: Int) {\n    queryProjectsContentsWithTotal(\n      top: $top\n      skip: $skip\n      orderby: "created desc"\n    ) {\n      total\n      items {\n        ...ProjectData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchProjects($top: Int, $skip: Int) {\n    queryProjectsContentsWithTotal(\n      top: $top\n      skip: $skip\n      orderby: "created desc"\n    ) {\n      total\n      items {\n        ...ProjectData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment UsersData on Users {\n    id\n    created\n    lastModified\n    version\n    flatData {\n      avatar {\n        id\n      }\n      connections {\n        code\n      }\n      degree\n      email\n      firstName\n      lastName\n      region\n      role\n      country\n      city\n      positions {\n        role\n        department\n        institution\n      }\n      questions {\n        question\n      }\n      onboarded\n      secondaryEmail\n      telephoneCountryCode\n      telephoneNumber\n      keywords\n      fundingStreams\n      biography\n      contributingCohorts {\n        role\n        study\n        id {\n          id\n          flatData {\n            name\n          }\n        }\n      }\n      social {\n        googleScholar\n        orcid\n        researchGate\n        researcherId\n        blog\n        twitter\n        linkedIn\n        github\n      }\n      activatedDate\n    }\n    referencingProjectsContents {\n      id\n      flatData {\n        members {\n          role\n          user {\n            id\n          }\n        }\n        status\n        title\n      }\n    }\n    referencingWorkingGroupsContents {\n      id\n      flatData {\n        members {\n          role\n          user {\n            id\n          }\n        }\n        title\n      }\n    }\n  }\n',
): (typeof documents)['\n  fragment UsersData on Users {\n    id\n    created\n    lastModified\n    version\n    flatData {\n      avatar {\n        id\n      }\n      connections {\n        code\n      }\n      degree\n      email\n      firstName\n      lastName\n      region\n      role\n      country\n      city\n      positions {\n        role\n        department\n        institution\n      }\n      questions {\n        question\n      }\n      onboarded\n      secondaryEmail\n      telephoneCountryCode\n      telephoneNumber\n      keywords\n      fundingStreams\n      biography\n      contributingCohorts {\n        role\n        study\n        id {\n          id\n          flatData {\n            name\n          }\n        }\n      }\n      social {\n        googleScholar\n        orcid\n        researchGate\n        researcherId\n        blog\n        twitter\n        linkedIn\n        github\n      }\n      activatedDate\n    }\n    referencingProjectsContents {\n      id\n      flatData {\n        members {\n          role\n          user {\n            id\n          }\n        }\n        status\n        title\n      }\n    }\n    referencingWorkingGroupsContents {\n      id\n      flatData {\n        members {\n          role\n          user {\n            id\n          }\n        }\n        title\n      }\n    }\n  }\n'];
export function gql(
  source: '\n  query FetchUser($id: String!) {\n    findUsersContent(id: $id) {\n      ...UsersData\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchUser($id: String!) {\n    findUsersContent(id: $id) {\n      ...UsersData\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchUsers($top: Int, $skip: Int, $filter: String) {\n    queryUsersContentsWithTotal(\n      top: $top\n      skip: $skip\n      filter: $filter\n      orderby: "data/firstName/iv,data/lastName/iv"\n    ) {\n      total\n      items {\n        ...UsersData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchUsers($top: Int, $skip: Int, $filter: String) {\n    queryUsersContentsWithTotal(\n      top: $top\n      skip: $skip\n      filter: $filter\n      orderby: "data/firstName/iv,data/lastName/iv"\n    ) {\n      total\n      items {\n        ...UsersData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment ProjectMembersData on Projects {\n    flatData {\n      members {\n        user {\n          id\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  fragment ProjectMembersData on Projects {\n    flatData {\n      members {\n        user {\n          id\n        }\n      }\n    }\n  }\n'];
export function gql(
  source: '\n  query FetchProjectsMembers($filter: String) {\n    queryProjectsContents(filter: $filter) {\n      ...ProjectMembersData\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchProjectsMembers($filter: String) {\n    queryProjectsContents(filter: $filter) {\n      ...ProjectMembersData\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment WorkingGroupMembersData on WorkingGroups {\n    flatData {\n      members {\n        user {\n          id\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  fragment WorkingGroupMembersData on WorkingGroups {\n    flatData {\n      members {\n        user {\n          id\n        }\n      }\n    }\n  }\n'];
export function gql(
  source: '\n  query FetchWorkingGroupsMembers($filter: String) {\n    queryWorkingGroupsContents(filter: $filter) {\n      ...WorkingGroupMembersData\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchWorkingGroupsMembers($filter: String) {\n    queryWorkingGroupsContents(filter: $filter) {\n      ...WorkingGroupMembersData\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment WorkingGroupNetworkData on WorkingGroupNetwork {\n    id\n    flatData {\n      support {\n        ...WorkingGroupData\n      }\n      complexDisease {\n        ...WorkingGroupData\n      }\n      monogenic {\n        ...WorkingGroupData\n      }\n      operational {\n        ...WorkingGroupData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  fragment WorkingGroupNetworkData on WorkingGroupNetwork {\n    id\n    flatData {\n      support {\n        ...WorkingGroupData\n      }\n      complexDisease {\n        ...WorkingGroupData\n      }\n      monogenic {\n        ...WorkingGroupData\n      }\n      operational {\n        ...WorkingGroupData\n      }\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchWorkingGroupNetwork {\n    queryWorkingGroupNetworkContents {\n      ...WorkingGroupNetworkData\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchWorkingGroupNetwork {\n    queryWorkingGroupNetworkContents {\n      ...WorkingGroupNetworkData\n    }\n  }\n  \n'];
export function gql(
  source: '\n  fragment WorkingGroupData on WorkingGroups {\n    id\n    flatData {\n      title\n      shortDescription\n      leadingMembers\n      description\n      primaryEmail\n      secondaryEmail\n      members {\n        role\n        user {\n          id\n          created\n          lastModified\n          version\n          flatData {\n            avatar {\n              id\n            }\n            firstName\n            lastName\n            onboarded\n          }\n        }\n      }\n      milestones {\n        title\n        description\n        status\n        link\n      }\n      resources {\n        type\n        title\n        description\n        externalLink\n      }\n      calendars {\n        id\n        flatData {\n          name\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  fragment WorkingGroupData on WorkingGroups {\n    id\n    flatData {\n      title\n      shortDescription\n      leadingMembers\n      description\n      primaryEmail\n      secondaryEmail\n      members {\n        role\n        user {\n          id\n          created\n          lastModified\n          version\n          flatData {\n            avatar {\n              id\n            }\n            firstName\n            lastName\n            onboarded\n          }\n        }\n      }\n      milestones {\n        title\n        description\n        status\n        link\n      }\n      resources {\n        type\n        title\n        description\n        externalLink\n      }\n      calendars {\n        id\n        flatData {\n          name\n        }\n      }\n    }\n  }\n'];
export function gql(
  source: '\n  query FetchWorkingGroup($id: String!) {\n    findWorkingGroupsContent(id: $id) {\n      ...WorkingGroupData\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchWorkingGroup($id: String!) {\n    findWorkingGroupsContent(id: $id) {\n      ...WorkingGroupData\n    }\n  }\n  \n'];
export function gql(
  source: '\n  query FetchWorkingGroups {\n    queryWorkingGroupsContentsWithTotal(orderby: "created desc") {\n      total\n      items {\n        ...WorkingGroupData\n      }\n    }\n  }\n  \n',
): (typeof documents)['\n  query FetchWorkingGroups {\n    queryWorkingGroupsContentsWithTotal(orderby: "created desc") {\n      total\n      items {\n        ...WorkingGroupData\n      }\n    }\n  }\n  \n'];

export function gql(source: string): unknown;
export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
