export const TEAM_PERFORMANCE_INITIAL_DATA = {
  withinTeam: {
    article: {
      belowAverageMin: 0,
      belowAverageMax: 0,
      averageMin: 0,
      averageMax: 0,
      aboveAverageMin: 0,
      aboveAverageMax: 0,
    },
    bioinformatics: {
      belowAverageMin: 0,
      belowAverageMax: 0,
      averageMin: 0,
      averageMax: 0,
      aboveAverageMin: 0,
      aboveAverageMax: 0,
    },
    dataset: {
      belowAverageMin: 0,
      belowAverageMax: 0,
      averageMin: 0,
      averageMax: 0,
      aboveAverageMin: 0,
      aboveAverageMax: 0,
    },
    labMaterial: {
      belowAverageMin: 0,
      belowAverageMax: 0,
      averageMin: 0,
      averageMax: 0,
      aboveAverageMin: 0,
      aboveAverageMax: 0,
    },
    protocol: {
      belowAverageMin: 0,
      belowAverageMax: 0,
      averageMin: 0,
      averageMax: 0,
      aboveAverageMin: 0,
      aboveAverageMax: 0,
    },
  },
  acrossTeam: {
    article: {
      belowAverageMin: 0,
      belowAverageMax: 0,
      averageMin: 0,
      averageMax: 0,
      aboveAverageMin: 0,
      aboveAverageMax: 0,
    },
    bioinformatics: {
      belowAverageMin: 0,
      belowAverageMax: 0,
      averageMin: 0,
      averageMax: 0,
      aboveAverageMin: 0,
      aboveAverageMax: 0,
    },
    dataset: {
      belowAverageMin: 0,
      belowAverageMax: 0,
      averageMin: 0,
      averageMax: 0,
      aboveAverageMin: 0,
      aboveAverageMax: 0,
    },
    labMaterial: {
      belowAverageMin: 0,
      belowAverageMax: 0,
      averageMin: 0,
      averageMax: 0,
      aboveAverageMin: 0,
      aboveAverageMax: 0,
    },
    protocol: {
      belowAverageMin: 0,
      belowAverageMax: 0,
      averageMin: 0,
      averageMax: 0,
      aboveAverageMin: 0,
      aboveAverageMax: 0,
    },
  },
};
