name: Setup

on:
  workflow_call:
    inputs:
      image-name:
        description: 'Image Name'
        required: true
        type: string
    secrets:
      codecov-token:
        description: 'Codecov Token'
        required: true
jobs:
  image-names:
    permissions:
      packages: read
    runs-on: ubuntu-latest
    outputs:
      integration-image-name: ${{ steps.get-image-names.outputs.integration-image-name }}
      squidex-image-name: ${{ steps.get-image-names.outputs.squidex-image-name }}
    container:
      image: ${{ needs.setup.outputs.integration-image-name }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      CODECOV_TOKEN: ${{ secrets.codecov-token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Jest cache
        uses: actions/cache@v2
        id: jest-cache
        with:
          path: |
            .jest-cache/
          key: jest-cache
      - name: Test
        run: |
          yarn test --coverage --maxWorkers=2
          yarn codecov
