name: DEV - Sync Algolia with squidex V2
on:
  workflow_dispatch:
    inputs:
      entity:
        required: true
        type: choice
        description: Choose which entity to sync
        options:
          - users
          - research-outputs
          - external-authors
          - all
jobs:
  sync_dev_index:
    uses: ./.github/workflows/algolia-sync-v2.yml
    with:
      entity: ${{ github.event.inputs.entity }}
      ALGOLIA_INDEX: 'asap-hub_dev'
      SQUIDEX_APP_NAME: 'asap-hub-dev'
      SSM_ALGOLIA_APP_ID_NAME: 'algolia-app-id-dev'
      SSM_ALGOLIA_API_KEY_NAME: 'algolia-api-key-ci-dev'
    secrets:
      SQUIDEX_CLIENT_ID: ${{ secrets.SQUIDEX_CLIENT_ID_DEV }}
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET_DEV }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
