name: DEV - Create database backups
on:
  schedule:
    - cron: '0 7 * * MON-FRI' # At 07:00 UTC on every day-of-week from Monday through Friday.
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.image-name.outputs.image-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Image Name
        uses: ./.github/actions/ecr-registry
        id: image-name
        with:
          repository-name: asap-hub/squidex-utils
  make_squidex_backup:
    needs: setup
    runs-on: ubuntu-18.04
    container:
      image: ${{ needs.setup.outputs.image-name }}
      credentials:
        username: AWS
        password: ${{ secrets.AWS_ECR_PASSWORD }}
    env:
      SQUIDEX_APP: 'asap-hub-dev'
      BUCKET_NAME: 'asap-hub-dev-data-backup'
      SQUIDEX_CLIENT_ID: ${{ secrets.SQUIDEX_CLIENT_ID_DEV }}
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET_DEV }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Add the configuration
        run: echo "testing"
