name: Synchronize Development & Production
on:
  push:
    branches:
      - master
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'
jobs:
  sync_algolia_settings:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Development Environment Variables
        run: |
          echo "ALGOLIA_INDEX=asap-hub_dev" >> $GITHUB_ENV
          echo "ALGOLIA_APP_ID=$(aws ssm get-parameter --name 'algolia-app-id-dev' --query Parameter.Value --output text)" >> $GITHUB_ENV
          echo "ALGOLIA_API_KEY=$(aws ssm get-parameter --name 'algolia-api-key-ci-dev' --query Parameter.Value --output text)" >> $GITHUB_ENV
          echo "::add-mask::$(aws ssm get-parameter --name 'algolia-api-key-ci-dev' --query Parameter.Value --output text)"
      - name: Synchronize Development Schema
        run: yarn run algolia:upload
      - name: Setup Production Environment Variables
        run: |
          echo "ALGOLIA_INDEX=asap-hub_prod" >> $GITHUB_ENV
          echo "ALGOLIA_APP_ID=$(aws ssm get-parameter --name 'algolia-app-id-prod' --query Parameter.Value --output text)" >> $GITHUB_ENV
          echo "ALGOLIA_API_KEY=$(aws ssm get-parameter --name 'algolia-api-key-ci-prod' --query Parameter.Value --output text)" >> $GITHUB_ENV
          echo "::add-mask::$(aws ssm get-parameter --name 'algolia-api-key-ci-prod' --query Parameter.Value --output text)"
      - name: Synchronize Production Schema
        run: yarn run algolia:upload
      - uses: ./.github/actions/slack/
        if: failure()
        with:
          message: Algolia Development & Production Sync
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          status: failure
