name: Restore Contentful from backup
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Backup source environment to restore
        type: choice
        options:
          - Production
          - Development
      backup-version:
        required: false
        description: Backup file to restore - leave blank for latest
        type: string
      contentful-env:
        required: false
        type: string
        description: Contentful environment to restore into - leave blank to use Production/Development as selected above

jobs:
  restore-backup:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    container:
      image: ghcr.io/yldio/asap-hub/node-python-sq:7b77d99657ab3718ed548ba366ffbcbb15315fd8
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        id: setup
        uses: ./.github/actions/setup-environment
        with:
          environment-name: ${{ inputs.environment }}
      - name: restore backup
        uses: ./.github/actions/contentful-restore
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bucket-name: ${{ steps.setup.outputs.crn-contentful-backup-bucket-name }}
          backup-key: ${{ inputs.backup-version }}
          contentful-space-id: ${{ steps.setup.outputs.contentful-space-id }}
          contentful-environment: ${{ inputs.contentful-env || inputs.environment }}
          contentful-token: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
