name: Sync GP2 Algolia
on:
  workflow_dispatch:
    inputs:
      entity:
        required: false
        type: choice
        description: Choose which entity to sync
        default: all
        options:
          - outputs
          - all
      environment-name:
        required: true
        type: environment
        description: Choose which environment to sync
        default: Branch
      contentful-environment-id:
        required: true
        type: string
        description: The contentful environment to sync from
        default: Development
      pr-number:
        required: false
        type: string
        description: The PR number to run for

jobs:
  algolia:
    uses: ./.github/workflows/reusable-gp2-algolia-sync.yml
    with:
      environment-name: ${{ github.event.inputs.environment-name }}
      entity: ${{ github.event.inputs.entity }}
      pr-number: ${{ github.event.inputs.pr-number }}
      contentful-environment-id: ${{ github.event.inputs.contentful-environment-id }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GP2_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.GP2_CONTENTFUL_ACCESS_TOKEN }}
      CONTENTFUL_MANAGEMENT_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}

  notify_failure:
    runs-on: ubuntu-latest
    needs: [algolia]
    if: ${{ failure() && github.event.inputs.environment-name=='Production' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/slack/
        with:
          message: GP2 Algolia Prod Sync
          webhook: ${{ env.SLACK_WEBHOOK }}
          status: failure
