name: Migrate preprint versions
on:
  workflow_dispatch:

jobs:
  backup_crn:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yldio/asap-hub/node-python-sq:86a189edc900d4e1afdcf3935c697292f69d409b
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    environment: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        id: setup
        uses: ./.github/actions/setup-environment
        with:
          environment-name: Development
      - name: Backup
        uses: ./.github/actions/contentful-backup
        with:
          app: 'crn'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bucket-name: ${{ steps.setup.outputs.crn-contentful-backup-bucket-name }}
          contentful-space-id: ${{ steps.setup.outputs.crn-contentful-space-id }}
          contentful-environment: ${{ steps.setup.outputs.contentful-environment }}
          contentful-token: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
          data-bucket-name: ${{ steps.setup.outputs.crn-data-backup-bucket-name }}
