name: OpenSearch Analytics Sync
on:
  workflow_dispatch:
    inputs:
      metric:
        required: true
        type: choice
        description: Choose which metric to sync
        default: os-champion
        options:
          - os-champion
          - all
      environment-name:
        required: true
        type: choice
        description: Choose which environment to sync
        default: Branch
        options:
          - Branch
          - Development
          - Production
      contentful-environment-id:
        required: true
        type: string
        description: The contentful environment to sync from
        default: Development

jobs:
  opensearch-index:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment-name }}
    container:
      image: ghcr.io/yldio/asap-hub/node-python-sq:86a189edc900d4e1afdcf3935c697292f69d409b
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        id: setup
        uses: ./.github/actions/setup-environment
        with:
          environment-name: ${{ github.event.inputs.environment-name }}
      - name: Build
        run: |
          yarn install
          yarn exec "yarn workspaces foreach -vptR --from '{@asap-hub/model,@asap-hub/server-common,@asap-hub/crn-server}' run build:babel"
          yarn build:typecheck
      - name: Run OpenSearch Sync
        run: |
          yarn workspace @asap-hub/crn-server sync:open-search ${{ github.event.inputs.metric }}
        env:
          CONTENTFUL_SPACE_ID: ${{ steps.setup.outputs.crn-contentful-space-id }}
          CONTENTFUL_ENV_ID: ${{ github.event.inputs.contentful-environment-id }}
          CONTENTFUL_MANAGEMENT_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CRN_CONTENTFUL_ACCESS_TOKEN }}

          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ steps.setup.outputs.aws-default-region }}

          OPENSEARCH_USERNAME: ${{ secrets.AWS_OS_USERNAME }}
          OPENSEARCH_PASSWORD: ${{ secrets.AWS_OS_PASSWORD }}
          ENVIRONMENT: ${{ github.event.inputs.environment-name }}

  notify_failure:
    runs-on: ubuntu-latest
    needs: [opensearch-index]
    if: ${{ failure() && github.event.inputs.environment-name=='production' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/slack/
        with:
          message: OpenSearch Analytics Sync
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          status: failure
