name: Migrate preprint versions
on:
  workflow_dispatch:

jobs:
  migrate_preprint_versions:
    runs-on: ubuntu-latest
    environment: Production
    container:
      image: ghcr.io/yldio/asap-hub/node-python-sq:7b77d99657ab3718ed548ba366ffbcbb15315fd8
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        id: setup
        uses: ./.github/actions/setup-environment
        with:
          environment-name: Production
      - name: Run Preprint Version Migration
        run: |
          yarn workspace @asap-hub/contentful migrate-preprint-versions
        env:
          CONTENTFUL_MANAGEMENT_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ steps.setup.outputs.crn-contentful-space-id }}
          CONTENTFUL_ENV_ID: Production

  notify_failure:
    runs-on: ubuntu-latest
    needs: [migrate_preprint_versions]
    if: ${{ failure() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/slack/
        with:
          message: Migrate preprint versions failed
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          status: failure
