name: Pipeline development and production

on:
  push:
    branches:
      - CRN-595-deploy-to-development
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      environment-name: Development
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET }}

  build-images:
    uses: ./.github/workflows/reusable-build-images.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION_ECR: ${{ secrets.AWS_REGION_ECR }}

  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      environment-name: Development
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      LIGHTSTEP_TOKEN: ${{ secrets.LIGHTSTEP_TOKEN }}
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET }}
      SQUIDEX_SHARED_SECRET: ${{ secrets.SQUIDEX_SHARED_SECRET }}

  build-analysis:
    needs: [build]
    uses: ./.github/workflows/reusable-build-analysis.yml
    with:
      environment-name: Development
    secrets:
      BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}

  deployment:
    needs: [test, build-analysis]
    uses: ./.github/workflows/reusable-deployment.yml
    if: github.event_name == 'workflow_dispatch'
    with:
      environment-name: Development
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      LIGHTSTEP_TOKEN: ${{ secrets.LIGHTSTEP_TOKEN }}
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET }}
      SQUIDEX_SHARED_SECRET: ${{ secrets.SQUIDEX_SHARED_SECRET }}

  verify:
    needs: [deployment]
    uses: ./.github/workflows/reusable-verify.yml
    with:
      environment-name: Development
    secrets:
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET }}

  # notify_failure:
  #   runs-on: ubuntu-latest
  #   needs:
  #     [
  #       setup,
  #       test,
  #       build,
  #       deploy-sls,
  #       verify,
  #     ]
  #   if: ${{ failure() }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - uses: ./.github/actions/slack/
  #       with:
  #         message: 'Build Failed on GitHub: ${{ needs.setup.outputs.pr-number || github.head_ref }}'
  #         webhook: ${{ secrets.SLACK_WEBHOOK }}
  #         status: failure

  master-pipeline-success:
    runs-on: ubuntu-latest
    needs: [verify, build-images]
    if: ${{ success() }}
    environment:
      name: Branch
      url: ${{ steps.setup.outputs.asap-app-url }}
    steps:
      - name: Print success
        run: |
          echo "Pipeline development and production successful."
