name: Pipeline development and production

on:
  push:
    branches:
      - CRN-713-build-test-and-check-in-github-for-dev-2
jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      environment-name: Development
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET }}

  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      environment-name: Development
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      LIGHTSTEP_TOKEN: ${{ secrets.LIGHTSTEP_TOKEN }}
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET }}
      SQUIDEX_SHARED_SECRET: ${{ secrets.SQUIDEX_SHARED_SECRET }}

  build-analysis:
    needs: [build]
    uses: ./.github/workflows/reusable-build-analysis.yml
    secrets:
      BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}

  # notify_failure:
  #   runs-on: ubuntu-latest
  #   needs:
  #     [
  #       setup,
  #       test,
  #       build,
  #       deploy-sls,
  #       verify,
  #     ]
  #   if: ${{ failure() }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - uses: ./.github/actions/slack/
  #       with:
  #         message: 'Build Failed on GitHub: ${{ needs.setup.outputs.pr-number || github.head_ref }}'
  #         webhook: ${{ secrets.SLACK_WEBHOOK }}
  #         status: failure

  build-pipeline-success:
    runs-on: ubuntu-latest
    needs: [build-analysis, test]
    if: ${{ success() }}
    steps:
      - name: Print success
        run: |
          echo "Pipeline development and production successful."
