name: Continuous Integration

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  test:
    needs: [setup]
    uses: ./.github/workflows/reusable-test.yml
    with:
      environment-name: Branch
      image-name: ${{ needs.setup.outputs.integration-image-name }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET }}

  build:
    needs: [setup]
    uses: ./.github/workflows/reusable-build.yml
    with:
      environment-name: Branch
      image-name: ${{ needs.setup.outputs.integration-image-name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      LIGHTSTEP_TOKEN: ${{ secrets.LIGHTSTEP_TOKEN }}
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET }}
      SQUIDEX_SHARED_SECRET: ${{ secrets.SQUIDEX_SHARED_SECRET }}

  build-analysis:
    needs: [setup, build]
    uses: ./.github/workflows/reusable-build-analysis.yml
    with:
      image-name: ${{ needs.setup.outputs.integration-image-name }}
    secrets:
      BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}

  prepare-squidex:
    permissions:
      packages: read
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    container:
      image: ${{ needs.setup.outputs.integration-image-name }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    environment: Branch
    env:
      SQUIDEX_APP_NAME: ${{ needs.setup.outputs.pr-number }}
      SQUIDEX_CLIENT_ID: ${{ secrets.SQUIDEX_CLIENT_ID }}
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET }}
      SQUIDEX_BASE_URL: ${{ secrets.SQUIDEX_BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          environment-name: ${{ secrets.ENVIRONMENT_NAME }}
      - name: Prepare
        uses: ./.github/actions/prepare-squidex
        if: ${{ github.event.action == 'opened' }}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ env.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          squidex-app-name: ${{ env.SQUIDEX_APP_NAME }}
          squidex-base-url: ${{ env.SQUIDEX_BASE_URL }}
          squidex-client-id: ${{ env.SQUIDEX_CLIENT_ID }}
          squidex-client-secret: ${{ secrets.SQUIDEX_CLIENT_SECRET }}

  deployment:
    needs: [setup, test, build-analysis, prepare-squidex]
    uses: ./.github/workflows/reusable-deployment.yml
    with:
      environment-name: Branch
      image-name: ${{ needs.setup.outputs.integration-image-name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      LIGHTSTEP_TOKEN: ${{ secrets.LIGHTSTEP_TOKEN }}
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET }}
      SQUIDEX_SHARED_SECRET: ${{ secrets.SQUIDEX_SHARED_SECRET }}

  verify:
    needs: [setup, deployment, prepare-squidex]
    uses: ./.github/workflows/reusable-verify.yml
    with:
      environment-name: Branch
      image-name: ${{ needs.setup.outputs.integration-image-name }}
    secrets:
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET }}

  # notify_failure:
  #   runs-on: ubuntu-latest
  #   needs:
  #     [
  #       setup,
  #       test,
  #       build,
  #       deploy-sls,
  #       verify,
  #     ]
  #   if: ${{ failure() }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - uses: ./.github/actions/slack/
  #       with:
  #         message: 'Build Failed on GitHub: ${{ needs.setup.outputs.pr-number || github.head_ref }}'
  #         webhook: ${{ secrets.SLACK_WEBHOOK }}
  #         status: failure

  build-pipeline-success:
    runs-on: ubuntu-latest
    needs: [verify]
    if: ${{ success() }}
    steps:
      - name: Print success
        run: |
          echo "Build Successful."
