name: Continuous Integration

on:
  push:
    branches:
      - '!master'
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Get branch
        uses: rlespinasse/github-slug-action@3.6.0
      - name: Lint
        run: yarn run lint:format
      - name: Build
        run: |
          source ci/env-setup.sh
          yarn run build
        env:
          NODE_ENV: 'production'
      - name: Test
        run: yarn run test --coverage
