name: Pipeline branch

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      environment-name: Branch
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET }}

  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      environment-name: Branch
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      LIGHTSTEP_TOKEN: ${{ secrets.LIGHTSTEP_TOKEN }}
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET }}
      SQUIDEX_SHARED_SECRET: ${{ secrets.SQUIDEX_SHARED_SECRET }}
      GP2_AUTH0_SHARED_SECRET: ${{ secrets.GP2_AUTH0_SHARED_SECRET }}

  build-analysis:
    needs: [build]
    uses: ./.github/workflows/reusable-build-analysis.yml
    with:
      environment-name: Branch
    secrets:
      BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}

  create-environment:
    uses: ./.github/workflows/reusable-create-environment.yml
    with:
      environment-name: Branch
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET }}
      SQUIDEX_SHARED_SECRET: ${{ secrets.SQUIDEX_SHARED_SECRET }}

  deployment:
    needs: [test, build-analysis, create-environment]
    uses: ./.github/workflows/reusable-deployment.yml
    with:
      environment-name: Branch
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      LIGHTSTEP_TOKEN: ${{ secrets.LIGHTSTEP_TOKEN }}
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET }}
      SQUIDEX_SHARED_SECRET: ${{ secrets.SQUIDEX_SHARED_SECRET }}
      GP2_AUTH0_SHARED_SECRET: ${{ secrets.GP2_AUTH0_SHARED_SECRET }}

  verify:
    needs: [deployment]
    uses: ./.github/workflows/reusable-verify.yml
    with:
      environment-name: Branch
    secrets:
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET }}

  branch-pipeline-success:
    runs-on: ubuntu-latest
    environment:
      name: Branch
      url: ${{ steps.setup.outputs.crn-app-url }}
    needs: [test, build, build-analysis, create-environment, deployment, verify]
    if: ${{ always() }}
    steps:
      - name: Checkout
        if: ${{ success() }}
        uses: actions/checkout@v3
      - name: Setup
        id: setup
        uses: ./.github/actions/setup-environment
        with:
          environment-name: Branch
      - name: Print status
        run: |
          echo "# Pipeline branch CI/CD" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "## Summary" >> $GITHUB_STEP_SUMMARY
          echo "| stage | status |" >> $GITHUB_STEP_SUMMARY
          echo "| ----- | ------ |" >> $GITHUB_STEP_SUMMARY
          echo "| test  | ${{ needs.test.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| build | ${{ needs.build.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| build-analysis | ${{ needs.build-analysis.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| create-environment | ${{ needs.create-environment.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| deployment | ${{ needs.deployment.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| verify | ${{ needs.verify.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
      - name: test
        if: ${{ contains(needs.build.result, 'success')}}
        run: |
          echo "build Success!" >> $GITHUB_STEP_SUMMARY
      - name: On failure
        if: ${{ !contains(needs.verify.result, 'success')}}
        run: |
            echo "Failed! :fire:" >> $GITHUB_STEP_SUMMARY
            exit 1
      - name: On success
        run: |
          echo "Success! :rocket:" >> $GITHUB_STEP_SUMMARY
