name: DEV - Create database backups
on:
  schedule:
    - cron: '0 7 * * MON-FRI' # At 07:00 UTC on every day-of-week from Monday through Friday.
  workflow_dispatch:
jobs:
  make_squidex_backup:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yldio/asap-hub/node-python-sq:1de8c60b2214fbca2e0959aa7f473c55bbc2e014
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    environment: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        id: setup
        uses: ./.github/actions/setup-environment
        with:
          environment-name: Development
      - name: Backup
        uses: ./.github/actions/backup-squidex
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          squidex-app-name: ${{ steps.setup.outputs.squidex-app-name }}
          squidex-backup-bucket-name: ${{ steps.setup.outputs.squidex-backup-bucket-name }}
          squidex-client-id: ${{ steps.setup.outputs.squidex-client-id }}
          squidex-client-secret: ${{ secrets.SQUIDEX_CLIENT_SECRET }}

  make_algolia_backup:
    runs-on: ubuntu-18.04
    env:
      BUCKET_NAME: 'asap-hub-dev-algolia-backup'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-east-1'
      ALGOLIA_INDEX: 'asap-hub_dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch the Algolia keys
        run: |
          echo "ALGOLIA_APP_ID=$(aws ssm get-parameter --name 'algolia-app-id-dev' --query Parameter.Value --output text)" >> $GITHUB_ENV
          echo "ALGOLIA_API_KEY=$(aws ssm get-parameter --name 'algolia-api-key-ci-dev' --query Parameter.Value --output text)" >> $GITHUB_ENV
      - name: Run the backup
        run: |
          export DIR_NAME=$(date +%s| cut -b1-13)
          mkdir $DIR_NAME
          yarn workspace @asap-hub/crn-server run algolia export -a $ALGOLIA_APP_ID -k $ALGOLIA_API_KEY -n $ALGOLIA_INDEX -o "../../$DIR_NAME"
          echo "DIR_NAME=$DIR_NAME" >> $GITHUB_ENV
      - name: Upload to S3
        run: |
          aws s3 cp $DIR_NAME s3://$BUCKET_NAME/$DIR_NAME --recursive --storage-class STANDARD_IA
