name: DEV - Sync Open Search
on:
  schedule:
    - cron: '0 6 * * *' # At 06:00 UTC, everyday.
  workflow_dispatch:

jobs:
  sync-opensearch:
    uses: ./.github/workflows/reusable-crn-opensearch-sync.yml
    with:
      metric: all
      environment-name: Development
      contentful-environment-id: Development
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CRN_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CRN_CONTENTFUL_ACCESS_TOKEN }}
      CONTENTFUL_MANAGEMENT_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
      AWS_OS_USERNAME: ${{ secrets.AWS_OS_USERNAME }}
      AWS_OS_PASSWORD: ${{ secrets.AWS_OS_PASSWORD }}
