name: PROD - Sync Algolia with squidex V2
on:
  schedule:
    - cron: '0 10 * * *' # Once a day: 10am
  workflow_dispatch:
    inputs:
      entity:
        required: false
        type: choice
        description: Choose which entity to sync
        default: all
        options:
          - users
          - research-outputs
          - external-authors
          - all
jobs:
  sync_prod_index:
    uses: ./.github/workflows/algolia-sync-v2.yml
    with:
      entity: ${{ github.event.inputs.entity }}
      ALGOLIA_INDEX: 'asap-hub_prod'
      SQUIDEX_APP_NAME: 'asap-hub'
      SSM_ALGOLIA_APP_ID_NAME: 'algolia-app-id-prod'
      SSM_ALGOLIA_API_KEY_NAME: 'algolia-api-key-ci-prod'
    secrets:
      SQUIDEX_CLIENT_ID: ${{ secrets.SQUIDEX_CLIENT_ID_PROD }}
      SQUIDEX_CLIENT_SECRET: ${{ secrets.SQUIDEX_CLIENT_SECRET_PROD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-east-1'
      ALGOLIA_INDEX: 'asap-hub_prod'
      ALGOLIA_INDEX_TEMP: 'asap-hub_prod_temp'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: yarn build
      - name: Setup Environment Variables
        run: |
          echo "ALGOLIA_APP_ID=$(aws ssm get-parameter --name 'algolia-app-id-prod' --query Parameter.Value --output text)" >> $GITHUB_ENV
          echo "ALGOLIA_API_KEY=$(aws ssm get-parameter --name 'algolia-api-key-ci-prod' --query Parameter.Value --output text)" >> $GITHUB_ENV
          echo "::add-mask::$(aws ssm get-parameter --name 'algolia-api-key-ci-prod' --query Parameter.Value --output text)"
      - name: Copy index without data to a temporary index (ALL)
        if: ${{ github.event.inputs.entity == 'all'}}
        run: yarn workspace @asap-hub/algolia run algolia transferindexconfig -a $ALGOLIA_APP_ID -k $ALGOLIA_API_KEY -n $ALGOLIA_INDEX -d $ALGOLIA_APP_ID -y $ALGOLIA_API_KEY -i $ALGOLIA_INDEX_TEMP
      - name: Copy index with data to a temporary index (ENTITY)
        if: ${{ github.event.inputs.entity != 'all'}}
        run: yarn workspace @asap-hub/algolia run algolia transferindex -a $ALGOLIA_APP_ID -k $ALGOLIA_API_KEY -n $ALGOLIA_INDEX -d $ALGOLIA_APP_ID -y $ALGOLIA_API_KEY -i $ALGOLIA_INDEX_TEMP
      - name: Remove the entity data (ENTITY)
        if: ${{ github.event.inputs.entity != 'all'}}
        env:
          ENTITY_TYPE: ${{ github.event.inputs.entity == 'users' && 'user' || 'research-output' }}
        run: yarn algolia:remove-records -a $ALGOLIA_APP_ID -k $ALGOLIA_API_KEY -n $ALGOLIA_INDEX -e $ENTITY_TYPE
      - name: Import Research Outputs (ROs | ALL)
        if: ${{ github.event.inputs.entity == 'research-outputs' || github.event.inputs.entity == 'all'}}
        env:
          ENTITY: 'research-outputs'
          ENTITY_TYPE: 'research-output'
        run: |
          yarn export:entity $ENTITY -f $ENTITY.json
          yarn workspace @asap-hub/algolia run algolia import -s "../../${ENTITY}.json" -a $ALGOLIA_APP_ID -k $ALGOLIA_API_KEY -n $ALGOLIA_INDEX_TEMP -t ./scripts/algolia-transformation.js
      - name: Import Users (USERs | ALL)
        if: ${{ github.event.inputs.entity == 'users' || github.event.inputs.entity == 'all'}}
        env:
          ENTITY: 'users'
          ENTITY_TYPE: 'user'
        run: |
          yarn export:entity $ENTITY -f $ENTITY.json
          yarn workspace @asap-hub/algolia run algolia import -s "../../${ENTITY}.json" -a $ALGOLIA_APP_ID -k $ALGOLIA_API_KEY -n $ALGOLIA_INDEX_TEMP -t ./scripts/algolia-transformation.js
      - name: Import External Authors (EXTERNAL_AUTHORS | ALL)
        if: ${{ github.event.inputs.entity == 'external-authors' || github.event.inputs.entity == 'all'}}
        env:
          ENTITY: 'external-authors'
          ENTITY_TYPE: 'external-author'
        run: |
          yarn export:entity $ENTITY -f $ENTITY.json
          yarn workspace @asap-hub/algolia run algolia import -s "../../${ENTITY}.json" -a $ALGOLIA_APP_ID -k $ALGOLIA_API_KEY -n $ALGOLIA_INDEX_TEMP -t ./scripts/algolia-transformation.js
      - name: Override prod index with the temp one
        run: yarn algolia:move-index -a $ALGOLIA_APP_ID -k $ALGOLIA_API_KEY -n $ALGOLIA_INDEX_TEMP -i $ALGOLIA_INDEX
      - uses: ./.github/actions/slack/
        if: failure()
        with:
          message: Algolia Prod Sync
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          status: failure
