name: Contentful App Extensions Deploy

on:
  workflow_call:
    inputs:
      environment-name:
        description: 'The environment name'
        required: true
        type: string
    secrets:
      CONTENTFUL_MANAGEMENT_ACCESS_TOKEN:
        description: 'Contentful Management Token'
        required: true
jobs:
  app-extensions-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    container:
      image: ghcr.io/yldio/asap-hub/node-python-sq:f93db8bae8be7528565c2510dbc8e3eece97983d
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        id: setup
        uses: ./.github/actions/setup-environment
        with:
          environment-name: ${{ inputs.environment-name }}
      - name: Build apps
        run: yarn workspaces foreach -j 2 --include "*/contentful-app-*" -vp run build

      - name: Deploy App Disabled Fields
        uses: contentful/actions-app-deploy@v1
        with:
          organization-id: ${{ steps.setup.outputs.contentful-organization-id }}
          app-definition-id: ${{ steps.setup.outputs.contentful-app-disabled-fields }}
          access-token: ${{ secrets.CONTENTFUL_MANAGEMENT_ACCESS_TOKEN }}
          folder: packages/contentful-app-extensions/disabled-fields/build
      - name: Deploy App Event Additional Materials
        uses: contentful/actions-app-deploy@v1
        with:
          organization-id: ${{ steps.setup.outputs.contentful-organization-id }}
          app-definition-id: ${{ steps.setup.outputs.contentful-app-event-additional-materials }}
          access-token: ${{ secrets.CONTENTFUL_MANAGEMENT_ACCESS_TOKEN }}
          folder: packages/contentful-app-extensions/event-additional-materials/build
      - name: Deploy App Event Speakers Title
        uses: contentful/actions-app-deploy@v1
        with:
          organization-id: ${{ steps.setup.outputs.contentful-organization-id }}
          app-definition-id: ${{ steps.setup.outputs.contentful-app-event-speakers-title }}
          access-token: ${{ secrets.CONTENTFUL_MANAGEMENT_ACCESS_TOKEN }}
          folder: packages/contentful-app-extensions/event-speakers-title/build
      - name: Deploy App Field As Updated At
        uses: contentful/actions-app-deploy@v1
        with:
          organization-id: ${{ steps.setup.outputs.contentful-organization-id }}
          app-definition-id: ${{ steps.setup.outputs.contentful-app-field-as-updated-at }}
          access-token: ${{ secrets.CONTENTFUL_MANAGEMENT_ACCESS_TOKEN }}
          folder: packages/contentful-app-extensions/field-as-updated-at/build
