name: Build Docker Images

on:
  workflow_call:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build integration
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME: asap-hub/node-python-sq
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $IMAGE_NAME . -f .github/Dockerfile --target integration
          GHCR_IMAGE_NAME=ghcr.io/yldio/$IMAGE_NAME
          docker tag $IMAGE_NAME $GHCR_IMAGE_NAME:$IMAGE_TAG
          docker tag $IMAGE_NAME $GHCR_IMAGE_NAME:latest
          echo "GHCR_IMAGE_NAME=$GHCR_IMAGE_NAME" >> $GITHUB_ENV
      - name: push integration
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          docker push --all-tags ${{ env.GHCR_IMAGE_NAME }}
