name: Pipeline Test

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
  push:
    branches:
      - CRN-713-build-test-and-check-in-github-for-dev-2
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      EVENT_NAME: ${{ github.event_name }}
    outputs:
      environment-name: ${{ steps.get-name.outputs.environment-name }}
    steps:
      - name: Get Environment name
        id: get-name
        run: |
          echo "${{ github.event_name }}"
          echo "$EVENT_NAME"

          if [ "$EVENT_NAME" = "pull_request" ]; then
          # if [ "$EVENT_NAME" = "push" ]; then
            ENVIRONMENT_NAME=Branch
          else
            ENVIRONMENT_NAME=Development
          fi
          echo "::set-output name=environment-name::$ENVIRONMENT_NAME"
          echo $ENVIRONMENT_NAME

  test:
    needs: [setup]
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_NAME: ${{ needs.setup.outputs.environment-name }}
    steps:
      - name: Test
        run: |
          echo "Testing $ENVIRONMENT_NAME"
          exit 1

  build:
    needs: [setup, test]
    runs-on: ubuntu-latest
    environment: ${{ needs.setup.outputs.environment-name }}
    env:
      ENVIRONMENT_NAME: ${{ needs.setup.outputs.environment-name }}
    steps:
      - name: Build
        run: |
          echo "Build $ENVIRONMENT_NAME"

  deploy:
    needs: [setup, build]
    runs-on: ubuntu-latest
    environment: ${{ needs.setup.outputs.environment-name }}
    env:
      ENVIRONMENT_NAME: ${{ needs.setup.outputs.environment-name }}
    steps:
      - name: Deploy
        run: |
          echo "Deploy $ENVIRONMENT_NAME"

  verify:
    needs: [setup, deploy]
    runs-on: ubuntu-latest
    environment: ${{ needs.setup.outputs.environment-name }}
    env:
      ENVIRONMENT_NAME: ${{ needs.setup.outputs.environment-name }}
    steps:
      - name: Verify
        run: |
          echo "Verify $ENVIRONMENT_NAME"

  pr-success:
    needs: [setup, verify]
    if: ${{ github.event_name == 'pull_request' &&
      needs.setup.outputs.environment-name == 'Branch'
      }}
    runs-on: ubuntu-latest
    environment: ${{ needs.setup.outputs.environment-name }}
    env:
      ENVIRONMENT_NAME: ${{ needs.setup.outputs.environment-name }}
    steps:
      - name: Success
        run: |
          echo "PR Success $ENVIRONMENT_NAME"

  build-production:
    needs: [setup, verify]
    if: ${{ github.event_name == 'push' &&
      needs.setup.outputs.environment-name == 'Development'
      }}
    runs-on: ubuntu-latest
    environment: Production
    env:
      ENVIRONMENT_NAME: Production
    steps:
      - name: Build
        run: |
          echo "Build $ENVIRONMENT_NAME"

  deploy-production:
    needs: [build-production]
    runs-on: ubuntu-latest
    environment: Production
    env:
      ENVIRONMENT_NAME: Production
    steps:
      - name: Deploy
        run: |
          echo "Deploy $ENVIRONMENT_NAME"

  verify-production:
    needs: [deploy-production]
    runs-on: ubuntu-latest
    environment: Production
    env:
      ENVIRONMENT_NAME: Production
    steps:
      - name: Verify
        run: |
          echo "Verify $ENVIRONMENT_NAME"
